### ISSUE TITLE
[view] summary 에서의 design space 설정

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#104]
오늘 회의에서 @ytaek 님께서도 말씀해주셨다시피 0.2 버전을 대비하여
지금부터 얘기해보면 좋을 것 같아 우선 이슈부터 세웁니다.

## 고민했던 부분들과 답
1. 데이터를 가공해서 시각화할 때 어떤 컬러 조합을 위주로 사용해야 하는가? -> 이 부분은 세미나에서도 얘기 나왔었던 것 같은데 그때 책을 언급해주셨던 것 같거든요 혹시 기억나시는 분이나 영택님께서 다시 알려주시면 해당 책 빠르게 읽고 저희에게 필요한 부분 요약해서 코멘트로 달겠습니다.
2. 마지막 배열의 메시지를 보여주는 것도 좋지만 (임시적으로) 우선 키워드를 가지고 보여주는 것도 좋은 것 같아서 한 개의 클러스터에 있는 메시지의 맨 앞 단어만 가져와서 count 한 후에 가장 많이 나온 단어를 크기와 색깔로 구분하는 방식으로 가보는 건 어떨지?
3. content 부분에서 커밋 메시지 키워드를 count하여 많이 나온 단어부터 보여주도록 하였는데 여기서 font size 등으로 style에 변화를 주는 것이 괜찮은 부분인지?
4. 이전에는 아래 그림과 같이 author가 중복 제거 되지 않고 있어 많이 나오는 나머지 최대한 붙였습니다만
![image](https://user-images.githubusercontent.com/41473964/188940795-7f6ed3f5-86ea-4a62-94df-f058afbd5d34.png)
>  user avatar(동그란거)가 겹쳐져 있는부분이 커서 구분이 안되니 최소한으로 붙이는게 좋아보입니당. (github도 아마 겹치는 부분 조금만 한듯)
아, 그리고 단어를 크기와 색깔로 구분하는 건 하지 않는 것이 좋겠습니다.
이미 user avatar에서 칼라 채널을 사용하고 있고, 
여러가지가 들어가면 user가 읽기 힘들어져서요.
굳이 하고 싶다면 크기.. 정도인데, 작은 공간에서 크기차이가 주는게 얼마나 효용성이 있는지는 좀 볼필요가 있는데요

이런 의견이 있어서 프로필 이미지 간격 넓히고 키워드에서 색으로 구분하는 것은 제거했습니다.

와 같이 고민해보고 의견 구한 후 피드백에 맞춰 수정해보는 방식으로 현재 결과가 나왔습니다.

## 고민해보면 좋은 질문
by @ytaek 님
> 1. 저 시각화 mark, channel을 왜 정했는지?
> 2. 그리고 다른 것과 비교했을 때 이게 최선인지?

**Comment by ytaek** [comment]
이 부분은 진행해보면 좋을 것 같은데,
어떤 contents로 들어갈지 정해진 다음에 다시 얘기해보면 좋을 것 같네요.
