### ISSUE TITLE
[view] CLOC line chart height 밀리는 현상

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#110]
데이터 통합하는 과정에서 발견한 현상입니다. summary에서 클릭했을 때 CLOC line chart height이 계속 밀리고 있습니다!
CLOC line chart 전체 div에서 height을 지정해주셔야할 것 같습니다 ... !

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/41473964/189145394-1b721695-1285-49cf-b820-31d58dddf4dd.gif)

**Comment by pshdev1030** [comment]
아직 다 작업하지 않아서 내일 정혜님이랑 민정님이랑 작업하면 될 것 같습니다..!

**Comment by jejecrunch** [comment]
그러면 우선 닫아두겠습니다!
