### ISSUE TITLE
[engine] stem.spec.ts 수정

### ISSUE THREAD

**Issue by ansrlm** [githru/githru-vscode-ext#116]
### Contents
- parser의 작업이 upstream/main에 머지가 된 것에 따라서 sequence관련 항목을 update할 필요성이 생겼습니다.

### Coverage
- 시퀀스에 맞게 (가장 최근의 commit이 0) 0으로 고정되어 있는 값을 수정
- 현재 반대 순번으로 표현하고 있는 FakeCommitData를 역순으로 다시 작성

### FYI
- https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/stem.spec.ts#L11
- https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/stem.spec.ts#L130

**Comment by ooooorobo** [comment]
제가 수정하겠습니다~!

사실 주석의 숫자는 시퀀스를 고려하지 않고 있을 때 #91 PR 설명에 같이 첨부된 노드 번호를 나타내려는 의도였는데,
sequence 번호로 사용하도록 (+역순으로) 수정하면 좋을 것 같네요 😄
