### ISSUE TITLE
[Warning] The task 'npm: watch' cannot be tracked. Make sure to have a problem matcher defined

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#138]
debugging을 위해 f5를 누르면 아래와 같은 에러가 발생합니다.
<img src="https://user-images.githubusercontent.com/81841082/189527669-00dde5f6-2bf8-440b-bdc7-97f16d2a0433.png" width="40%"/>

debug anyway 하면 되지만, 많이 거슬립니다.

원인은 문구에 적혀있는 것 처럼 problem matcher가 없다는 의미인데, tasks.json에 다음 두 problem matcher가 warning을 띄고있기 때문입니다.
![image](https://user-images.githubusercontent.com/81841082/189527662-344dfe91-30ac-4fc6-93c6-5424d706d18b.png)

각자가 아래 extension을 설치하는 것 말고는 마땅한 해결법을 찾지 못했습니다.
https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher

**Comment by ytaek** [comment]
제가 알기로는 해당 문제는 extension을 설치하는걸로 해결하는게 맞는 것 같습니다.

packages/vscode/.vscode/extensions.json 을 보시면
 
```
{
    // See http://go.microsoft.com/fwlink/?LinkId=827846
    // for the documentation about the extensions.json format
    "recommendations": ["dbaeumer.vscode-eslint", "amodio.tsl-problem-matcher"]
}
```

이렇게 되어 있는데,
workspace open시에 적혀있는 두 플러그인이 설치되어 있지 않다면, 설치를 추천합니다~. 하고 나옵니다.

https://stackoverflow.com/questions/50615102/vs-code-extension-recommendations-for-projects

eslint 및 problem matcher plugin 둘 다 저희 개발에 필수적인 플러그인이라, recommendation으로 강제(?)하는 것도 나쁘지 않을 것 같습니다.
