### ISSUE TITLE
[engine] 기준이 되는 branch name을 받아 main stem을 생성

### ISSUE THREAD

**Issue by ooooorobo** [githru/githru-vscode-ext#144]
### as-is
- 커밋의 브랜치 중 이름이 main/master인 것이 있다면, 그 커밋이 만드는 stem은 main stem이 됩니다.

### to-be
- stem 생성 시, 기준 branch의 이름을 받아 그 브랜치가 만드는 stem을 main stem으로 생성합니다.

---

githru prototype도 url 뒤에 파라미터로 기준이 되는 branch 이름을 받게 되어 있습니다.

```
            <Switch>
                <Route exact path="/" component = { Home }/>
                <Route path = "/v2/:repo/:releasePrefix/:mainStemBranchName" component = { v2 }/>
                <Route path = "/v2/:repo/:releasePrefix" component = { v2 }/>
                <Route path = "/v2/:repo/" component = { v2 }/>
            </Switch>
```
(지금보니 기준이 되는 branch 이름과, release prefix (v0.1.0이면 v)를 받아야 하는군요. 추후 반영이 필요하겠습니다 😄   )

나중에는 아래와 비스무리한 형태로 branch name을 user가 바꿔줄 수 있는 형태로 만들면 좋겠네요.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/24404665/189563170-473796e0-1b91-4e9d-942c-baa8a0e56d26.png">

_Originally posted by @ytaek in https://github.com/githru/githru-vscode-ext/issues/140#issuecomment-1243142499_

**Comment by ytaek** [comment]
이거 0.2에 갑시다... ㅎㅎ
vscode연동 부분이 조금 귀찮을 수 있는데, 한번 해보아요.
