### ISSUE TITLE
[FIX REQUEST] Temporal Filter 

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#145]
아래 항목들에 대해서 살펴봐주시고, 담당하시는 분들께서는 comment로 진행사항을 알려주세요~.

각 항목에 대해서 PR 올려주셔서 바로 반영해주시면 되고,
혹시 14일 전에 빠르게 수정이 불가능한 경우라면, 항목별로 '추후 수정 예정'이라고 댓글로 달아주세요.

- [ ] 브러싱은 안되더라도, 날짜로 Filter를 하면 Line chart도 같이 바뀌어야 하는데 안 바뀝니다.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/24404665/189579273-7c564c38-66dc-4d1d-b6c6-f17235765fd7.png">

- [ ] Bar chart -> Line Chart로 변경 (#107 아래쪽에 제 리뷰 사항들 다시 봐주세요)
- [ ] Temporal Filter높이를 아래 위 전부 합쳐서 margin 빼고 100~120px 정도로 만들어주세요. (지금 margin을 합치면 280px 이 넘습니다). 아래 그림이 margin 빼고 100~120px 이 되도록 입니다.
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/24404665/189578509-d95dcd93-cfe8-4920-bbca-248ef1c72309.png">

- [x] Chart 제목 붙여주세요. (#129)
<img width="423" alt="image" src="https://user-images.githubusercontent.com/24404665/189578879-2f53133b-c8ce-4768-a0d7-53bb1264b592.png">

- [ ] #165
- [x] y축 값들은 겹쳐지는 부분도 있고 색이 명확하게 안보이는데, 그냥 빼주셔도 될 것 같습니다.
<img width="150" alt="image" src="https://user-images.githubusercontent.com/24404665/189579027-798b94f7-a6cb-454e-abeb-9b38e153cf2f.png">

- [x] 혹시 오른쪽에 checkbox는 어떤 내용일까요? spec에 없는 부분은 빼주시면 감사하겠습니다.
<img width="534" alt="image" src="https://user-images.githubusercontent.com/24404665/189579360-95e65e31-3fb3-4cb1-b4fd-e989847221dc.png">

**Comment by jejecrunch** [comment]
> 혹시 오른쪽에 checkbox는 어떤 내용일까요? spec에 없는 부분은 빼주시면 감사하겠습니다.
> y축 값들은 겹쳐지는 부분도 있고 색이 명확하게 안보이는데, 그냥 빼주셔도 될 것 같습니다.
> Chart 제목 붙여주세요. (https://github.com/githru/githru-vscode-ext/pull/129)
이 부분 아직 작업 안들어가신 것 같아서 작업 들어가겠습니다.

**Comment by ytaek** [comment]
아하! 오른쪽 상단 체크박스가 Theme Selector 군요!! 이제 알았습니다 ^^;
요건 다음에 전반적으로 기능이 동작할 때, 이쁜 버튼 만들어서 채워넣으면 좋겠습니다.

**Comment by jeonghye-choi** [comment]
> 브러싱은 안되더라도, 날짜로 Filter를 하면 Line chart도 같이 바뀌어야 하는데 안 바뀝니다.

@ytaek 영택님! 이 부분, Line chart 안바뀌는 거 아닌가요??
brushing 기능 대신, Filtering 하는 날짜에 따라 배경색을 주는 형식으로 개선하기로 했었습니다! (cc. @kmin-jeong)

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/54584063/189923439-d6fb7238-f67e-4295-91f4-6474e58e2cbe.png">

**Comment by kmin-jeong** [comment]
@jeonghye-choi  그거 제가 구현이 가능할지 모르겠어서 아직 답변을 안드린걸로 알고 있어요!

**Comment by jeonghye-choi** [comment]
> @ytaek : 브러싱은 안되더라도, 날짜로 Filter를 하면 Line chart도 같이 바뀌어야 하는데 안 바뀝니다.

제가 D3부분을 잘 몰라서, 배경색상으로 filtering 부분 적용이 이번 릴리즈에는 힘들 것 같습니다ㅠㅠ
또한 브러시 기능이 내일까지는 아무래도 무리일 거 같아요ㅠㅠ 
해당 부분에 대한 이슈는 v0.2.0에 브러시 기능으로 추가 및 대응하겠습니다 #164

**Comment by jeonghye-choi** [comment]
> Bar chart -> Line Chart로 변경(trend를 알고 싶다는 목적이기에)
바꾸는데 시간이 걸리면 다음에 update해주세요.

'추후 수정 예정'

**Comment by jeonghye-choi** [comment]
> Temporal Filter높이를 아래 위 전부 합쳐서 margin 빼고 100120px 정도로 만들어주세요. (지금 margin을 합치면 280px 이 넘습니다). 아래 그림이 margin 빼고 100120px 이 되도록 입니다.

@ytaek 이 부분 혹시 설명 더 부탁드려도 될까요?? Filter(배경색 검은색 부분) hight를 전체 120px이 되었으면 좋겠다는 의미가 맞을까요??

**Comment by jeonghye-choi** [comment]
>  tick (x축 날짜 표시)이 좀 듬성듬성한데, 조금 더 뿌려도 괜찮겠습니다.

@kmin-jeong 민정님 혹시 이 부분 내일(14일까지) 대응 가능하실까요?? 어려우시면 '추후 수정 예정' 코멘트 부탁드립니다!

**Comment by kmin-jeong** [comment]
@jeonghye-choi  x축 날짜가 저희 json보면 시간이나 분도 함께 나와있잖아요! 그래서 지금 당장은 무리지만 v0.2.0 때 이거 범위도 함께 논의해보면 좋을거 같다고 생각해요!

**Comment by kmin-jeong** [comment]
> > tick (x축 날짜 표시)이 좀 듬성듬성한데, 조금 더 뿌려도 괜찮겠습니다.

추후수정예정

**Comment by ytaek** [comment]
> theme selector 만든 이유가 테스트용이였어요! 배경이 dark일 때, light일 때 적용 확인하기 위해서요! 제 개인적인 의견으로는 theme selector가 githru에 필요한 기능이라고 생각하지는 않아요!

넵. 일단 심미적인 관점에서 생각해볼 수 있는 기능이고, 요새 개발툴들도 많이들 지원하고 있는거라 한번 쯤 논의해보는 것도 좋겠습니다.
하지만, 단순히 배경색깔만 바꾸면 되는게 아니라, 많은 부분은 건드려야될 수도 있어서 가성비(?)가 나오는 작업인지는 심각하게 고민이 필요하다고 개인적으로 생각합니다. 😺

**Comment by ytaek** [comment]
> @jeonghye-choi x축 날짜가 저희 json보면 시간이나 분도 함께 나와있잖아요! 그래서 지금 당장은 무리지만 v0.2.0 때 이거 범위도 함께 논의해보면 좋을거 같다고 생각해요!

요거는 데이터가 '일' 단위로 binning한 것이기에 시간이나 분은 보여지지 않아도 될 것 같습니다~.

**Comment by ytaek** [comment]
> 

tick 의 개수를 늘리면 좋겠다는 의견이었습니다 :- )
나중에는 width의 변경에 따라서 tick 개수도 조절할 수 있다면 best이긴 하겠네요~.

**Comment by ytaek** [comment]
> > Temporal Filter높이를 아래 위 전부 합쳐서 margin 빼고 100120px 정도로 만들어주세요. (지금 margin을 합치면 280px 이 넘습니다). 아래 그림이 margin 빼고 100120px 이 되도록 입니다.
> 
> @ytaek 이 부분 혹시 설명 더 부탁드려도 될까요?? Filter(배경색 검은색 부분) hight를 전체 120px이 되었으면 좋겠다는 의미가 맞을까요??

<img width="57" alt="image" src="https://user-images.githubusercontent.com/24404665/189961810-29b6973a-43bf-46c1-85cb-24f87f6bd3f0.png">

요거의 높이가 120px이요!! 팍팍 줄여주세용!! 😃

**Comment by ytaek** [comment]
답변 정리해주셔서 감사합니다~. 
할 수 있는 것 까지만 해주시고, 그 보다는 결과보고서에 더 집중해주시는 것도 좋습니다 : )

'추후 수정'이라고 적힌 부분은 잘 갈무리해서 다음 릴리즈 feature로 등록해주셔도 좋습니다~.
