### ISSUE TITLE
[FIX REQUEST] Graph + Detail

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#146]
아래 항목들에 대해서 살펴봐주시고, 담당하시는 분들께서는 comment로 진행사항을 알려주세요~.

각 항목에 대해서 PR 올려주셔서 바로 반영해주시면 되고,
혹시 9/14일 전에 빠르게 수정이 불가능한 경우라면, 항목별로 '추후 수정 예정'이라고 댓글로 달아주세요~.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/24404665/189579643-5e8015ab-0ae0-4676-921d-a70427d1dca4.png">

- [x] #148

- [x] #149

- [x] Node(Cluster)별 높이를 조금 더 줄여서 많은 정보가 보이게 하면 좋겠습니다. 지금은 여백이 좀 많아서 한 페이지에 10개 미만으로 보이네요. IDE에서는 아랫쪽에 problem matcher나 terminal 등이 떠서 실제 보이는 정보들을 훨씬 줄어듭니다.
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/24404665/189579936-4261c56a-7deb-4db2-9326-d7cb379e9af9.png">

- [x] 윗 node와 아래 node가 서로 연결된 느낌이 없어서, node와 node사이에 link (수직선?)을 넣어주던지, 혹은 아예 테이블 형태처럼 붙여주세요. 서로 이어져서 ordering되었다는 인식이 되어야 합니다.
- [x] node 색깔도 조금 명확하게 바꾸는게 좋겠습니다. 어두운 바탕이라 그런지 잘 안보이네요.
- [x] node의 width도 지금 100이 넘는데, 50~70 정도로 줄이면 좋겠습니다. (높이가 줄어들테니 뚱뚱하게 보이지는 않을 듯)
- [x] GitHub에서 가져온 부분이긴 하지만, 불필요하게 서술(문장)형으로 적혀있는 것 같습니다. 필요한 부분만 골라내서 컴팩트하게 바꾸면 좋겠네요. 한 줄 정도로. (추후에는 glyph나 작은 chart 정도로 표현해도 괜찮겠습니다)
<img width="698" alt="image" src="https://user-images.githubusercontent.com/24404665/189580580-166e58b7-a829-42ed-a7cf-97a476a723e7.png">

- [x] user avatar에 hover를 했을 때 나오는 설명이 avatar동그라미와 좀 떨어져있습니다. 가까이 붙여주시면 감사하겠습니다. (tooltip의 크기, margin을 좀 줄여도 괜찮겠습니다)
<img width="191" alt="image" src="https://user-images.githubusercontent.com/24404665/189580878-117ff350-2852-4202-b115-5eb4a1d97a73.png">

- [x] node를 클릭했을 때, 고정 height 로 나오는 것 같은데, 아래와 같은 경우 graph 아래쪽이 잘린 것 같은 느낌을 주네요. 변동폭으로 하면 좋겠습니다. 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/24404665/189581105-3308741a-c5f4-4ece-9e2d-3a67055c7e3b.png">

- [x] node가 collapse되었는지 아닌지에 대한 표시가 필요합니다. 바로 윗 그림에서 그런게 없으니 더 이상했었던 것 같네요.
- [x] detail에는 commit별로 commit ID, 날짜와 author 정보도 같이 있는게 좋겠습니다.

**Comment by vgihan** [comment]
> Node(Cluster)별 높이를 조금 더 줄여서 많은 정보가 보이게 하면 좋겠습니다. 지금은 여백이 좀 많아서 한 페이지에 10개 미만으로 보이네요. IDE에서는 아랫쪽에 problem matcher나 terminal 등이 떠서 실제 보이는 정보들을 훨씬 줄어듭니다.

- [ ] ClusterGraph
- [ ] Summary

**Comment by wherehows** [comment]
- detail에는 commit별로 commit ID, 날짜와 author 정보도 같이 있는게 좋겠습니다.
- node가 collapse되었는지 아닌지에 대한 표시가 필요합니다. 바로 윗 그림에서 그런게 없으니 더 이상했었던 것 같네요.
- node를 클릭했을 때, 고정 height 로 나오는 것 같은데, 아래와 같은 경우 graph 아래쪽이 잘린 것 같은 느낌을 주네요. 변동폭으로 하면 좋겠습니다.

작업 진행하겠습니다.

**Comment by jejecrunch** [comment]
> user avatar에 hover를 했을 때 나오는 설명이 avatar동그라미와 좀 떨어져있습니다. 가까이 붙여주시면 감사하겠습니다. (tooltip의 크기, margin을 좀 줄여도 괜찮겠습니다)

이 부분은 tooltip의 배경색이 어두운 색이라 안보이는 것 같고 색으로 진행하더라도 너무 크게 padding, margin 값이 들어가있어서 해당 부분 수정하겠습니다.

> commit message의 앞 keyword만 딴 것은 좋긴 했는데, 처음 list가 보일 때 화면을 채워주는 contents 가 좀 없어보이네요 ㅜ.ㅜ 일단 마지막 commit message으로 채워놓는것이 좋을 것 같아요. (혹은 feat(webview): add typescript structure + 2 more 정도로 표시하던지)

이 부분도 수정하겠습니다.



> > Node(Cluster)별 높이를 조금 더 줄여서 많은 정보가 보이게 하면 좋겠습니다. 지금은 여백이 좀 많아서 한 페이지에 10개 미만으로 보이네요. IDE에서는 아랫쪽에 problem matcher나 terminal 등이 떠서 실제 보이는 정보들을 훨씬 줄어듭니다.
> 
> * [x]  ClusterGraph [fix(view): update cluster graph size (width, height, gap) #150](https://github.com/githru/githru-vscode-ext/pull/150)
> * [ ]  Summary

이 부분도 수정했는데 합치고 나서 한번 다시 봐야할 것 같습니다.

**Comment by vgihan** [comment]
> Node(Cluster)별 높이를 조금 더 줄여서 많은 정보가 보이게 하면 좋겠습니다. 지금은 여백이 좀 많아서 한 페이지에 10개 미만으로 보이네요. IDE에서는 아랫쪽에 problem matcher나 terminal 등이 떠서 실제 보이는 정보들을 훨씬 줄어듭니다.

작업 시작하겠습니다 !

**Comment by vgihan** [comment]
> 윗 node와 아래 node가 서로 연결된 느낌이 없어서, node와 node사이에 link (수직선?)을 넣어주던지, 혹은 아예 테이블 형태처럼 붙여주세요. 서로 이어져서 ordering되었다는 인식이 되어야 합니다.

작업 시작하겠습니다 !

**Comment by ytaek** [comment]
모두들 디테일하게 진척사항 알려주셔서 감사합니다!  👍 👍 👍 👍 👍 👍

**Comment by jejecrunch** [comment]
앗 그리고 디테일 작업해주시는 분 혹시 color도 배경색 맞춰서 밝은 색으로 해주시면 감사할 것 같습니다 !

**Comment by vgihan** [comment]
현재 VerticalClusterList에서 `data.reverse()` 함수가 동작하지 않는 문제가 있어, Data Ordering 문제는 결과보고서 작성 이후에 작업하도록 하겠습니다..!
