### ISSUE TITLE
[FIX REQUEST] Statistics

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#147]
아래 항목들에 대해서 살펴봐주시고, 담당하시는 분들께서는 comment로 진행사항을 알려주세요~.

각 항목에 대해서 PR 올려주셔서 바로 반영해주시면 되고,
혹시 9/14일 전에 빠르게 수정이 불가능한 경우라면, 항목별로 '추후 수정 예정'이라고 댓글로 달아주세요~.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/24404665/189582196-91a0f816-b8ba-4cd6-9ea6-cb6266bf919c.png">

- [x] 1. 윗쪽 select box에서 `commit`을 `commit #`로 바꿔주세요.
- [x] 2. select box의 테두리만 굵은데 나머지와 통일성 있게 바꿔주시고, 
- [x] 3. select box 위치를 오른쪽 위로 바꿔주세요.
- [x] 4. select box와 chart, 아래 축 정보의 margin을 줄여주세요.
- [x] 5. y축의 tick은 없어도 되겠습니다.
<img width="50" alt="image" src="https://user-images.githubusercontent.com/24404665/189582850-7be6b702-5938-4f44-b6fb-c32336154ecd.png">

- [ ] 6. y축 값이 지금은 commit # / Total commit# 의 백분율인데, 이럴 경우 현재처럼 차트의 반 이상이 비어 있게 됩니다 (dominant한 contributor가 있지 않는 이상). 100%를 max로 잡지말고 최대값+a를 max로 잡거나, 혹은 그냥 cardinality (commit#)만 가지고 표시하면 더 보기 좋을 것 같습니다.  (추후에 값의 분포에 따라서 top 10 user만 보여준다던지, Percentage가 서로 비슷할 경우, 다를 경우를 분리해서 보여주는 값을 다르게 한다던지 하는 방법도 있겠네요)

- [ ] 7. bar chart를 나중에 avatar 정보를 긁어오게 된다면, 아래 GitHub처럼 horizontal로 해도 괜찮겠네요 ㅎㅎ (지금은 item의 이름이 길어 horizontal로 하긴 했습니다.)
<img width="641" alt="image" src="https://user-images.githubusercontent.com/24404665/189582495-61e372fd-a48e-440a-bb48-d79ad5f98133.png">

**Comment by hanseul-lee** [comment]
1~5 작업 예정입니다

**Comment by jejecrunch** [comment]
실행해보니 Icicle 차트가 보이지 않는 것 같은데 이 부분은 어떻게 되는지 알 수 있을까요?!
view 폴더에서 npm start로 실행하면 잘 보이는데 vscode에서 실행시키면 안보여서요 ... !

**Comment by hanseul-lee** [comment]
> 실행해보니 Icicle 차트가 보이지 않는 것 같은데 이 부분은 어떻게 되는지 알 수 있을까요?! view 폴더에서 npm start로 실행하면 잘 보이는데 vscode에서 실행시키면 안보여서요 ... !

이 부분 Icicle에서만 mockup data 사용하고 있어서 그런 것일까요? 
현재 @taejs 님께서 실제 데이터 연동되도록 작업 중이신 것으로 하는데 확인해봐 주시면 좋을 것 같습니다

**Comment by taejs** [comment]
https://github.com/githru/githru-vscode-ext/pull/156
넵 맞습니다. 연동 완료했습니다~

**Comment by ytaek** [comment]
6,7번은 가능하다면 v0.2에 되면 좋겠습니다~~. 검토 부탁드려요!
