### ISSUE TITLE
[Question] Cluster Data Ordering

### ISSUE THREAD

**Issue by vgihan** [githru/githru-vscode-ext#148]
Ordering 관련해서 질문드립니다 !

현재 VerticalClusterList 팀에서는 따로 reverse 하지 않고 fake asset을 그대로 사용 중인데, engine 팀에서 내려 받는 데이터의 경우 최신 순으로 정렬되어 내려져 오는 지 궁금합니다 !

이미 언급된 내용이라면 죄송합니다

**Comment by anpaul0615** [comment]
> "engine 팀에서 내려 받는 데이터의 경우 최신 순으로 정렬되어 내려져 오는 지 궁금합니다"
이부분이 정확히 어떤부분을 말하는건지는 잘 모르겠는데요.

만약 squash 되어 묶여있는 커밋들(csm-source) 에 대한 정렬을 물어보는거라면,
https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/csm.ts#L92 에서처럼 sequence 오름차순 정렬이 적용되어있구요.

squash 하는 기준 커밋(csm-base) 에 대한 정렬에 대해 물어보는거라면,
각 CSMNode(=mapper 가 ClusterNode 만들때 사용하는 대상) 를 만들때, 루트노드(=가장오래된커밋)부터 순회를 진행하기때문에,
자연스럽게 ClusterNode[0] 이 가장 오래된커밋이고, ClusterNode[last] 가 가장 최근 커밋이 되게됩니다.

**Comment by ansrlm** [comment]
현재 데이터 관리 측면에서는 Filter는 최고 -> 최신의 형태를 가지고 있기 때문에 어떤 데이터 정렬에 대해서 특정 하더라도(asd || dsc) 모두를 만족시킬 수 없는 상황입니다.

다른 컴포넌트들을 보니 Date를 통해서 렌더링을 진행하고 있기 때문에 해당 처리와 비슷하게
`Array.map(item => return React.Element(item))` 가 바로 진행되는 것이 아닌 
`Array.sort(a, b => a.commitDate - b.commitDate).map(item => return React.Element(item))`
와 같이 처리하는 방식을 (reverse를 사용해도 상관 없습니다) 제안드리고 싶습니다.

**Comment by ansrlm** [comment]
상기 이슈는 어느정도 해소된 것으로 보아, close 처리합니다.
