### ISSUE TITLE
[Discussion] Apply getboundingclientrect chart component

### ISSUE THREAD

**Issue by pshdev1030** [githru/githru-vscode-ext#167]
차트 컴포넌트의 width와 height를 상위 div(wrapper)의 width와 height를 가져와서 설정하되, css로 상위 div를 조작하여 사용하는 것이 좋을 것 같습니다.

차후 수정시 css만 수정하여 차트를 바꿀 수 있습니다.

**Comment by jin-Pro** [comment]
좋아요~~ 그러면 추후 다른 인원이 리팩토링하기에도 용이할것 같네요!

**Comment by ytaek** [comment]
이런 부분 좋습니다!!!
