### ISSUE TITLE
[discussion]how far should go on the x-axis?

### ISSUE THREAD

**Issue by kmin-jeong** [githru/githru-vscode-ext#170]
json데이터에 보면 date에 년도,월,일,시간까지 나와있는데, x축이 어디까지 나와야할지, 확대와 축소는 어떻게 해야할지 의논해보면 좋을거 같습니다

**Comment by ytaek** [comment]
x축은 일 단위로 binning됩니다~.
binning한다음에 line chart로 바꿔주시면 되요.

해결되었다면 close 부탁드립니다~.

**Comment by kmin-jeong** [comment]
네! 확인했습니다!
