### ISSUE TITLE
[view] fix commit message slice logic

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#174]
현재 commit message를 /n을 만나면 문자열을 그곳까지 자르게 로직이 구현되어있습니다.
그런데 commit message에서 공백문자가 아닌 /n을 만났다면? 이라는 경우가 떠오르더라고요.
예를 들자면

```bash
Merge pull request #159 from vgihan/nain/n/nfix(view): modify ...
```

이런 메시지를 가지고 있다면? 이라는 경우입니다.

이 경우라면 현재의 로직으로는 `Merge pull request #159 from vgihan`까지만 보이게 되는 이슈가 발생합니다.

저도 조금 더 고민해보겠습니다.

**Comment by jin-Pro** [comment]
혹시 커밋 메세지를 자르는 이유를 알 수 있을까요??
줄바꿈을 위해서라면 pre 태그 사용은 어떠할까요?

**Comment by jejecrunch** [comment]
> 혹시 커밋 메세지를 자르는 이유를 알 수 있을까요?? 줄바꿈을 위해서라면 pre 태그 사용은 어떠할까요?

squash된 커밋에서는 title + content 이렇게 들어가서 [title]/n/n[content] 이렇게 나오더라고요 ... !

**Comment by jin-Pro** [comment]
> > 혹시 커밋 메세지를 자르는 이유를 알 수 있을까요?? 줄바꿈을 위해서라면 pre 태그 사용은 어떠할까요?
> 
> squash된 커밋에서는 title + content 이렇게 들어가서 [title]/n/n[content] 이렇게 나오더라고요 ... !

감사합니다 ㅎㅎ

**Comment by ytaek** [comment]
음. 좀 헷갈리는데, 이게 \n 인가요 /n인가요?  문맥상 \n 인것 같은데...

> squash된 커밋에서는 title + content 이렇게 들어가서 [title]/n/n[content] 이렇게 나오더라고요 ... !

보통 commit title이 나오고 \n\n[content] 가 맞을 겁니다.
이게 우리가 쓰는 email 포맷도 까보면 저렇게 생겼을꺼에요 😄 

\r\n도 있으니 잘 구분하면 좋겠습니다.

이것도 간단하니 0.2 로 가겠습니다.

**Comment by jejecrunch** [comment]
> 음. 좀 헷갈리는데, 이게 \n 인가요 /n인가요? 문맥상 \n 인것 같은데...
> 
> > squash된 커밋에서는 title + content 이렇게 들어가서 [title]/n/n[content] 이렇게 나오더라고요 ... !
> 
> 보통 commit title이 나오고 \n\n[content] 가 맞을 겁니다. 이게 우리가 쓰는 email 포맷도 까보면 저렇게 생겼을꺼에요 😄
> 
> \r\n도 있으니 잘 구분하면 좋겠습니다.
> 
> 이것도 간단하니 0.2 로 가겠습니다.

저도 그런 줄 알고 처음에는 \n로 했었는데 안되길래 자세히보니 /n 이렇게 들어가있더라고요 ... !

**Comment by ytaek** [comment]
음? 이건 그럼 데이터 넘어오는 쪽 이슈일 수도 있겠는데,

@jejecrunch 님, 혹시 재현 경로나, 실제 나온 데이터를 여기 뿌려주실 수 있으신가요?
넘어오는 데이터 이슈라면 @githru/engine 팀 쪽에서 보는게 맞을 것 같습니다.

**Comment by jejecrunch** [comment]
아래 이미지가 가공하는 부분입니다!

<img width="417" alt="스크린샷 2022-09-22 오후 8 58 41" src="https://user-images.githubusercontent.com/41473964/191740724-7abdf9c4-56e4-48ba-a3c2-ae5f80a63dab.png">

지우고 실행했을 때 (npm run build:all -> vscode 실행으로 확인한 결과) 이미지는 아래입니다.
<img width="722" alt="image" src="https://user-images.githubusercontent.com/41473964/191740123-9822cea1-d425-44db-a8fd-b8534e66e82f.png">

되살리고 실행했을 때 이미지는 아래입니다.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/41473964/191740862-43b6c8b6-1993-40ab-9185-bede035d1100.png">

제 생각에는 squash할 때 문제인 것 같습니다. -> 내용으로 기존의 커밋들이 모아서 들어가면서 엔터 문자가 2번 들어가는데 이때 문자를 \n이 아닌 /n으로 넣는 것 같습니다.

**Comment by ytaek** [comment]
https://github.com/githru/githru-vscode-ext/blob/55250b68e59640ca138cb5021c13577834decf5f/packages/analysis-engine/src/parser.ts#L82

```
      if (str.startsWith("CommitDate")) {
        let indexCheckFileChanged = idx + 2;
        let eachCommitMessage = "";
        while (splitByNewLine[indexCheckFileChanged] !== "") {
          if (eachCommitMessage !== "") {
            eachCommitMessage += "/n";
          }
          eachCommitMessage += splitByNewLine[indexCheckFileChanged].trim();
          indexCheckFileChanged += 1;
        }
```

parser 쪽의 이슈였네요.
@jejecrunch 님, 요거 하나 이슈로 등록해주시면 감사하겠습니다.
v0.2 milestone 달고, analysis-engine으로 label 붙여주셔요.

@githru/engine 팀, 해당 이슈 patch 부탁드리겠습니다.

**Comment by jejecrunch** [comment]
생성했습니다 :)
엔진팀에서 해결되면 저도 해결하고 해당 이슈는 클로즈하겠습니다 !

**Comment by jejecrunch** [comment]
해결 완료하여 클로즈합니다.
