### ISSUE TITLE
[view] change summary content into keyword + file name

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#177]
## Current status

현재는 summary content에 마지막 commit node의 message와 cluster의 commit 갯수가 보여집니다.

## Suggestion

이전에 keyword로 빼서 관리했던 부분이 콘텐츠가 부족해보인다는 의견이었습니다.
그전에 가장 많은 변화가 일어난 파일명을 넣자는 의견이 있었는데 시간이 부족해서 구현하지 못했습니다.
그래서 0.2에서 이 부분을 추가적으로 구현해보는 건 어떨까요?

만약 이렇게 되면 가장 count가 높은 상위 3위까지의 keyword와 가장 많은 변화가 일어난 파일명 이렇게 들어갈 것 같고,
가장 많은 변화가 일어났다는 기준은 insertions, deletions을 합쳐서 그 합친 수로 판단할 예정입니다.

또 툴팁으로 current status에 있는 내용을 가져갈 수도 있을 것 같습니다.

**Comment by jin-Pro** [comment]
오~~~ 좋아요 조금 더 직관적으로 나타낼 수 있겠네요!

**Comment by ytaek** [comment]
UI Renewal 계획에 따라 close합니다.
