### ISSUE TITLE
[view] add author profile image

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#178]
## Current status

현재 author를 구분해주는 것은 background-color입니다.

## Suggestion

author profile image를 가져와서 author를 구분할 수 있는 것은 어떨까요?
만약에 이 부분이 engine팀에서도 구현이 된다면 바로 집어넣어볼 수 있을 것 같습니다.
그 전까지는 https://github.com/githru/githru-vscode-ext/issues/102 이 부분 좀 더 고려해보겠습니다.

**Comment by jin-Pro** [comment]
오 훨씬 직관적일것같아요 ~~

**Comment by ytaek** [comment]
avatar 들어가는 부분 꼭 있으면 좋겠습니다.
@githru/engine 팀 이 부분 이슈로 잡으면 좋겠습니다.

**Comment by jejecrunch** [comment]
방법을 찾은 것 같습니다 ! https://github.com/{user_name}.png로 하면 아바타 이미지를 가져올 수 있군요 ...
여기는 함정이 있긴 합니다 ㅜㅜ
userName이 정확하게 들어가고 있는가?
-> 저의 경우 제제jeje라는 이름으로 commit을 했습니다. 이의 경우 jejecrunch라는 이름을 읽어올 수 없습니다.
(물론 이는 다른 git 저장소를 이용하다가 github에 올렸을 때도 발생하는 이슈이긴 합니다만 ...)
-> 그렇다면 이메일로 할 수 있는 방법은? MD5 해시로 암호화한다면 가능합니다. 이는 crypto 라이브러리가 필요해보입니다. 라이브러리를 추가한다면 그럴 수밖에 없는지 조금 더 고민해봐야할 것 같습니다.

**Comment by jejecrunch** [comment]
MD5 암호화의 경우 보안의 문제로 Web API에서는 지원하지 않고 있네요.
대안으로 util함수로 만들거나 라이브러리를 추가해야할 것 같은데 어떻게 생각하시나요?

cf. https://copyandpaste.tistory.com/74
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#supported_algorithms

**Comment by ytaek** [comment]
지난주 engine팀과 얘기해봤는데,
avatar 가져오는 부분은 일단 author name으로 하고, 안 나올 떄는 지금 만들어놓으신 Initial 이 나오는 image로 대체하면 될 것 같습니다.
이미지 tag에 onError를 등록하거나 하면 된다는데..

@ansrlm 님 도와주세요!!

**Comment by ansrlm** [comment]
@jejecrunch 님
default image를 업로드하기 어렵다면 다음과 같은 방식도 있으니 고려해봐도 좋을 것 같아요.

https://en.gravatar.com/site/implement/images/ 를 통해서 default image를 생성하면 되는데 말씀주신 md5와 같은 hash algorithm을 사용하면 됩니다.

그래서 다음과 같이 조합해서 사용이 가능할 것 같네요.
1. md5은 https://www.npmjs.com/package/md5 를 활용
2. author name을 md5생성의 인지로 사용 (`md5(author)`)

**Comment by jejecrunch** [comment]
자세한 답변 감사합니다.
라이브러리 설치하는 걸 최소화하고 싶어서 라이브러리 없이 md5로 암호화할 수는 없을까 고민했었거든요
우선 한번 해보고 PR 날려보겠습니다 !!

**Comment by jejecrunch** [comment]
지금까지 해본 내용 적어두겠습니다 !!

1. email을 md5 해시로 인코딩해서 요청해 받는 방법 -> md5 인코딩 결과가 먹히는 url이 없는 것 같습니다.
(이 방법은 [ts-md5]()라이브러리를 통해 시도해보았습니다.)
아래 두 주소를 참고해서 시도해보았습니다.
```
<img src="https://avatars.githubusercontent.com/u/${MD5_ENCODING_EMAIL}" />
<img src="http://www.gravatar.com/avatar/${MD5_ENCODING_EMAIL}">
```

2. Github API 이용하는 방법 -> 위와 같은 문제 발생 + 하루에 요청할 수 있는 횟수 제한이 있음 + 제한 풀려면 유료 ...
3. 만약 Git email로 Github user id를 무료로 가져올 수 있다면 충분히 잘 해결될 수 있을 것 같은데 ...
```
<img src="https://avatars.githubusercontent.com/u/${GITHUB_USER_ID}?s=400&u=${MD5_ENCODING_EMAIL}&v=4" />
```
여기서 github user id만 달라도 이미지 가져올 수 있었습니다. 조금 아쉽네요 ... 우선은 가져올 수 없는 경우는 제외하고 구현해보도록 하겠습니다 ㅜㅜ

**Comment by jejecrunch** [comment]
어프로브 받아서 추가하는 작업 완료되었기 때문에 닫겠습니다 !
