### ISSUE TITLE
[design] Change Githru Logo for v0.2.0

### ISSUE THREAD

**Issue by jeonghye-choi** [githru/githru-vscode-ext#179]
## Description

- 로고가 라인이 얇고 색상이 다크모드에서 대비가 크지 않아 눈에 잘 들어오지 않음.
- 변경이 필요해 보임

## Tasks

- [x] Githru Concept 설정하기
- [x] Logo 시안 등록 및 논의하기

**Comment by jejecrunch** [comment]
오! 안그래도 로고에 대해서 이야기 하고 싶었는데 이슈 감사합니다.

**Comment by wherehows** [comment]
와... 로고 직접 그리시는건가요?;

**Comment by jin-Pro** [comment]
와 ㅋㅋㅋ,,, 멋져요...

**Comment by ytaek** [comment]
@jeonghye-choi 님, 웬만한 Feature보다 이게 제일 중요할 것 같습니다 ㅜ.ㅜ 
개인적으로는 가능 큰 contribution인 것 같아요!! 🥲🥲🥲🥲🥲🥲🥲

v0.2에 꼭 되면 좋겠습니다!

**Comment by jeonghye-choi** [comment]
## Githru Logo

### Branding
- Githru가 'see through'의 의미를 지닌다고 들었지만,
- go through 의 의미를 넣어서 앞으로 나아가는 형태를 넣었습니다.
- 저희 프로젝트의 시각적 요소에 Line이 많이 들어가 있기 때문에 Line 형태로 구성했습니다

- 자세히 보면 귀여운 눈과 입이 있습니다😘

### 시안
![Artboard 1 copy 3](https://user-images.githubusercontent.com/54584063/193396592-6df2a5f8-f893-4755-aa47-ba1314a9d948.png)
![Artboard 1 copy 6](https://user-images.githubusercontent.com/54584063/193396595-55e50a35-c505-46ea-8ef5-9fb88831b770.png)


### VSCode 에서 아마 보여질 이미지

<img width="533" alt="image" src="https://user-images.githubusercontent.com/54584063/193396633-84662662-9183-4008-b1b3-1ed6dcdeb740.png">

**Comment by jeonghye-choi** [comment]
만들긴 했지만 괜찮은지 잘 모르겠네요ㅠㅠ
고민 정말 많이 했는데, 의견 있으시면 자유롭게 편하게 말해주세요!

**Comment by hanseul-lee** [comment]
와~ 너무 얼굴 너무 귀여워요ㅋㅋㅋㅋㅋ LGTM~~!!!

**Comment by jejecrunch** [comment]
너무 귀엽습니다 ㅎㅎㅎ LGTM 👍

**Comment by kmin-jeong** [comment]
LGTM!! 너무 귀여워요!!

**Comment by ytaek** [comment]
지난주 토요일 모임에서 핫했던 로고군요!! 
너무너무너무 좋습니다. 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 

(눈하고 입도 이쁜데, 썸네일로 작아질 때 그 부분이 안 보이는게 약간 아쉽긴 하네요~.)

아무튼 좋아요!!

**Comment by ytaek** [comment]
로고에 맞춰서 저희 메인 color도 좀 바꿔보는 건 어떨까요?

한번 정한게 백만년 갈껀 아니니까, ^^; 부담없이 이번에 칙칙한 파란색에서 바꿔보는 것도 좋을 것 같아요!
