### ISSUE TITLE
[engine] PARSER 로직

### ISSUE THREAD

**Issue by blcklamb** [githru/githru-vscode-ext#181]
## PARSER의 목적
STEM, CSM에서 쓰일 commit 정보를 json 형식에 담아 보내줍니다.

[packages/analysis-engine/src/types/CommitRaw.ts](https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/types/CommitRaw.ts)

CommitRaw 예시 출력은 다음과 같습니다.
```bash
{
    id: 'a38625748a80945959ca5ff82555a60e8ac51186',
    parents: [  '9aca1fffa56dc46946f75a6573ed182d7f4c3837'  ],
    branches: [  'main', 'origin/main', 'origin/HEAD'  ],
    tags: [],
    author: {  name:  'chaejung Kim',  email:  'whenucan35@gmail.com' },
    authorDate: 'Sun Sep 4 20:17:59 2022 +0900',
    committer: {  name:  'chaejung Kim',  email:  'whenucan35@gmail.com' },
    committerDate: 'Sun Sep 4 20:17:59 2022 +0900',
    message: 'feat(engine): sequenceNumber field add\n\n이후 DAG, STEM 작업을 위해 각 커밋의 순서를 나타내는 필드 추가'
    differenceStatistic:  {
        totalInsertionCount: 1,
        totalDeletionCount: 0,
        fileDictionary: {
            'packages/analysis-engine/src/types/CommitRaw.ts': {
                insertionCount: 1,
                deletionCount: 0,
            }
       }
}
```

## 위치한 레포지토리에서 git log 실행하기

- child_process를 활용하여 코드 실행 시 실행한 레포지토리의 console에서 바로 git log를 실행시킬 수 있도록 하였습니다.

    [child_process?](https://nodejs.org/api/child_process.html#:~:text=The%20node%3Achild_process%20module%20provides%20the%20ability%20to%20spawn%20subprocesses%20in%20a%20manner%20that%20is%20similar%2C%20but%20not%20identical%2C%20to%20popen(3).%20This%20capability%20is%20primarily%20provided%20by%20the%20child_process.spawn()%20function%3A)

git log option은 이전 githru 코드를 참고했습니다.
`git --no-pager log --all --parents --numstat --date-order --pretty=fuller --decorate -c`

### git log arguments 세부 사항
- `--no-pager`: pager로 git 결과를 뽑아내지 않고 바로 terminal에 출력합니다.
    - pager란 아래 이미지처럼 terminal에서 텍스트 파일을 볼 수 있도록 임시 창을 띄우는 프로그램입니다.
        <img width="656" alt="image" src="https://user-images.githubusercontent.com/92101831/190184609-196ef428-7194-4144-8977-33d4e4f1ed89.png">

- `--all`: 현재 위치한 branch의 HEAD를 포함한 모든 refs/들의 commit을 출력합니다.
    - 즉, 파생된 브랜치의 이력을 함께 볼 수 있습니다.
    
- `--parents`: commit의 부모 commit도 함께 출력합니다.
    - ex.`commit <자기 자신 commit hash 값> <부모 commit hash 값>`
    
- `--numstat`: 변화 이력을 가진 파일의 추가 및 제거 줄의 수를 나타냅니다, 둘 다 0의 경우 '-'로 출력합니다.
    - ex. `0       8       packages/analysis-engine/src/parseIndex.ts`
    
- `--date-order`: 자식 commit이 다 출력되기 전에 부모 commit이 나오지 않게 합니다. 그런 경우가 없다면 시간 순으로 출력합니다.

- `--pretty=fuller`: commit 출력 format의 일종입니다. fuller의 경우 아래와 같습니다.
    ```
    commit <hash>
    Author:     <author>
    AuthorDate: <author-date>
    Commit:     <committer>
    CommitDate: <committer-date>

    <title-line>

    <full-commit-message>
    ```
- `--decorate`: 🚨 유의할 점: git log 명령어는 terminal에서 출력되는 것과 그렇지 않은 것을 구분합니다. #90 해당 이슈를 해결하기 위해 추가했습니다.

- `-c`: merge commit의 경우 두 부모 commit를 동시에 비교해 한꺼번에 파일 변경 이력을 출력합니다.

[git log arguments에 관한 참고 링크](https://git-scm.com/docs/git-log)

예시 출력은 다음과 같습니다.

```bash
commit a38625748a80945959ca5ff82555a60e8ac51186 9aca1fffa56dc46946f75a6573ed182d7f4c3837 (HEAD -> main, origin/main, origin/HEAD)
Author:     chaejung Kim <whenucan35@gmail.com>
AuthorDate: Sun Sep 4 20:17:59 2022 +0900
Commit:     chaejung Kim <whenucan35@gmail.com>
CommitDate: Sun Sep 4 20:17:59 2022 +0900

    feat(engine): sequenceNumber field add
    
    이후 DAG, STEM 작업을 위해 각 커밋의 순서를 나타내는 필드 추가

1       0       packages/analysis-engine/src/types/CommitRaw.ts

commit 9aca1fffa56dc46946f75a6573ed182d7f4c3837 e333e8cbfe442336c35bd943af03f264d9d28a43
Author:     chaejung Kim <whenucan35@gmail.com>
AuthorDate: Sun Sep 4 20:14:36 2022 +0900
Commit:     chaejung Kim <whenucan35@gmail.com>
CommitDate: Sun Sep 4 20:14:36 2022 +0900

    chore(engine): delete parseIndex.ts
    
    index.ts에 통합하여 기존 별도로 구분된 parse 전용 index는 삭제

0       8       packages/analysis-engine/src/parseIndex.ts

commit e333e8cbfe442336c35bd943af03f264d9d28a43 5e79f2f8af6411021e20f7807b495117c04b1a0c
Author:     chaejung Kim <whenucan35@gmail.com>
AuthorDate: Sun Sep 4 20:11:00 2022 +0900
Commit:     chaejung Kim <whenucan35@gmail.com>
CommitDate: Sun Sep 4 20:11:00 2022 +0900

    refact(engine): erase useless lines

1       1       packages/analysis-engine/src/parseLog.ts

...
```

[function getGitLog](https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/parser.ts#:~:text=export%20function-,getGitLog,-(path%3A)

## git log로 출력된 문자열 parse하기

git log로 출력된 문자열은 commit별로 분리되어 들어오는 것이 아니라 하나의 문자열로 들어오게 됩니다.

따라서 전체 문자열을 한 줄씩 차례대로 읽으면서 어떤 필드에 해당하는지 분류해야 합니다.

한 줄씩 분리한 것들을 쭉 돌면서 동일한 필드별로 담습니다.

문자열에서 시작하는 단어가 동일한 경우 `str.startsWith`으로 검사하여 담습니다.

그 외의 경우는 commit message와 fileChanged의 경우인데,

모든 경우에 가지는 특징을 잡아 해당 특징의 경우에 분류합니다.

- commit message의 경우
    항상 CommitDate의 두 줄 밑에서 시작하고, 해당 메시지 부분은  빈 문자열인 ""가 위아래로 둘러싸여 있습니다.

- fileChanged의 경우
    항상 commit message 이후 숫자 또는 -로 시작합니다.

```javascript

if (str.startsWith("CommitDate")) {
        let indexCheckFileChanged = idx + 2;
        let eachCommitMessage = "";
        while (splitByNewLine[indexCheckFileChanged] !== "") {
          if (eachCommitMessage !== "") {
            eachCommitMessage += "/n";
          }
          eachCommitMessage += splitByNewLine[indexCheckFileChanged].trim();
          indexCheckFileChanged += 1;
        }
        commitDates.push(new Date(str.split(": ")[1].trim()));
        messages.push(eachCommitMessage);
      }
      if (/^\d/.test(str) || /^-/.test(str)) {
        const [addition, deletion, path] = str
          .split(" ")
          .filter((e) => e)[0]
          .split("\t");

        const numberedAddition = addition === "-" ? 0 : Number(addition);
        const numberedDeletion = deletion === "-" ? 0 : Number(deletion);
        differenceStatistics[commitIdx].totalInsertionCount += numberedAddition;
        differenceStatistics[commitIdx].totalDeletionCount += numberedDeletion;
        differenceStatistics[commitIdx].fileDictionary[path] = {
          insertionCount: numberedAddition,
          deletionCount: numberedDeletion,
        };
      }


```

[function getCommitRaws](https://github.com/githru/githru-vscode-ext/blob/main/packages/analysis-engine/src/parser.ts#:~:text=export%20function-,getCommitRaws,-(log%3A)

**Comment by ansrlm** [comment]
상세한 설명 잘 읽었습니다~

**Comment by ooooorobo** [comment]
arguments 별로 설명 작성해 주신 것 너무 좋습니다~! 과거 관련 이슈 링크해주신 것도 좋아요!
잘 읽었습니다~!

**Comment by ytaek** [comment]
이슈 정리중입니다! 
다른 이슈 없으시면 close 시켜 주시면 감사하겠습니다~.

**Comment by ytaek** [comment]
knowledge 부분 일단 닫고, 추후 정리하는 것으로 일단 가겠습니다.
