### ISSUE TITLE
[engine] additional information : PR

### ISSUE THREAD

**Issue by ansrlm** [githru/githru-vscode-ext#184]
### Content
- 현재 analysis-engine의 정보는 git log command를 기반으로 구성되어 있습니다.
- 추가적으로 PR과 관련된 정보를 가져옵니다.

### Coverage
- @octokit기반의 싱글톤 작업이후에 진행합니다.
- PR 정보 중 하단의 링크를 참조해서 어떤 데이터를 가져올지 정의합니다.

### FYI
- https://github.com/githru/git-metadata-preprocessor/blob/master/code/logGenerator.ipynb?short_path=66b1372#L389

**Comment by ytaek** [comment]
PR 정보 꼭 있으면 좋겠어요.. 흐흐
