### ISSUE TITLE
[all] knowledge 수합 및 마이그레이션

### ISSUE THREAD

**Issue by ansrlm** [githru/githru-vscode-ext#189]
### Content
- github.com/githru/githru-vscode-ext/issues에 knowledge label를 가진 이슈들이 존재합니다.
- 궁극적으로 issue들은 닫히는 것이 맞기에 논의가 필요한 항목은 discussion으로, 아카이빙이 필요한 곳은 wiki로 이동하는 것이 맞을 것 같습니다.

### Coverage
- 단순 복사 붙여넣기가 아닌 모든 지식에 대한 재정의 및 점검을 포함합니다.
  - 해당 행위를 하기 위해서 필요하다면 온라인 회의 등을 주최합니다.
- 정리된 부분을 wiki로 마이그레이션 함과 동시에 README.md 파일을 같이 수정합니다.

### FYI
- https://github.com/githru/githru-vscode-ext/issues?q=is%3Aopen+is%3Aissue+label%3Aknowledge

**Comment by ytaek** [comment]
중요한 이슈이나, 일단은 빼겠습니다.
추후 documentation하는 process같은걸 논의해서 만들면 좋겠습니다.

**Comment by ytaek** [comment]
엇, 그런데 작년 팀 중 하나는 documentation해놓은것도 아예 repo로 빼서 handbook 같은 걸 만들었더라구요.
혹시 그런게 필요하다 싶으면 다시 해당 이슈의 우선순위를 올려놔도 좋겠습니다.

**Comment by ytaek** [comment]
이거 빨리 해놓으면 좋겠네요!
우선 순위 올려놓겠습니다.

**Comment by ytaek** [comment]
#597 을 참조하세요.
