### ISSUE TITLE
githru 퍼소나 및 유저스토리 정의 관련 논의 요청

### ISSUE THREAD

**Issue by anpaul0615** [githru/githru-vscode-ext#192]
https://ieeexplore.ieee.org/document/9222261 의 2.2 Target Users 섹션의 내용과 제 개인적인 의견을 섞어서
githru 의 퍼소나(Persona) 를 정의하고, 그에 해당되는 유저스토리(User Story) 를 정리해보았습니다.

이를 바탕으로 우리 제품이 어떤 사용자를 가져야 하는지에 대한 논의를 요청드립니다.

이 논의를 요청드리는 이유는
우리 제품이 마켓에서 어떤 사용자를 타겟으로 삼아야하는지를 정해보면
자연스럽게 어떤 feature 가 필요한지 식별할 수 있을 것 같았기 때문입니다.

아래 내용들은 결코 확정적인 것이 아니며,
우리 githru 팀원분들의 다양한 의견들과 함께 보강되어갈 내용이라고 봐주시면 좋을 것 같습니다.

여러분들께서 각자 의견들을 다양하게 공유해주신다면
우리 제품의 가치를 찾아나가는 데 정말 많은 도움이 될 수 있을 것 같습니다.

적극적인 참여 부탁드립니다. 감사합니다.

---

## Persona

- git 을 사용할줄아는 (optional)
- 특정 프로젝트의 작업 히스토리 파악이 필요한
- 개발자/매니저/테스터

## User Story

- 특정 파일/디렉토리에서
  - 누가 많이 작업했는지 알고싶습니다.
  - 언제 어느시점에 작업이 있었는지 알고싶습니다.
  - 어떤 작업유형이 많이 있었는지 알고싶습니다.

- 특정 사람이
  - 어떤 파일/디렉토리를 주로 작업했는지 알고싶습니다.
  - 언제 어느시점에 주로 작업했었는지 알고싶습니다.
  - 어떤 작업유형을 주로 만들었는지 알고싶습니다.

- 특정 기간에
  - 어떤 사람이 주로 작업했는지 알고싶습니다.
  - 어떤 파일/디렉토리가 변경되었는지 알고싶습니다.
  - 어떤 유형의 작업이 주로 있었는지 알고싶습니다.

- 특정 작업유형을
  - 어떤 사람이 주로 작업했었는지 알고싶습니다.
  - 언제 어느시점에 주로 생성됐는지 알고싶습니다.
  - 어떤 파일/디렉토리에서 주로 작업했었는지 알고싶습니다.

- 이 모든걸 한번에 눈으로 쉽게 파악하고 싶습니다.

**Comment by ytaek** [comment]
한번쯤 해야되지 않을까 싶었는데, 스타트 끊어주셨네요 👍 

<img width="411" alt="image" src="https://user-images.githubusercontent.com/24404665/190836721-d80a6f5a-e403-4911-9da7-7c80e4211d79.png">

githru paper쓸 때 작성했던 자료입니다.
Persona를 할때도 Primary/Secondary/... 를 나누면 더 명확하게 할 수 있습니다.

저희는 아무래도 IDE사용자를 대상으로 하니, paper와는 달리 `개발자`가 primary에 더 가까울 것 같고, 
newcomer를 집중적으로 한다기보다는 일상적인 개발 환경에서의 얘기로 조금 바꿔줄 필요가 있겠네요.

그리고 실명을 붙여야 제맛이지요 😅 

- `바울`은 개발자이다. 
- `바울`은 판교에 서식하고 있고, 체크 남방을 즐겨입는다.
- ...

**Comment by ytaek** [comment]
http://www.yes24.com/Product/Goods/6585853

막 소설같이 재밌는 책은 아니겠습니다만, 
HCI 관련 수업을 들은 적이 없다면, 한번 쯤 읽어보는 것도 괜찮을 것 같아요 : -)

**Comment by wherehows** [comment]
본 내용과는 상관 없지만, 혹여 저 같은 분이 계실까봐

페르소나와 유저스토리라는 단어가 무엇을 의미하는지 몰라서 찾아봤는데, 괜찮은 링크 공유드립니다.
링크: https://yozm.wishket.com/magazine/detail/754/

**Comment by ytaek** [comment]
일단 v0.2에서 제외합니다만, 사용자 분석해보는것도 매우매우 중요하다고 생각합니다.
날 잡아서 하시죠 : -)

**Comment by ytaek** [comment]
UI Renewal 에 따라 우선 close 합니다.
