### ISSUE TITLE
VSCode에서 View Node Type 사용 관련 이슈

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#196]
mapper쪽에서 사용하는 건데,
현재 vscode는 engine만 import해서 의존성을 가지고 있습니다.
engine은 node module로 배포가능한 형태로 bundling되고, package.json에 의존성을 선언해놓아서 괜찮은데,
view는 그런게 없기 때문에 만약 view가 monorepo에서 떨어져 나가거나 하면 빌드가 깨질 것입니다.

해서 일단 view에서 type 선언 파일을 복사를 해서 처리했습니다.

추후에는 아래 방법 등으로 수정이 필요하겠습니다.
- view가 react bundle 외에 type만 module export할 수 있도록 만들던지
- mapper가 view type을 모르고 작업할 수 있도록 하던지 

@githru/view 팀, mapper작업하신 @anpaul0615 님 참고 부탁드립니다~.

_Originally posted by @ytaek in https://github.com/githru/githru-vscode-ext/pull/194#discussion_r973569442_

**Comment by anpaul0615** [comment]
(질문)
vscode 가 engine 만 알고있어도 괜찮을까요?
vscode 가 view 를 모르면, view가 이해하는 데이터를 전달하려면 어떻게 해야하는지 모르겠습니다.

vscode 는 (데이터와 화면을 조합해서) githru 를 vscode-ext 형태로 만들어주는 역할이니깐,
자연스럽게 어떤 데이터와 어떤 화면을 사용할지에 대해 의존성이 생길것같은데요.

어떤 데이터를 사용할지에 대해서는 engine 의 output 인터페이스를 참조하고,
어떤 화면으로 보여줄지에 대해서는 view 의 input 인터페이스를 참조해야할 것 같아서요.

그래서 개인적으로는 
> view가 react bundle 외에 type만 module export할 수 있도록 만들던지

이 방향대로 view 의 input 인터페이스를 export 해서, 
그걸 vscode 에서 import 하는 구조를 만드는게 괜찮지않을까 생각합니다.
(=vscode dependencies 에 view 추가)


---

그게 아니라면..
차라리 engine 의 output 인터페이스를 공유하는 방법도 생각할 수 있을 것 같아요.
(물론 이 방법은 기획하신 내용과는 전혀 다른 방향이긴 합니다..ㅎㅎ)

화면에서 데이터에 대한 스펙을 알고있으면, (마치 client-server 모델처럼)
하나의 데이터를 view1, view2, .... 등의 다양한 화면이 사용할수있는 구조로 가져가는 방법도 괜찮지않을까 싶어요.
그렇게되면 vscode 에서 하는일은 그냥 engine 호출결과를 그대로 bypass 해버리면 끝나게 될것같아요. (mapper 필요x)

**Comment by ytaek** [comment]
> 현재 vscode는 engine만 import해서 의존성을 가지고 있습니다.

앗. 이게 딱 `현재 code 상태`를 뜻했습니다 ㅎㅎ 
지금 package.json에 engine만 dependencies가 걸려있거든요.
view에도 dependency를 걸려면, 아마 view의 bundling output이 다른 형태로 되어야 할 것 같아요.
(이 부분은 확실하지 않습니다. 제가 하나의 src를 react로, node module로 같이 export 되도록 만들어지게 해 본적은 없어서...)

---

저는 지금 구조를 vscode를 Backend의 controller, view를 FE라고 두고,
둘이서 HTTPRequest로 통신을 하는 것 처럼 생각하면 될 것 같은데요.
(지금 string만 되는 상황이 그와 매우 유사해 보이기도 하구요).

일단 BE관점에서는, API 명세(?)대로 던져줘야 하는데, 그 명세를
1. vscode controller가 어떻게 넘겨줄지를 정하든지(engine결과를 mapping), 혹은 
2. @anpaul0615 님이 두번째에 말씀하신 대로 engine에서 정한걸 다같이 쓰던지,
하게 될꺼구요.

1번은 engine결과 및 Type을 DTO처럼 바꿔주는 mapper의 역할일꺼고 (양방향 Two-way mapping)
2번은 core(businuess) layer에 있는 type을 그대로 넘겨주는 것일꺼구요 (단방향 One-way mapping)

FE관점에서는, API 명세를 보고
1. Engine의 Type을 그대로 써서 해석하던지
2. View만의 Type을 가지고 바꿔서 쓰던지 해야겠네요.

---

지금 머리가 잘 안돌아가서, 혹시 헷갈린 답이 될 수도 있을 것 같은데.. 😢 
더 논의해봐도 좋습니다. 미팅으로 따로 얘기해도 좋구요~.

**Comment by ytaek** [comment]
요것도 0.2에 해결하고 갑시다!

**Comment by ytaek** [comment]
0.3으로 미룹니다!
