### ISSUE TITLE
[view] temporal filter 개선 작업

### ISSUE THREAD

**Issue by kmin-jeong** [githru/githru-vscode-ext#199]
이슈 [166번](https://github.com/githru/githru-vscode-ext/issues/166)에서 해야할 작업들 중에 그래프 개선하는 작업 3가지만 먼저 가져가겠습니다!
 y축 오른쪽 배치 -> 왼쪽 배치 변경
 x축 날짜 표시 조금 더 디테일 하게 변경
 styles: 아랫쪽을 더 쳐다보도록 회색 계정 컬러 + 톤다운

**Comment by jin-Pro** [comment]
https://github.com/githru/githru-vscode-ext/issues/166#issuecomment-1248952604
