### ISSUE TITLE
[view] File Icicle Tree의 파일을 클릭했을 때 해당 파일의 Diff를 보여주기

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#200]
- [ ] File Icicle Tree의 파일을 클릭했을 때 해당 파일의 Diff 보여주기

**Comment by wherehows** [comment]
Icon 라이브러리 도입하기 작업 시작하겠습니다.

**Comment by wherehows** [comment]
'File Icicle Tree의 파일을 클릭했을 때 해당 파일의 Diff 보여주기' 기능 구현 시작하겠습니다.

**Comment by jin-Pro** [comment]
(궁금) 혹시,, 해당 issue를 @wherehows 님께서 모두 작업하시려고 하는건가요..??ㅎㅎ,,

**Comment by wherehows** [comment]
@jin-Pro 엇 아니에요~ 그런데 한 이슈에 여러 개의 수정사항 두지말고 하나만 두도록 쪼갤까요?

**Comment by jin-Pro** [comment]
> @jin-Pro 엇 아니에요~ 그런데 한 이슈에 여러 개의 수정사항 두지말고 하나만 두도록 쪼갤까요?

쪼갤수있으면 쪼개는게 좋을 것 같아요..!

**Comment by wherehows** [comment]
> > @jin-Pro 엇 아니에요~ 그런데 한 이슈에 여러 개의 수정사항 두지말고 하나만 두도록 쪼갤까요?
> 
> 쪼갤수있으면 쪼개는게 좋을 것 같아요..!

분리해놓을게요~!

**Comment by ytaek** [comment]
쪼개주셔서 감사합니다~. 이것도 있으면 꽤 유용할 것 같습니다!.

음.. 이미 작업에 들어가신 것 같은데... 이 아이템은 빨리 치고 나오면 참 좋을 것 같네요 : -)

@wherehows 님, 저랑 같이 공동 작업하시면 어떨까요?
제가 vscode api쪽을 작업하고, @wherehows 님은 diff editor 부분 및 file icicle tree click event 부분 작업해주시면 빠르게 될 것 같습니다.

**Comment by wherehows** [comment]
@ytaek  작업...에 들어갔다고 하기도 민망한게 diff 보여주는 것에 대한 리서치가 잘 안돼서 깃 그래프 리버스 엔지니어링 하고있었습니다. ㅠㅠ

말씀해주신 file icicle click event는 클릭했을 때 view가 보여지는 이벤트 핸들러 구현이고 diff editor는 보여지는 view가 맞을까요?

알겠습니다~ 우선은 토욜까지 코드 틀 만들어 오는 것을 목표로 달려보겠습니다. 😵

**Comment by ytaek** [comment]
> @ytaek 작업...에 들어갔다고 하기도 민망한게 diff 보여주는 것에 대한 리서치가 잘 안돼서 깃 그래프 리버스 엔지니어링 하고있었습니다. ㅠㅠ

음. 아마도 vscode 쪽에 diff editor를 호출하면 되는 걸로 알고 있어요.
vscode repository 쪽에서 가지고 있는 command가 있을 것 같은데...
이 부분 한번 찾아봐주시면 좋을 것 같구요.
아니면 제가 찾아봐도 되구요.

> 말씀해주신 file icicle click event는 클릭했을 때 view가 보여지는 이벤트 핸들러 구현이고 diff editor는 보여지는 view가 맞을까요?
> 알겠습니다~ 우선은 토욜까지 코드 틀 만들어 오는 것을 목표로 달려보겠습니다. 그래도 괜찮을까용? 😵

결국 click했을 때 vscode 쪽으로 file editor를 열어주세요~ 하고 요청하는 부분인데요.

vscode와 연동하는 부분은, 제가 이전에 해봤던 것들이 있어서, 먼저 작업할 수 있을 것 같아요.
오늘/내일 중으로 PR 한번 올려보겠습니다.
file tree에서 click event 넣는 부분 작업해주실 때 그 부분을 넣으면 될 것 같아요.

**Comment by wherehows** [comment]
> 음. 아마도 vscode 쪽에 diff editor를 호출하면 되는 걸로 알고 있어요.
vscode repository 쪽에서 가지고 있는 command가 있을 것 같은데...
이 부분 한번 찾아봐주시면 좋을 것 같구요.
아니면 제가 찾아봐도 되구요.

한번 제가 찾아보겠습니당~

> vscode와 연동하는 부분은, 제가 이전에 해봤던 것들이 있어서, 먼저 작업할 수 있을 것 같아요.
오늘/내일 중으로 PR 한번 올려보겠습니다.
file tree에서 click event 넣는 부분 작업해주실 때 그 부분을 넣으면 될 것 같아요.

확인했습니다.

**Comment by wherehows** [comment]
우선은 v0.2 타겟에서는 뺄께요 ㅜ.ㅜ 혹시 좋은 방법을 찾게 되면 그때 다시 넣어도 괜찮을 것 같습니다.
> 넵 알겠습니당.

**Comment by ytaek** [comment]
@wherehows 영후님, 이거 언제 하시나요 ㅋ

**Comment by ytaek** [comment]
UI Renewal 에 따라  우선 close 합니다.
