### ISSUE TITLE
[view] button 요소 내 button 요소가 children으로 존재하여 발생하는 에러

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#201]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/81841082/190907796-21981962-0ec5-48a7-86ae-8f03ea291d9d.png">

summary 컴포넌트 내 버튼 요소의 children 요소로 버튼 요소가 존재하여 위와 같은 에러가 발생합니다.

**Comment by jin-Pro** [comment]
(궁금) 혹시 해당 에러가 발생하는 시나리오를 알 수 있을까요? 그냥 렌더링 직후 발생하는 에러일까요??

**Comment by wherehows** [comment]
> (궁금) 혹시 해당 에러가 발생하는 시나리오를 알 수 있을까요? 그냥 렌더링 직후 발생하는 에러일까요??

헐. 제가 댓글을 안남겨서 작업이 겹친걸까요?

**Comment by jin-Pro** [comment]
> > (궁금) 혹시 해당 에러가 발생하는 시나리오를 알 수 있을까요? 그냥 렌더링 직후 발생하는 에러일까요??
> 
> 헐. 제가 댓글을 안남겨서 작업이 겹친걸까요? 여기에 수정해서 올려놓았는데 ㄷ_ㄷ #202

아닙니다 ㅎㅎ,,, assign되었는데 다른 이슈하시는 줄 알고 제가 밀어붙였습니다 죄송합니다 ㅎㅎ,,,

**Comment by jin-Pro** [comment]
해당 merge 되시면 제 pr closed 해주시면 감사드리겠습니다! ㅎㅎ

**Comment by ytaek** [comment]
해결되었다면 close처리 부탁드립니다~.
