### ISSUE TITLE
[view] author 작업 모아 보여주기

### ISSUE THREAD

**Issue by hanseul-lee** [githru/githru-vscode-ext#203]
## Content
- author 별 정보 보여주는 기능 추가
  - ex) 회사에서 weekly report 보고 시, 일주일 간 본인의 작업 기록 한번에 확인 가능 
    - 현재 gitlab에서 이전 작업 다시 훑어보기 or 틈틈히 업무 일지 따로 기록
    - 기간 선택해 해당 기간동안 내 작업 내역 한번에 확인 가능하도록 githru에서 구현해보는 건 어떨까?
  - ex) 퇴사자 작업 기록 모아보기
    <img width="663" alt="image" src="https://user-images.githubusercontent.com/69497936/193704067-8966810a-df5c-4dac-a503-4c41d6c5b793.png">

## Discussion

-  본인의 작업 vs author 별 확인 가능
    - 기본적으로 본인의 commit highlighting
    - author 별 확인
- 언제 정보를 보여줄 것인지
  -  a. Summary author 아이콘과 연계
  - b. Author bar chart와 연계
  - c. 기타
- 선택한 기간에 대한 총 Summary 추가

## FYI
- 참고: githru 내 filter 기능
  <img width="800" alt="스크린샷 2022-09-18 오후 11 58 33" src="https://user-images.githubusercontent.com/69497936/190913725-236e463f-f293-4b6b-90dd-2ae98b2ae572.png">

**Comment by ytaek** [comment]
아.. 이거 정말하면 좋겠는데... 일이 뭔가 좀 있어보이네요.

일단 v0.2로 못박아넣고,

기능은 설계를 한 다음에 잘게잘게 issue로 쪼개면 좋을 것 같습니다.
멋진 제안 감사합니다 : -)
