### ISSUE TITLE
[View] Icicle Tree Height 늘리기

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#205]
# Problem

<img width="1393" alt="스크린샷 2022-09-19 오전 3 10 07" src="https://user-images.githubusercontent.com/70205497/190922202-e31a82ad-31be-418c-a33b-d7e172a76967.png">

위 이미지에서처럼 Cluster Graph는 웹페이지 전체 height을 가득 채우지만,
Icicle Tree는 웹페이지 전체 height을 가득 채우지 않아 여백이 생기게된다.

# Solution

Icicle Tree 의 Height을 늘리자.

**Comment by ytaek** [comment]
늘려주세용! ㅎㅎ
