### ISSUE TITLE
[view] 반응형 개선 작업

### ISSUE THREAD

**Issue by vgihan** [githru/githru-vscode-ext#206]
### 문제 상황
- WebView의 width가 줄어들게 되면, line chart와 하위 컴포넌트들이 충돌되는 문제 발생합니다.
- 추가로 ClusterGraph가 잘리는 문제가 발생합니다.
- 일정 width 이하로 줄여지지 않게 구현할 수 있고, width를 줄이더라도 line chart와 충돌이 없도록 수정이 필요합니다.

![image](https://user-images.githubusercontent.com/49841765/190922227-bd6db801-248f-41dd-909f-ebaa7f572b0a.png)

**Comment by ytaek** [comment]
@vgihan 님, 해당 이슈는 얼마나 걸릴까요?
짧으면 바로 하면 좋겠고,
큰 작업이 필요로 하는 거라면 다음 번으로 미뤄도 괜찮겠습니다.

우선 v0.2로 해놓을께요.

**Comment by vgihan** [comment]
영진님이 https://github.com/githru/githru-vscode-ext/pull/209 PR에서 작업해주셔서, 해당 이슈는 영진님 PR이 반영된 이후에 close 해도 될 것 같습니다 !!
