### ISSUE TITLE
[bug] React githru 적용 에러

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#207]
# Problem

react 라이브러리에서 githru를 실행시켰을 때의 화면입니다.

<img width="1440" alt="스크린샷 2022-09-19 오전 3 18 04" src="https://user-images.githubusercontent.com/70205497/190922430-d1aca1b2-c3cb-4e7d-b20a-90e4156e9305.png">

아직은 문제만 확인한 상태입니다!

**Comment by ytaek** [comment]
아.. githruData쪽 string넘어갈 때 뭔가 이슈가 있는 것 같네요. 한번 테스트 해보면 좋겠는데,
명확한 test scenario 말씀해주시면 좋겠습니다!

이건 해결하고 가야겠네요.

**Comment by jin-Pro** [comment]
> 쪽 string넘어갈 때 뭔가 이슈가 있는 것 같네요. 한번 테스트 해보면 좋겠는데,
> 명확한 test scenario 말씀해주시면 좋겠습니다!

react를 clone해서 해당 폴더 위치에서 vscode를 열고 githru를 실행하였습니다.
githru 실행 결과 화면을 기다렸고,
결과 화면이 위의 이미지와 같았습니다.

**Comment by ytaek** [comment]
String(engine에서 넘어오는)이 매우매우 길 때의 이슈인 것으로 보입니다.
React repo가 대략 16000개 정도의 commit을 가지고 있는데...
현재 방식으로는 그 정도 사이즈에 대한게 처리가 힘든 것 같네요.
(속도도 엄청 오래 걸립니다)

마일스톤에서 제외하고 좀 두고 볼 이슈로 놔두겠습니다.
