### ISSUE TITLE
[View] Cluster 다중 선택

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#208]
# Problem

현재는 Cluster를 Click하면 해당 Cluster에 대한 토글 기능만 존재하며,
Click한 Cluster가 존재할 경우, 다른 Cluster를 클릭하면 선택한 Cluster가 바뀌게 된다.

# Example

<img width="1172" alt="스크린샷 2022-09-19 오전 3 25 09" src="https://user-images.githubusercontent.com/70205497/190922710-fc03827c-9939-4492-83ed-b9f165d910dd.png">

**Comment by ytaek** [comment]
음 이게 지난번에 제가 언급했던, 
클러스터를 접었을 때와 선택했을 떄의 action을 나누자는 것이었을까요?

펼쳤다가 접었을 때, deselect 가 되어서 옆 statistics view 쪽이 다시 바뀌는 부분이 생겨서.. 조금 구분이 필요하다는 얘기였거든요.

어쨋든 정리가 필요한 issue이니 v0.2로 놔두겠습니다.

**Comment by jin-Pro** [comment]
이 부분에 대해서 저는

우측 statistics view의 데이터는 선택한 cluster에 대하여 데이터를 보여준다 생각하였기에,
펼쳤다가 접었을 때 아무 것도 선택이 되지 않았다면, 초기 상태와 동일하게 statistics view 에서는 초기 상태와 동일하게 전체 데이터를 보여줘야한다고 이해하고 있었습니다.

@ytaek 님의 말씀은, 펼쳤다가 접었을 때 상황에 따라 statistics view 데이터가 바뀌면 안된다고 해주신것 같아요.

다중 cluster를 선택할 수 있을 때,

펼쳤다가 접으면, 다른 cluster가 선택이 되어있다면 statistics view의 데이터가 바뀌는게 맞고
펼쳤다가 접으면, 다른 cluster가 선택이 되지 않았다면 statistics view는 데이터가 바뀌지 않아야 한다는 말씀이실까요??
