### ISSUE TITLE
[view] 디테일 컴포넌트 시간과 author 짤리는 부분 개선하기

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#211]
- [ ] 디테일 컴포넌트 시간과 Author이 짤리는 부분 개선하기
![image](https://user-images.githubusercontent.com/81841082/190903306-6a65763d-a898-4004-8c88-b7e70c8711b4.png)

**Comment by ytaek** [comment]
개선되면 좋겠습니다!
wrap 으로 되거나 하는 거면 금방 될 수도 있긴 하겠네요.

일단은 동작하는 기능이라 v0.2에서는 빼겠습니다.

**Comment by Jaeheon-Sim** [comment]
message 부분과 시간, author 정보를 분리해 해결했습니다.
다만 현재는 정보들이 두 줄로 구현이 되어 있어, 해당 정보들을 한 줄로 나타낼 방법을 생각해보면 좋을 것 같습니다.
