### ISSUE TITLE
[view] 디테일 컴포넌트에 트랜지션 적용하기

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#212]
- [ ] 디테일 컴포넌트에 트랜지션 적용하기
![image](https://user-images.githubusercontent.com/81841082/190903318-58395663-65f7-4d53-a9f7-6c5a2e8a76fa.png)

### 참고
~~한슬님께서 적용하려다가 제대로 적용되지 않아서 작업을 중단한 코드가 주석처리 되어있습니다.~~
기존 적용된 애니메이션이 최적화되어 있지 않아 열고 닫는 액션이 부자연스러워 해당 코드 주석처리하였습니다. (한슬)

**Comment by ytaek** [comment]
음 이건 제가 결정을 못하겠네요.
우선 동작 하는 부분이라, v0.2에서 빼놓을껀데,
중요하다고 생각이 드시면 v0.2로 다시넣어주시면 감사하겠습니다.

**Comment by hanseul-lee** [comment]
#226 에서 기한님이 적용해주신 트랜지션 말고 디테일 컴포넌트에 추가되어야 할 트랜지션이 무엇인지 구체적으로 여쭤보아도 될까요?

**Comment by wherehows** [comment]
> #226 에서 기한님이 적용해주신 트랜지션 말고 디테일 컴포넌트에 추가되어야 할 트랜지션이 무엇인지 구체적으로 여쭤보아도 될까요?

Cluster Graph는 transition과 함께 보여지는데, Detail이 보여질때는 똬 하고 펼쳐지는게 조금 어색해 보여서, Detail도 transition을 추가되면 좋겠다 해서 issue 등록해놨었습니다~
