### ISSUE TITLE
[view] 디테일 컴포넌트의 commit hash값을 클릭했을 때 복사되게 하기

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#213]
- [ ] 디테일 컴포넌트의 commit에 복사 기능 넣기
![image](https://user-images.githubusercontent.com/81841082/190903326-bf74eb34-4419-46bf-8539-0b0737c9714d.png)

**Comment by ytaek** [comment]
좋은 아이디어 입니다 : -)

일단 데모용으로 급하지는 않는 부분이라 v0.2에서는 제외하겠습니다.

**Comment by hanseul-lee** [comment]
(궁금) commit hash 값이 복사되면 어떤 곳에 사용하기 유용한가요?

**Comment by wherehows** [comment]
요거 git graph가 기능을 갖고 있어서 카피했습니다~!

**Comment by ytaek** [comment]
> (궁금) commit hash 값이 복사되면 어떤 곳에 사용하기 유용한가요?

제 경우는 tagging이 안되어 있는 commit 등으로 checkout하거나 rollback할 때 유용했던 것 같습니다~
