### ISSUE TITLE
[engine] branch 이름 목록을 가져오기

### ISSUE THREAD

**Issue by ooooorobo** [githru/githru-vscode-ext#219]
#198 작업으로, 특정 브랜치를 기준으로 Stem, CSM을 생성할 수 있게 되었습니다.
view에서 기준 브랜치를 선택할 수 있도록, 현재 repository에 존재하는 브랜치 목록을 함께 데이터로 넘겨줍니다.

- 현재 git repository에 존재하는 브랜치 이름 목록을 반환하는 함수를 만듭니다.
- 브랜치 이름 목록을 data에 함께 담아서 보내줍니다. 

---

        > AnalysisEngineArgs에서 받아오도록 변경되어야 할 것 같아요

현재 git branch가 바라보고 있는 basebranchName을 vscode에서 전달하는 것으로 변경이 필요할 것 같네요. 
다음과 같은 플로우로 예상이 됩니다.
1. view에서 select box의 values로 들어갈 branch list 및 value 선택에 대한 부분을 vscode로 passing
2. vscode는 해당 적용에 따라서 analyzeGit에 아규먼트로 브랜치 명칭을 전달
3. 처리된 부분을 return

3의 경우는 처리가 되어 있어서 vscode쪽에서 view에 함수를 제공하는 부분과 함수에 대한 callback처리가 필요하고
부차적으로는 브랜치 명칭 리스트를 쭉 뽑아내는 함수를 만들어야 할 것 같습니다. (analysis-engine에 있어서 리스트도 함께 data로 던져주어도 좋을 것 같네요)

_Originally posted by @ansrlm in https://github.com/githru/githru-vscode-ext/pull/198#discussion_r973736984_

**Comment by ytaek** [comment]
@anpaul0615 님이 새로 만드실 이슈에 이게 포함될 것 같습니다.
마일스톤 새로 할당합니다.

**Comment by ytaek** [comment]
#276, #277, #278로 새로 만들어서 진행합니다.
