### ISSUE TITLE
[view] author bar chart author 이름 avatar로 변경 

### ISSUE THREAD

**Issue by hanseul-lee** [githru/githru-vscode-ext#220]
## Related Issue
- #147 
- #178

## Content
>   7. bar chart를 나중에 avatar 정보를 긁어오게 된다면, 아래 GitHub처럼 horizontal로 해도 괜찮겠네요 ㅎㅎ (지금은 item의 이름이 길어 horizontal로 하긴 했습니다.)

![image](https://user-images.githubusercontent.com/69497936/192085467-0d99239d-39b5-4c1a-aff7-9b60eba632d1.png)

**Comment by KirschX** [comment]
author bar chart 컴포넌트 author 이름을 avatar로 변경
