### ISSUE TITLE
[engine] root-commit을 가진 Stem인지 식별하는 로직 추가

### ISSUE THREAD

**Issue by ooooorobo** [githru/githru-vscode-ext#221]
(orphan branch 등으로 인해) root-commit이 2개 이상인 상황에 대응하기 위해, Stem에 root-commit이 포함되어 있는지 식별하는 로직을 추가합니다.

---

    이건 추가적인 이슈인데요.
    
    root-commit 이 2개 이상인 상황에서의 stem, csm 생성처리가
    현재 시점에서는 대응이 안되는걸로 보여요.
    
    이번 PR 기준으로 예를들면,
    1) buildStem 에서 baseBranch 를 파라미터로 받아왔을때,
        baseBranch 의 stem 에서 root-commit 을 반드시 포함하게 되고, (aka root-stem-1)
    2) 또 다른 root-commit 으로부터 시작된 커밋들로 stem 이 만들어지고,
    3) 그 중에서도 두번째 root-commit 을 포함하고있는 stem 이 만들어지게 될텐데, (aka root-stem-2)
    4) buildStem 의 결과에서는 root-stem-1 는 식별할수있는데 (branchName)
        root-stem-2 를 식별할 수 있는 방법이 없는 상황입니다.
    
    buildCSM 의 내부 처리절차가 root-commit 부터 순회하는 거라서,
    위 상황에서는 root-stem-2 로 csm을 만들수 없는 상황이네요.
    
    사실 이 부분은 view 에서 사용하는 ClusterNode[] 에서도 적용되는 이슈가 될 수도 있겠네요.
    (ClusterNode[] 가 아니라 ClusterNode[][] 가 되어야할지도..??)

    결론:
    - root-commit 을 가지고있는 stem 을 식별할 수 있는 장치가 필요하다

_Originally posted by @anpaul0615 in https://github.com/githru/githru-vscode-ext/issues/198#issuecomment-1252434470_

**Comment by ytaek** [comment]
Progressive CSM plan에 추후 포함 예정입니다.
