### ISSUE TITLE
[view] summary 반응형 적용 css 이슈

### ISSUE THREAD

**Issue by hanseul-lee** [githru/githru-vscode-ext#225]
## Related PR
- #223 

## Content
- vertival cluster list summary에서 850px 이하에서는 hover 시 css가 제대로 적용되지 않는 이슈 존재
  <img width="311" alt="image" src="https://user-images.githubusercontent.com/69497936/192109317-27fcf27b-623b-4116-b4bf-3744c0cab790.png">

**Comment by chaejunlee** [comment]
간단한 오타였던 것 같습니다. `200px`로 되어있던 값을 `300px`로 바꾸니 해결된 문제였습니다.
