### ISSUE TITLE
[view] VerticalClusterList에서 Cluster 클릭 시 스크롤 개선

### ISSUE THREAD

**Issue by vgihan** [githru/githru-vscode-ext#226]
## Related PR

- https://github.com/githru/githru-vscode-ext/pull/231

## Content

아래와 같이 VerticalClusterList에서 Cluster를 클릭하면 화면 중간에 Detail 컴포넌트가 펼쳐지는데, 이 때 스크롤이 부드럽게 이어지지 않고 곧바로 스크롤 전환이 일어나기 때문에, 위쪽 Cluster를 펼치는 건지 아랫쪽 Cluster를 펼치는 건지 구분하기가 어렵습니다. 아래와 같이 부드러운 스크롤을 통해 개선할 수 있습니다.

(before)
![s_before](https://user-images.githubusercontent.com/49841765/192129573-1f0c1ebf-db4e-4d80-a096-af17ec302383.gif)

(after)
![s_after](https://user-images.githubusercontent.com/49841765/192129613-19401a07-b82b-45c6-a6d7-d2cd3be73325.gif)

**Comment by hanseul-lee** [comment]
@vgihan 님 클러스터 클릭시 인터렉션 관련해 궁금한 것이 있는데요
ClusterGraph가 어디를 클릭하든 항상 위에서 아래로 내려가게 움직이는데 
만약 아래쪽을 cluster 클릭 시 아래에서 위로 올라가게도 구현이 가능하실까요?

**Comment by vgihan** [comment]
사실 Detail이 펼쳐지고 그래프의 transition이 발생할 때, 어딘가 좀 어색해보이는 것 같은 느낌이 들었는데, 한슬님 말씀들어보니 그 부분이 문제인 것 같기도 하네요 ! 아마 구현하려면 그래프의 이전 상태를 기억해야해서 useRef로 처리할 수 있을 것 같은데, 제가 assign해서 맡아보도록 할게요 ! 개선할 부분 찾아주셔서 감사합니다 :)
