### ISSUE TITLE
[view] summary windowing 추가 (+무한 스크롤)

### ISSUE THREAD

**Issue by jejecrunch** [githru/githru-vscode-ext#235]
@momomingzhi 님께서 피드백해주신 내용이었는데 클러스터가 많아질 경우를 대비해서 반드시 추가해야하는 내용 같습니다.
제가 고민이 되는 부분은 graph 부분에서 지정해주신 `scroll: "smooth"`와 충돌하지 않을까 하는 것입니다만...
단순히 windowing 기법만 넣는다면 상관없을 것 같긴 합니다.

cf. https://ko.reactjs.org/docs/optimizing-performance.html#virtualize-long-lists
https://tech.kakaoenterprise.com/149

**Comment by ytaek** [comment]
UI Renewal로 close 합니다.
