### ISSUE TITLE
[view] cluster graph를 일반적인 branch graph로 보여주기

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#241]
기존에 아래와 같이 나와있는 cluster graph를

<img width="86" alt="image" src="https://user-images.githubusercontent.com/81841082/193401761-fa1e0c8a-096a-430c-a845-cf6879cadeb6.png">

아래와 같이 일반적인 commit graph로 바꿀수도 있는 기능을 추가합니다.

<img width="63" alt="image" src="https://user-images.githubusercontent.com/81841082/193401789-5ab67a2d-ab81-4919-ab32-8fbd8dd3b9dc.png">

사용자는 cluster graph와 commit graph를 모두 볼수 있도록 합니다.

## Note

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/81841082/193401871-c6460515-f4cf-4066-ac17-136af7cc45a8.png">

**Comment by ytaek** [comment]
일단 branch를 이용해서 straighten 시키는 부분은 좀 간단하게 해도 될것 같습니다.
제대로 branch 고려해서 하려면 좀 어려우니까, 일단 node라도 표현을 다 할 수 있으면 좋겠네요.

**Comment by vgihan** [comment]
급한 만큼 진행 상황부터 조금 공유하고 가겠습니다 ! 아래와 같이 vertical link 는 연결한 상태이고, 마지막 horizontal link 연결 작업 수행해서 오늘 안까지 PR 올리도록 하겠습니다 :)
![image](https://user-images.githubusercontent.com/49841765/194267850-167f1411-9236-4ccd-aea5-4b32dc92acc2.png)

**Comment by ytaek** [comment]
#360 에서 이어갑니다.
