### ISSUE TITLE
[engine] git log parser 회의 내용 공유_PR commit에 관하여

### ISSUE THREAD

**Issue by blcklamb** [githru/githru-vscode-ext#27]
## 문제 상황
git log parsing 구현 준비 중에 있고, interface를 고민하고 있습니다.
commit 유형에는 일반/merge/PR이 있는데, 각 commit log의 형태가 달라 구성하는 interface도 달라집니다.

이때 PR commit의 경우는 다음과 같습니다.
```
commit <자기 자신 commit hash 값> <parent commit hash 값>
Author:     <Author 이름> <<Author email>>
AuthorDate: Thu Jul 28 11:52:16 2016 +0200
Commit:     <Commiter 이름> <<Commiter email>>
CommitDate: Thu Aug 4 12:42:55 2016 -0700

    <Commit 메시지>
    
    Fixes: <해결한 Issue URL>(항상 들어가진 않음)
    PR-URL: <PR의 URL>
    Refs: <관련 Issue URL>(항상 들어가진 않음)
    Reviewed-By: <Reviewer 이름> <<Reviewer email>>
    Reviewed-By: <Reviewer 이름> <<Reviewer email>>
    Reviewed-By: <Reviewer 이름> <<Reviewer email>>
    Reviewed-By: <Reviewer 이름> <<Reviewer email>>

<addition> <deletion> <directory>
13      1       src/node_contextify.cc
27      0       test/parallel/test-vm-strict-mode.js
```

### 1. PR commit info
다른 commit과 다르게 `[Fixes]`, `[PR-URL]`, `[Refs]`, `[Reviewed-By]`가 들어가는데,
현재 버전 상에서 commitlist에 해당 정보가 추가되어야할까요?

PR정보는 버전 0.2부터 적용이 된다고 했지만, view에서 PR정보를 작업을 할 때,
해당 commit이 아예 들어가지 않으면 적용할 수 있는 정보가 없을 것이라 예상됩니다.

특히나 오픈소스 레포지토리같은 경우 전부 PR commit으로만 구성되어 있는데, 
예시 [node](https://github.com/nodejs/node/commits/main?before=705fefd30d68e70b0b6aff07567ee0afb8324f89+35&branch=main&qualified_name=refs%2Fheads%2Fmain)
지금 버전 0.1에서 PR 정보를 완전히 제하고 넘기는 것이 맞을까요?

해당 질문은 view팀에서 답변해주시면 좋을 것 같습니다.

### 2. 유형 field 추가
PR이 추가되던 말던 일단 commit 유형이 두 개 이상(일반/merge/(PR))로 나뉘어지는데, 
DAG 및 STEM, CSM 작업 시 commit 유형을 구분할 수 있는 field가 추가되면 좋을까요?

예시

```
{
    Type: "basic",
    commit: [
      "5d3f94e4072863b98dc17c3e43d77c98473bd42f",
      "224512334c9526a24ef49af030f93884102a4d2b",
    ],
    Author: "chaejung Kim",
    AuthorEmail: "whenucan35@gmail.com",
    AuthorDate: "Fri Jul 29 20:01:18 2022 +0900",
    Committer: "chaejung Kim <whenucan35@gmail.com>",
    CommitterEmail: "whenucan35@gmail.com",
    CommitDate: "Fri Jul 29 20:02:36 2022 +0900",
    message: "Feat: log to JSON function, parse01",
    fileChanged: [[Object]],
},

```

해당 질문은 DAG, STEM, CSM 담당하시는 분께서 답변해주시면 좋을 것 같습니다.

**Comment by hy57in** [comment]
@blcklamb 혹시 요런건 discussion으로 옮겨가면 어떨까요?!

**Comment by blcklamb** [comment]
> @blcklamb 혹시 요런건 discussion으로 옮겨가면 어떨까요?!

New Disscussion>Q&A로 설정해서 작성하면 될까요?

**Comment by ooooorobo** [comment]
2 => git log 인터페이스로 세 가지 유형의 커밋을 모두 구분할 수 있다면, git log parsing 할 때 필드를 추가해주시면 이후 로직에서 좀 더 편하고 정확하게 커밋을 구분할 수 있을 것 같아요.

이 정보를 받지 않으면 현재로서는 일반 커밋인지 아닌지 여부를 커밋의 parent 개수만으로 판단해야 하는데,
(`ex. parents.length === 1 -> 일반 커밋 / parents.length > 1 -> 머지 커밋`)
이 경우에는 머지 커밋과 PR 커밋을 구분할 수 없는 문제가 있을 것 같아요. (유일한 판단 기준이 머지 커밋의 메시지 형태인데, 머지 커밋 메시지는 변경 가능하니..)
이런 문제를 해결하는 데 도움이 될 것 같아요

그런데 커밋 로그의 인터페이스가 달라진다는 것은 커밋 메시지의 형식이 달라진다는 거죠?
커밋 메시지 형식은 깃 호스팅 서비스에 따라서 달라지는 것 같아서, 만약 깃 커밋 메시지 형식으로 커밋 타입을 구분한다면 이 부분에 대한 고려가 필요할 것 같아요.

bitbucket으로 머지한 PR의 경우 아래 형식으로 로그에 찍히네요
```
(commit~CommitDate까지는 동일)

    Pull request #<number>: <PR 제목>

    Merge in <repo name> from <source branch> to <targe branch>

    * commit '<commit hash>':
      <PR에 포함된 커밋 제목 목록...>
```

**Comment by ytaek** [comment]
> ## 질문
> ### 1. PR commit info
> 다른 commit과 다르게 `[Fixes]`, `[PR-URL]`, `[Refs]`, `[Reviewed-By]`가 들어가는데, 현재 버전 상에서 commitlist에 해당 정보가 추가되어야할까요?
> 
> PR정보는 버전 0.2부터 적용이 된다고 했지만, view에서 PR정보를 작업을 할 때, 해당 commit이 아예 들어가지 않으면 적용할 수 있는 정보가 없을 것이라 예상됩니다.
> 
> 특히나 오픈소스 레포지토리같은 경우 전부 PR commit으로만 구성되어 있는데, 예시 [node](https://github.com/nodejs/node/commits/main?before=705fefd30d68e70b0b6aff07567ee0afb8324f89+35&branch=main&qualified_name=refs%2Fheads%2Fmain) 지금 버전 0.1에서 PR 정보를 완전히 제하고 넘기는 것이 맞을까요?


오. 저렇게 뽑히는게 어떤 형식인지는 모르겠지만, 
별도의 설정없이 PR merge할 때는 그렇게 들어가지 않는 것 같아요. (저희 pr merge commit 만 봐도..)
뭔가 hook등에다가 설정을 한 것 같구요,
https://github.com/githru/githru-vscode-ext/commits/main

그리고, commit message에 들어가 있는 놈이라서
저 형태가 정확하게 저 form 을 유지하는지는 보장할 수 없을 것 같아요.
그냥 저건 commit message 내용이라고 보는게 좋을 것 같습니다.
(따로 뭔가 message를 파싱하지 않아도 됨)

@ooooorobo 님이 말씀하신 대로 뭔가에 따라 달라지는 것 같네요.

>그런데 커밋 로그의 인터페이스가 달라진다는 것은 커밋 메시지의 형식이 달라진다는 거죠?



> 
> ### 2. 유형 field 추가
> PR이 추가되던 말던 일단 commit 유형이 두 개 이상(일반/merge/(PR))로 나뉘어지는데, DAG 및 STEM, CSM 작업 시 commit 유형을 구분할 수 있는 field가 추가되면 좋을까요?
> 

>커밋 메시지 형식은 깃 호스팅 서비스에 따라서 달라지는 것 같아서, 만약 깃 커밋 메시지 형식으로 커밋 타입을 구분한다면 이 부분에 대한 고려>가 필요할 것 같아요.

음. merge commit을 구분하는 필드는 parent수로 파악이 가능하니, 편리함을 위해 더하는건 상관없는 것 같구요.
이게 PR commit이냐? 라고 하셨는데, 제 생각에는 PR commit이란 구분은 조금 애매합니다.

- PR과 commit이 1:1 로 매핑되는건 아니고, PR 하나가 Commit 여러개를 가질 수 있구요.
- 그럼 PR commit을 PR이 최종 merge 된 commit으로 보면 되지 않느냐? 라고 생각할 수는 있는데,
- 어차피 그것도 merge가 되는 놈이기 때문에 merge냐 PR이냐 라고 나누는건 비교 단위(?)가 맞지 않는 것 같아요.
- 그래서 이 commit이 어떤 PR에 속하는가? 에 대한 정보가 있으면 될 것 같아요.
(기억이 가물가물 한데... 한  commit이 여러개 PR에 속하는 것도 본것 같아요;)


전체적으로 아주 디테일하게 접근한 질문이어서 굉장히 놀랍기도 하고 반갑(?)기도 합니다 ㅎㅎ
생각보다 심도있는 결과물들이 나올 것 같아서 왠지 기대가 많이 되네요!!

**Comment by blcklamb** [comment]
> 
> 그런데 커밋 로그의 인터페이스가 달라진다는 것은 커밋 메시지의 형식이 달라진다는 거죠? 커밋 메시지 형식은 깃 호스팅 서비스에 따라서 달라지는 것 같아서, 만약 깃 커밋 메시지 형식으로 커밋 타입을 구분한다면 이 부분에 대한 고려가 필요할 것 같아요.
> 
커밋 메시지 형식이 바뀌는 것이 아니라 output인 commitList의 필드 값이 바뀔 예정입니다! 우선은 type이 포함되도록 적용해보겠습니다.

**Comment by blcklamb** [comment]
> @blcklamb 님~ 어느정도 인터페이스에 대한 정리가 되신 것 같은데요, type / interface에 해당하는 파일을 먼저 PR을 통해서 토의한 이후 머지하는 것은 어떨까요? 예진님께서 후행 작업하실때 인터페이스가 계속 변경이되면 그부분도 피로로 누적될 수 있을 것 같습니다. 한판(?)을 구성해두고 변경사항 있을때 재 반영하는 구조로 진행했으면 좋겠습니다.

네 좋은 생각입니다. type/interface만 별도로 파일을 만들어서 먼저 PR을 올리겠습니다.
