### ISSUE TITLE
[vscode] githru 열리기 전까지 progress 표시

### ISSUE THREAD

**Issue by ooooorobo** [githru/githru-vscode-ext#321]
githru 버튼을 누른 후 패널이 뜨기까지 시간이 걸리는데, 그동안 progress UI를 표시해 로딩중임을 알 수 있게 합니다

- https://code.visualstudio.com/api/ux-guidelines/notifications#progress-notification
- https://code.visualstudio.com/api/ux-guidelines/status-bar#status-bar-items

**Comment by ytaek** [comment]
status-bar 앞에도 loading 뺑뺑이 돌려놓는 것도 괜찮겠네요!
