### ISSUE TITLE
[vscode, view] PR 링크를 vscode 웹뷰로 띄워주기

### ISSUE THREAD

**Issue by ooooorobo** [githru/githru-vscode-ext#326]
related #324 #325

githru 내에서 PR 혹은 이슈를 열 때, vscode 웹뷰로 열어 vscode 내에서 확인 가능하게 해줍니다

---

### Discussion

@Zigje9 
이 이슈가 vscode webview 로 PR 링크를 띄워주는 것인데, 
필요성과 편의성이 있는지 따져봐야 할 것 같습니다. 

vscode webview 는 노드환경이라, DOM API, 외부 리소스 액세스, CORS 문제가 있을 수 있기에 
웹뷰에서 일반 웹사이트를 open 해주기보다, 커스텀한 UI 생성해서 사용하는게 더 일반적으로 쓰이는 것 같은데요. 

개인적으로는 PR 링크를 브라우저에서 사용하는게 웹뷰보다 편리해 보이는데, 의견이 다를 수 있을 것 같습니다.

참고)
[vscode-webview-doc](https://code.visualstudio.com/api/extension-guides/webview#:~:text=Does%20this%20functionality%20really%20need%20to%20live%20within%20VS%20Code%3F%20Would%20it%20be%20better%20as%20a%20separate%20application%20or%20website%3F)
공식 문서에서 웹사이트와 분리해서 webview 로 사용하는게 정말 필요한지를 검토해보는걸 얘기하네요.

**Comment by ytaek** [comment]
#319 에서 해결합니다.
