### ISSUE TITLE
Contributor-bot 내용 수정 

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#355]
늘어난 contributor들의 표시를 위해, readme의 contributor-bot이 표시하는 내용을 수정하고, 
새로운 contributor들도 추가 가능하도록 수정 필요.

<img width="1101" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/4143d342-7f78-4591-b689-10d2670889c0">

**Comment by ytaek** [comment]
<img width="542" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/121bc9d2-6ad9-47f5-a862-9f788087395f">

이런 느낌?

**Comment by ss-won** [comment]
해당 이슈 맡아서 진행해보고 싶습니다~!~!

**Comment by ytaek** [comment]
project 새로 할당하여 진행합니다.
