### ISSUE TITLE
[view] data typing 정리/다시하기

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#363]

**Comment by 2taesung** [comment]
현재 view 쪽의 정리가 명확히 필요한 타입 코드는 정리 완료했습니다.(#441)

하지만 #343 과 관련된  타입 코드들이 정리가 되지 않아 close 처리하지 않은 상태입니다.
관련 내용은 #343 에서 토론 진행하도록 하겠습니다.

**Comment by 2taesung** [comment]
#343 에서 토론이 완료 됐고 view 관련 작업 issue는 해당 issue로 진행하겠습니다.

**Comment by ytaek** [comment]
#196 도 한번 참고만 부탁드립니다. 이전 논의 기록이 있긴 했었네요. ㅎㅎ
