### ISSUE TITLE
e2e test 적용 (playwright) 준비

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#364]
e2e 적용 (playwright) 준비. 
뼈대마련

**Comment by 2taesung** [comment]
@ytaek 
테스트 컨벤션이 따로 없는 것 같은데 이걸 어떻게 결정하면 좋을까요 ?
일단 생각나는 간단하게 정해야할 규칙은 

- e2e 테스트, 단위 테스트 파일 관리 방식
  => 예를 들어, __test__ 폴더에 몰아 넣을지 각각 테스트 파일 옆에 바로 둘지 
  => 제 의견은 e2e는 폴더로 분류해 관리하고 유닛 테스트 파일은 각각 파일 옆에 두는게 어떨까 생각합니다.
  => 시나리오 단위다보니 여러개의 파일을 e2e 테스트 파일 하나가 검증할 수 있는 여지가 크기에 파일 수가 적고 관심사의 범위가 광범위할 수 있기 때문입니다. 그러나 단위테스트는 하나의 코드와 대칭이 되는게 이상적이기 때문에 바로 옆에 두는게 목적에도 맞고 관리하기도 편할 것 같습니다!
  
- 테스트 파일 명칭 .test. 또는 .spec.
  => 둘다 정상적으로 테스트 파일로 인식하기 때문에 큰 문제는 없지만 하나를 정해서 통일하는게 좋을 것 같습니다!
  => 제 의견은 spec은 BDD의 관점에서 나온 단어이기에 더 직관적인 .test. 로 통일하는게 어떨까 생각합니다!

- 테스트 파일의 안의 레이어 (describe, context, it ... )
  => 이것도 더 디테일하게 생각하면 정해서 통일하면 좋을 것 같긴한데 ... 
  => 아직 테스트가 시작 단계라서 자유롭게 작성하고 문제가 생기면 잡아나가는 것도 좋을 것 같습니다!

**Comment by ytaek** [comment]
> * e2e 테스트, 단위 테스트 파일 관리 방식
>   => 예를 들어, **test** 폴더에 몰아 넣을지 각각 테스트 파일 옆에 바로 둘지
>   => 제 의견은 e2e는 폴더로 분류해 관리하고 유닛 테스트 파일은 각각 파일 옆에 두는게 어떨까 생각합니다.
>   => 시나리오 단위다보니 여러개의 파일을 e2e 테스트 파일 하나가 검증할 수 있는 여지가 크기에 파일 수가 적고 관심사의 범위가 광범위할 수 있기 때문입니다. 그러나 단위테스트는 하나의 코드와 대칭이 되는게 이상적이기 때문에 바로 옆에 두는게 목적에도 맞고 관리하기도 편할 것 같습니다!

네 저도 그게 좋을 것 같습니다 😃 

> * 테스트 파일 명칭 .test. 또는 .spec.
>   => 둘다 정상적으로 테스트 파일로 인식하기 때문에 큰 문제는 없지만 하나를 정해서 통일하는게 좋을 것 같습니다!
>   => 제 의견은 spec은 BDD의 관점에서 나온 단어이기에 더 직관적인 .test. 로 통일하는게 어떨까 생각합니다!

이것도 좋습니다. 

> * 테스트 파일의 안의 레이어 (describe, context, it ... )
>   => 이것도 더 디테일하게 생각하면 정해서 통일하면 좋을 것 같긴한데 ...
>   => 아직 테스트가 시작 단계라서 자유롭게 작성하고 문제가 생기면 잡아나가는 것도 좋을 것 같습니다!

네 이건 자유롭게 하시지요 ㅎㅎ
