### ISSUE TITLE
[engine] githru 실행시 로딩 화면이 계속되는 현상

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#366]
- 환경
WSL: UBUNTU-20.04

- 재현 절차
1. vscode extention 에서 githru install 
2. githru 실행

- 상황 화면
![githru](https://github.com/githru/githru-vscode-ext/assets/66891085/477639ef-b501-43a3-a7d8-5fb580a86eab)

- 비고
  - 로딩 상황이 약 36분 이상 소요(36분 실제 체크)
  - .git 파일의 크기는 4.7M 밖에 되지 않습니다.
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/1dffeb91-2d6a-40fb-8b25-44e1d2b15512)

**Comment by ytaek** [comment]
repo를 clone한 뒤에, 실제로 띄워보고 디버깅 모드로 띄워서 메시지를 확인해보는 것이 좋을 것 같습니다. ㅜ.ㅜ

**Comment by 2taesung** [comment]
> repo를 clone한 뒤에, 실제로 띄워보고 디버깅 모드로 띄워서 메시지를 확인해보는 것이 좋을 것 같습니다. ㅜ.ㅜ

넵 한번 해보겠습니다!
추가로 다른 프로젝트들은 또 정상적으로 작동되니 os나 컴퓨터 환경 문제는 아닌 것 같습니다!
해당 프로젝트와 관련해서 시도해보겠습니다!

**Comment by 2taesung** [comment]
현재 제 환경에서 어떤 프로젝트는 githru가 정상 작동하고 어떤 프로젝트는 해당 버그가 발생합니다. 이 두 프로젝트를 helper>Toggle Developer Tools 로 비교해본 결과 다음과 같은 에러가 발생합니다. engine팀과 상의해봐야겠습니다!
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/dc07eed6-2f80-4a5c-9b55-98d81d5ff9d7)

**Comment by blan19** [comment]
현재 띄워주신 디버깅 콘솔을 확인해본 결과 원인은 `gitRemoteConfigPattern`에서 발생하는 문제 인 것 같습니다.

아래는 예외처리하는 전체 코드입니다
```javascript
export const getRepo = (gitRemoteConfig: string) => {
  const gitRemoteConfigPattern =
    /(?:https?|git)(?::\/\/(?:\w+@)?|@)(?:github\.com)(?:\/|:)(?:(?<owner>.+?)\/(?<repo>.+?))(?:\.git|\/)?$/m;
  const gitRemote = gitRemoteConfig.match(gitRemoteConfigPattern)?.groups;
  if (!gitRemote) {
    throw new Error("git remote config should be: [https?://|git@]${domain}/${owner}/${repo}.git");
  }

  const { owner, repo } = gitRemote;
  if (!owner || !repo) {
    throw new Error("no owner/repo");
  }

  return { owner, repo };
};
```

리모트 주소가 위에 있는 정규식에 따르지 않으면 발생하는 문제로 보여요
현재는 github의 리모트 레포지토리만 깃쓰루에서 사용이 가능한데, 혹시 저기서 사용된 remote 주소가 어떻게 되나요?

**Comment by 2taesung** [comment]
> 

remote 주소를 어떻게 확인할 수 있나요 ?????

**Comment by blan19** [comment]
> > 
> 
> remote 주소를 어떻게 확인할 수 있나요 ?????

git remote 로 연결된 레포 주소 확인해주시면 될 것 같아요!

**Comment by ytaek** [comment]
> > > 
> > 
> > 
> > remote 주소를 어떻게 확인할 수 있나요 ?????
> 
> git remote 로 연결된 레포 주소 확인해주시면 될 것 같아요!

`git remote -v`

**Comment by 2taesung** [comment]
![remote 에러 스샷](https://github.com/githru/githru-vscode-ext/assets/66891085/032b1b59-d05b-460d-a634-9bde42bfd0ac)

**Comment by 2taesung** [comment]
#465 issue와 연관된 버그로 #465 issue 해결시 함께 close 진행하겠습니다.
