### ISSUE TITLE
node summary 열고 닫을 때 속도 수정

### ISSUE THREAD

**Issue by KyuTae98** [githru/githru-vscode-ext#368]
요약을 열고 닫을 때 옆에 있는 요약본끼리의 열고 닫을 떄 속도 차이가 수정 필요 

https://github.com/githru/githru-vscode-ext/assets/79373803/87e6a884-ef78-4401-b278-d40714739d08

**Comment by 2taesung** [comment]
너무 좋네요!!!!! 꼭 속도를 빠르게 하기보다 프로필 있는 부분이랑 속도 sync 를 맞춰주면 너무 좋을 것 같습니다!!
