### ISSUE TITLE
commit-item 요소의 적절한 크기 선정

### ISSUE THREAD

**Issue by KKanghh** [githru/githru-vscode-ext#375]
#371 에서 commit-item을 한 줄로 출력되게 변경하면서 commit-id의 width를 고정 크기로 변경하였는데 vscode에서 확인하기 적합한 width, 또는 width의 적절한 범위를 설정하면 좋을 것 같습니다.

**Comment by yura0302** [comment]
다음 오프라인 미팅때 함께 의논해 보면 좋을것 같습니다 !

**Comment by ytaek** [comment]
6자리에 딱 맞게 이쁘게 해주세요~
