### ISSUE TITLE
commit message가 길어질 경우 표시되는 방법을 더 명확하게

### ISSUE THREAD

**Issue by KKanghh** [githru/githru-vscode-ext#376]
<img width="1728" alt="스크린샷 2023-08-02 오후 7 32 52" src="https://github.com/githru/githru-vscode-ext/assets/84486674/479afcd0-dd1c-4030-80e0-bc2265978685">

commit message가 길어져 표시되는 범위를 초과하는 경우 현재 ... 으로 표시되고 있는데 이를 더 잘 보여줄 수 있는 방법, 또는 hover 시에 더 잘 보여줄 수 있는 방법이 있다면 수정하면 좋겠습니다.

혹 좋은 아이디어가 있다면 댓글 달아주셔도 좋을 것 같습니다!

**Comment by KyuTae98** [comment]
hover도 좋고 더 보기 식으로 있어도 좋다고 생각합니다!!

**Comment by 2taesung** [comment]
hover 도 좋은 것 같고 저는 '더보기' 도 좋은 것 같아요!!!
