### ISSUE TITLE
[view] commit message 정렬 순서 변경

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#379]
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/a212ee83-025d-438d-8316-0196bcad3af2)

매세지와 요약 chart를 반대 시간순으로 정렬할 수 있는 기능이 있었으면 좋겠습니다!
메시지가 쌓이면 쌓일수록 '최신순'이 더 좋을 것이라고 생각되고 
작업을 할 때 아무래도 최신 메시지를 확인할 필요성이 매우 큰데 과거 메시지들이 화면을 차지하고 있어 UI 측면에서도 선택권을 주는게 좋을 것 같습니다!

**Comment by KyuTae98** [comment]
시간 순으로 commit을 볼 수 있게 하는 부분 매우 좋다고 생각합니다!!
