### ISSUE TITLE
Node summary detail에서 detail name을 항상 숨기기

### ISSUE THREAD

**Issue by rlaqltmxm** [githru/githru-vscode-ext#385]
> * Normal viewport
> 
> ![summary-tobe](https://user-images.githubusercontent.com/44524767/260232624-5a01ad3a-a481-4340-8fa2-3fcbde1166c7.JPG)

왠지 구현 해 놓으신 걸 보니, normal view보다는 아이콘만 있는 버전이 훨씬 깔끔할것 같은데,
상시로 아래처럼 하는것도 이 PR 이후에 고민해보시면 어떨까요? : -)

> ![summary-tobe-small](https://user-images.githubusercontent.com/44524767/260232630-b9f9076d-5046-419e-b10e-759cfa4d3724.JPG)
>

_Originally posted by @ytaek in https://github.com/githru/githru-vscode-ext/pull/384#pullrequestreview-1575965424_

**Comment by josuncom** [comment]
음 간단한 수정일 것 같은데 한 번 진행해볼까요??

**Comment by ytaek** [comment]
(아직 할당되지 않은 이슈입니다)
