### ISSUE TITLE
[engine, view, vscode] Test Case 작성 가이드 문서 작성

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#400]
각 모듈들의 Test Case 작성 가이드에 대한 문서 작성이 필요합니다.
모듈별로 이슈들을 등록한 다음에 같이 얘기해보면 좋을 것 같아요.

가이드가 fix가 되면, MD로 소스코드에 박아넣는 것도 좋을 것 같습니다.

**Comment by 2taesung** [comment]
#458 #457 view>unit test, view>e2e  작성 가이드 문서 이렇게 이슈를 쪼갰는데 괜찮을까요 ?????

**Comment by ytaek** [comment]
나누는 것 좋습니다~.

**Comment by ytaek** [comment]
@blan19 님, 해당 이슈 확인 부탁드립니다. 자세한 사항은 @2taesung 님께...
