### ISSUE TITLE
[view] e2e test(playwright) github actions(ci/cd)에  yml 파일 설정

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#402]
아직 테스트 시스템이 자리를 잡으면 github actions에 hook을 적절히 걸어 test들을 설정하는 이슈입니다!
성급하게 도입하면 진입장벽을 높이고 pr, merge 속도를 몹시 저하시킬 수 있어 적절한 도입 시기를 체크해봐야할 것 같습니다!

**Comment by ytaek** [comment]
해주세요~
