### ISSUE TITLE
[view] 새로고침시 나머지 배경 반투명 처리하기

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#414]
현재 새로고침시 BounceLoader가 중앙에 나와 로딩이 됩니다.
유저에게 현재 로딩 중이라는 것을 좀더 직관적으로 알려주기 위해 나머지 배경을 반투명하게 처리하면 UX상 좋을 것 같습니다.

![image](https://github.com/githru/githru-vscode-ext/assets/66891085/d39c7419-1890-4725-84b6-aead413eece9)

**Comment by KyuTae98** [comment]
오 좋은 의견입니다!!!
