### ISSUE TITLE
[engine]  classify similar keywords by commit Message type

### ISSUE THREAD

**Issue by blan19** [githru/githru-vscode-ext#435]
## Related Issue
#187
#416

## Content

현재 엔진에서 커밋 메세지를 분류하는 기준은 커밋 메세지 내 `CommitMessageTypeList`에서 지정한 커밋 타입 값이 존재하는가로 분류합니다. 

```javascript
// 현재 engine에서 사용하는 커밋 메세지 타입
const CommitMessageTypeList = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "pert",
  "refactor",
  "revert",
  "style",
  "test",
];
```

즉, 커밋 메세지가 `feat(engine): build stem & CSM based on passed branch name (#198)` 일 경우 커밋 메세지 타입은 `feat`로 분류됩니다.

하지만 커밋 메세지를 작성할 때 컨벤션이 따로 존재하지 않는 커밋들이 존재할 수 있습니다. 
이를 위해 커밋 메세지 타입에 포함될 수 있는 하위 키워드를 지정해, 커밋 메세지에 키워드가 포함된다면 그 키워드가 속해 있는 메세지 타입으로 분류 할 수 있을 것 같습니다

<img width="405" alt="githru-keyword" src="https://github.com/githru/githru-vscode-ext/assets/66871265/6e988709-e77b-4d7e-85a0-9ffbd004942c">

## Discussion

`add`와 `clean`같은 서로 다른 타입의 키워드가 같이 들어가 있는 커밋 메세지인 경우 처리를 어떻게 할지
-> default로 넘긴다?

**Comment by inthejim** [comment]
커밋 메세지 하나당 여러 개의 type을 가지는건 어떨까요? keyword들을 break 없이 다 돌아야 해서, 비효율적이려나요,,

**Comment by ytaek** [comment]
> 커밋 메세지 하나당 여러 개의 type을 가지는건 어떨까요? keyword들을 break 없이 다 돌아야 해서, 비효율적이려나요,,

커밋 하나당 여러개 type을 가지는 것도 좋을 것 같긴 합니다만.
그러면, 사용자에게 보여주는 화면을 위한 처리 같은것도 좀 고민해봐야 될 것 같구요.

적당한 디자인 제약이 있으면 뭔가 깔끔하게 더 돌아나는 경우가 많으니,
당분간은 커밋 1개당 1개의 타입만 가지게 하다가, 추후에 확장하는 방법도 괜찮을 것 같긴 하네요.

**Comment by ytaek** [comment]
#187 도 참고해주세요~

**Comment by ytaek** [comment]
혹시 끝나셨으면 닫아주세요~
