### ISSUE TITLE
[view] Read More를 클릭했을 때 height 고정되어 있는 현상

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#439]
Read More를 눌렀을 때 전체적인 높이가 늘어나서 한 눈에 모든 commit을 볼 수 있으면 좋겠습니다.
height가 고정되어 있어 답답하고 추후 큰 프로젝트에서 많은 커밋을 보는데 불편하리라 생각합니다.

- read more 클릭 전
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/461e416c-5462-4c43-9725-4e45c1fa3caf)

- read more 클릭 후 (height 고정)
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/35473b6e-1fb7-419b-ad01-91688eda872c)

**Comment by ytaek** [comment]
UI renewal 예정으로 close합니다.
