### ISSUE TITLE
[view] scss 모듈 도입

### ISSUE THREAD

**Issue by syoung125** [githru/githru-vscode-ext#445]
- scss 모듈을 사용하고 있지 않기 때문에 중복된 클래스명을 사용할 경우 예상치 못한 css가 적용될 수 있다.
- 클래스명에 B.E.M을 모든곳에서 사용하고 있지 않기 때문에, 충분히 발생할 수 있을 문제 일 것 같고 모듈을 적용할 경우 클래스명도 더 짧아져 코드 가독성도 좋아질 것 같다

**Comment by ytaek** [comment]
참, scss 도입도 중요 이슈이긴 합니다!! 
이슈 만들어주셔서 감사해요!!

해당 링크 discord에 올려서 논의 요청해보면 좋겠습니다!

**Comment by 2taesung** [comment]
scss 모듈로 분리 사용은 장단점이 있는 것 같습니다.
모듈 분리의 장점들은 잘 말씀해주셔서 단점으로는 

styles 처리를 해줘야함으로 코드상 지저분해지고 동적인 부분을 styles처리를 통해 제한되는 부분이 있다고 생각합니다.

현재 도메인별로 scss 파일이 분리되어서 프로젝트가 관리되고 있는데(재사용 없음)
이렇게 분리된 파일들도 다른 파일들에 영향을 주나요 ...? (질문 ...!)

**Comment by ytaek** [comment]
> scss 모듈로 분리 사용은 장단점이 있는 것 같습니다. 모듈 분리의 장점들은 잘 말씀해주셔서 단점으로는
> 
> styles 처리를 해줘야함으로 코드상 지저분해지고 동적인 부분을 styles처리를 통해 제한되는 부분이 있다고 생각합니다.
> 
> 현재 도메인별로 scss 파일이 분리되어서 프로젝트가 관리되고 있는데(재사용 없음) 이렇게 분리된 파일들도 다른 파일들에 영향을 주나요 ...? (질문 ...!)

저도 궁금합니당!

**Comment by syoung125** [comment]
@2taesung 논의 코멘트 기다렸는데 , 달아주셔서 감사합니다!

우선 styles 처리를 해줘야함으로 코드상 지저분해진다 -> 요것은 제가 제대로 이해를 못한 것 같습니다.
```js```

**Comment by 2taesung** [comment]
> @2taesung 논의 코멘트 기다렸는데 , 달아주셔서 감사합니다!
> 
> 우선 styles 처리를 해줘야함으로 코드상 지저분해진다 -> 요것은 제가 제대로 이해를 못한 것 같습니다..! 좀 더 설명 부탁드려도 될까요??
> 
> 참고로 module scss 도입으로 인한 코드 변경은 요정도 입니다!
> 
> Before
> 
> ```js
> import "./RefreshButton.scss";
> 
> <button className='refresh-button' />
> ```
> 
> After
> 
> ```js
> import classNames from "classnames/bind";
> 
> import styles from "./RefreshButton.module.scss";
> 
> const cx = classNames.bind(styles);
> 
> <button className={cx('refresh-button')} />
> ```
> 
> 두번째, 도메인별로 scss 파일이 분리되어있지만 만들어진 빌드파일을 보시면 <img alt="image" width="830" src="https://user-images.githubusercontent.com/39763891/265444674-161b99dc-882b-408c-af9b-a9dd5ad10cf4.png"> 결국 다른 파일에 있더라도, 하나의 css파일로 빌드되기 때문에 이 때 우연히 같은 이름의 클래스가 있다면 예상치 못하게 다른 파일의 스타일이 덮어씌워질 수도 있는 문제가 발생할 수 있습니다!
> 
> 이를 방지하기 위해 에어비앤비 B.E.M 타입 네이밍 규칙을 사용할 수 있는데, (ex) RefreshButton__icon--loading : [컴포넌트명]__[클래스명]--[특정 상태]) 저는 이 네이밍이 너무 길다는 생각이 들고, 현재 프로젝트에서 잘 지켜지고 있지 않다고 생각해서 더더욱 문제가 될 수 있다고 생각합니다.
> 
> scss 모듈을 도입하면 분리된 파일인 경우, 빌드시 클래스 네임 뒤에 유니크한 해시값이 붙기 때문에 다른 파일에서 중복된 네이밍이 사용되더라도 문제가 되지 않아 좋은 것 같습니다!

첫 번째로 말씀해주신 그 부분이 코드가 지저분해진다의 의미가 맞습니다! 
개인적인 취향일 수 있는데 아무래도 가독성이 떨어지고 어렵게 느껴지더라구요!

문제가 발생할 여지가 충분히 있군요. 뭔가 분명한 컨벤션이나 말씀해주신대로 모듈화가 필요한 것 같습니다.
하지만 모든 scss 파일들을 모듈화를 해야하다보니 대규모 공사가 필요하겠다느 생각은 드네요 ...

또 한편으로는 아직 프로젝트가 작을 때 후딱 공사 치뤄야 맞지 않나라는 생각도 들고 ...
몇가지 트레이드 오프가 존재하는 것 같네요 ..!

**Comment by ytaek** [comment]
오 tradeoff가 명백하군요.

저는 이전에 scss package 버전 관련 이슈가 있어서 애먹은 적이 있긴 한데 😃😺  
(scss가 c++로 된 모듈을 내부적으로 쓰는데 이전 버전에 뭔가 문제가 있었던 적이 있네요;;)

지금은 확실히 정리가 안되어서 무언가 필요한 상태인건 확실해보입니다.
꼭 필요하다면 한번 뒤엎는것도 괜찮을 것 같은데요,

styled component(css-in-js)와의 비교를 쪼~금만 더 해보고, 결정해서 이번에 진행해보면 어떨까요?

**Comment by syoung125** [comment]
@2taesung 아하! 아무래도 scss 보다는 추가해야할 코드가 몇 줄 늘어나긴 하죠ㅠㅠㅠ
그래서 저도 모든 scss파일을 모듈로 한번에 변경하는 것은 다른 분들 작업에도 영향을 많이 미칠 것 같아서 어려울 것 같다고 생각합니다.
새로 만드는 컴포넌트라도 scss 모듈로 점진적으로 수정하는 방향은 어떨까요??

@ytaek 오오 넵 한번 이부분도 논의하면 좋을 것 같습니다~! 
저는 개인적으로 둘 다 사용해 보았을 때 css-in-js를 사용하는 경우, 
각각의 요소가 특정 이름을 갖는 컴포넌트가 되기 때문에 시멘틱 태그가 한눈에 파악되지 않는 점이 조금 불편했습니다🤔 

- scss : `<p className="name" />` p 태그임이 명확
- css-in-js : `<Name />` styled component 내부를 확인해보아야 태그를 알 수 있음

추가로 [이 글](https://junghan92.medium.com/%EB%B2%88%EC%97%AD-%EC%9A%B0%EB%A6%AC%EA%B0%80-css-in-js%EC%99%80-%ED%97%A4%EC%96%B4%EC%A7%80%EB%8A%94-%EC%9D%B4%EC%9C%A0-a2e726d6ace6)에서는 css-in-js는 
- 런타임 오버헤드를 더하고
- 번들 크기를 늘리며
- 특히 SSR 및 컴포넌트 라이브러리를 사용할 때 버그를 초래할수 있는 부분이 훨씬 많다
라고 지적하고 있습니다 😢

반면에, css-in-js는 prop을 통해 조건적으로 스타일 주거나, js 변수를 사용하는 것이 자유로워서 이 점은 편했던 것 같습니다! 
하지만 scss에서도 css 변수(var(--color)) 또는 `$color`형태의 scss 변수로 충분히 대응 가능하다고 생각합니다 :)

따라서 저는 현재 상황에서 css-in-js로 전환하면 좋을 특별한 이점을 발견하지 못했는데요..!
이건 제가 css-in-js를 더 깊이 이해하고 사용해보지 못해서 그런 것일 수도 있을 것 같습니다ㅠㅠ 
그래서 이부분은 css-in-js를 잘 다뤄보신 다른분들의 의견도 궁금해요!!

**Comment by 2taesung** [comment]
> @2taesung 아하! 아무래도 scss 보다는 추가해야할 코드가 몇 줄 늘어나긴 하죠ㅠㅠㅠ 그래서 저도 모든 scss파일을 모듈로 한번에 변경하는 것은 다른 분들 작업에도 영향을 많이 미칠 것 같아서 어려울 것 같다고 생각합니다. 새로 만드는 컴포넌트라도 scss 모듈로 점진적으로 수정하는 방향은 어떨까요??
> 
> @ytaek 오오 넵 한번 이부분도 논의하면 좋을 것 같습니다~! 저는 개인적으로 둘 다 사용해 보았을 때 css-in-js를 사용하는 경우, 각각의 요소가 특정 이름을 갖는 컴포넌트가 되기 때문에 시멘틱 태그가 한눈에 파악되지 않는 점이 조금 불편했습니다🤔
> 
> * scss : `<p className="name" />` p 태그임이 명확
> * css-in-js : `<Name />` styled component 내부를 확인해보아야 태그를 알 수 있음
> 
> 추가로 [이 글](https://junghan92.medium.com/%EB%B2%88%EC%97%AD-%EC%9A%B0%EB%A6%AC%EA%B0%80-css-in-js%EC%99%80-%ED%97%A4%EC%96%B4%EC%A7%80%EB%8A%94-%EC%9D%B4%EC%9C%A0-a2e726d6ace6)에서는 css-in-js는
> 
> * 런타임 오버헤드를 더하고
> * 번들 크기를 늘리며
> * 특히 SSR 및 컴포넌트 라이브러리를 사용할 때 버그를 초래할수 있는 부분이 훨씬 많다
>   라고 지적하고 있습니다 😢
> 
> 반면에, css-in-js는 prop을 통해 조건적으로 스타일 주거나, js 변수를 사용하는 것이 자유로워서 이 점은 편했던 것 같습니다! 하지만 scss에서도 css 변수(var(--color)) 또는 `$color`형태의 scss 변수로 충분히 대응 가능하다고 생각합니다 :)
> 
> 따라서 저는 현재 상황에서 css-in-js로 전환하면 좋을 특별한 이점을 발견하지 못했는데요..! 이건 제가 css-in-js를 더 깊이 이해하고 사용해보지 못해서 그런 것일 수도 있을 것 같습니다ㅠㅠ 그래서 이부분은 css-in-js를 잘 다뤄보신 다른분들의 의견도 궁금해요!!

저는 css-in-js를 사랑하는 사람 중에 한명인데 css-in-js의 힘은 팀 전체의 정확한 컨벤션 공유를 통한 재사용성과 js와의 연계, 디자인 시스템으로 인한 색상 정의 등등이라고 생각합니다. githru에서는 장점을 활용할 여지가 많지 않아보여요! 

저는 각 잡고 다 한번에 도입 해버리는 것도 좋을 것 같습니다. 왜냐하면 지금 개발하는 것들만 모듈처리를 하자고 하면 이전거는 아무도 안할거 같거든요! ㅋㅋ ㅠ

**Comment by syoung125** [comment]
@2taesung 태성님 말씀대로 한번에 진행하지 않으면, 이전꺼는 레거시로 남아버릴 것 같긴하네유..ㅋㅋ큐ㅠㅠㅠ 요건 오늘 논의 되는 대로 작업해보겠습니다~!

**Comment by 2taesung** [comment]
해당 이슈는 9/5 오프라인 회의에서 모듈화 작업을 진행하는 것으로 결정됐습니다. 이전 코드 모두 포함해 scss 모듈화 작업을 진행하는 것으로 하겠습니다!
