### ISSUE TITLE
[view] e2e test(playwright) 기본 url 시나리오 공모

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#447]
![image](https://github.com/githru/githru-vscode-ext/assets/66891085/329588ad-57a2-4b0e-863e-8271f13415a4)

e2e test(playwright) 기본 url(Home 으로 지칭 ....? )에서 화면을 반드시 구성해야하는 (추후 변동이 없으리라 생각되는) 요소들
위와 동일한 조건으로 유저들이 액션을 취하는 시나리오 생각하되는 것들을 공모합니다!

**Comment by ytaek** [comment]
일단 기본 test 환경을 갖추는 것도 중요한 것 같습니다!

변화하고 있는 repo의 데이터를 쓴다면 일정한 테스트가 안될꺼라,
stub data로 사용할 수 있는 fake repo data 정도를 기본으로 여러가지(??) 셋팅이 되면 좋겠네요.

**Comment by 2taesung** [comment]
> 일단 기본 test 환경을 갖추는 것도 중요한 것 같습니다!
> 
> 변화하고 있는 repo의 데이터를 쓴다면 일정한 테스트가 안될꺼라, stub data로 사용할 수 있는 fake repo data 정도를 기본으로 여러가지(??) 셋팅이 되면 좋겠네요.

멘토님의 의견이 궁금합니다!
제 생각으로는 unit test는 각각의 파일의 함수, 컴포넌트들이 실행이 잘 됐는지, 정상인지, 에러가 작동하는지 하는 등의 로직을 검증하기 때문에 적재적소에 mocking 해서 검증하는게 맞다고 생각합니다!

하지만 e2e test의 경우 실제 유저 시나리오를 기준으로 하기 때문에 mocking 데이터를 하기보다 '유저의 스크린, 유저의 이벤트 등'에 의한 결과물 체크를 하는 것으로 생각합니다!

그렇기 때문에 e2e test는 mocking이 아닌 실제 데이터, 실제 서비스의 화면을 가지고 테스트하는게 맞지 않을까 라는 의견입니다!
제가 playwright 공식 홈페이지 가서 조금 살펴보는데 mocking data를 사용하는 api들에 대한 내용도 없는 것 같기도 합니다!!
https://playwright.dev/docs/api/class-playwright

**Comment by ytaek** [comment]
> > 일단 기본 test 환경을 갖추는 것도 중요한 것 같습니다!
> > 변화하고 있는 repo의 데이터를 쓴다면 일정한 테스트가 안될꺼라, stub data로 사용할 수 있는 fake repo data 정도를 기본으로 여러가지(??) 셋팅이 되면 좋겠네요.
> 
> 멘토님의 의견이 궁금합니다! 제 생각으로는 unit test는 각각의 파일의 함수, 컴포넌트들이 실행이 잘 됐는지, 정상인지, 에러가 작동하는지 하는 등의 로직을 검증하기 때문에 적재적소에 mocking 해서 검증하는게 맞다고 생각합니다!
> 
> 하지만 e2e test의 경우 실제 유저 시나리오를 기준으로 하기 때문에 mocking 데이터를 사용하기보다 '유저의 스크린, 유저의 이벤트 등'에 의한 결과물 체크를 하는 것으로 생각합니다!
> 
> 그렇기 때문에 e2e test는 mocking이 아닌 실제 데이터, 실제 서비스의 화면을 가지고 테스트하는게 맞지 않을까 라는 의견입니다! 제가 playwright 공식 홈페이지 가서 조금 살펴보는데 mocking data를 사용하는 api들에 대한 내용도 없는 것 같기도 합니다!! https://playwright.dev/docs/api/class-playwright

말씀하신 대로 실데이터 베이스로 TC를 만들 수 있으면 가장 좋은 것 같구요.
보통은 실데이터는 변경될 가능성이 있어서,  TC의 결과값이 바뀌게 되는 경우가 있기 때문에 fixture같은것들을 미리 만들게 됩니다.

데이터의 변화와 관계없이 TC를 만들 수 있는 시나리오라면 상관없는데,
데이터에 dependent 한 테스트는 어쩔 수 없이 `테스트를 위한 전용 환경`이 필요합니다.
예를 들어 CRUD를 하는 테스트인데, 실제 DB에다가 테스트를 하면 production 데이터에 영향을 미치니까요.
그런 의도에서의 테스트 환경 정도라고 생각하시면 될 것 같아요~.
