### ISSUE TITLE
engine, vscode, view 공통 type들에 대한 정리

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#464]
현재까지 나온 방법들로는
1. pacakages 계층에 common 폴더를 넣는다.
2. engine에서 빌드시 타입을 mapping 해서 view에 넘긴다.

관련 작업 issue
#363

**Comment by 2taesung** [comment]
> 

shared 도 후보 폴더명 중 하나였습니다!
어제 오프라인 회의를 통해 3번 engine, vscode, view 별도 관리 대신 명시적인 주석, jsdoc으로 결정 됐습니다!

**Comment by 2taesung** [comment]
view는 #363 issue와 연결해 작업 진행하겠습니다.
engine도 관련 issue를 comment 해주시고 해당 issue 닫아주시면 될 것 같습니다! @Zigje9

**Comment by ytaek** [comment]
restructuring 예정으로 우선 close 합니다.
