### ISSUE TITLE
[engine, vscode] githru domain 확장

### ISSUE THREAD

**Issue by blan19** [githru/githru-vscode-ext#465]
## Related Issue
#320 
#328 
#366 

## Content

현재 githru가 지원하는 도메인은 github가 유일합니다.
이에따라 기타 다른 도메인에 대한 지원이 필요합니다.

## Discussion

도메인 뿐만아니라 `https//${token}@github.com/${owner}..` 와 같은 remote 주소가 존재할 수 있습니다

**Comment by blan19** [comment]
@yangchoi #320 이슈가 이 이슈로 넘어왔습니다!
참고하셔서 진행하시면 될 듯 합니다 ㅎㅎ

**Comment by 2taesung** [comment]
#366 해당 버그도 해당 issue와 함께 해결하기로 결정됐습니다.
#366 issue에 가보면 상세한 설명이 있지만 요약하면 

기존 github 주소를 파싱하는 정규표현식에 github token이 끼어있을때 발생하는 에러입니다.

**Comment by 2taesung** [comment]
@yangchoi 효정님!!! 부탁드려요!!!

**Comment by yangchoi** [comment]
> @yangchoi 효정님!!! 부탁드려요!!!

확인 감사합니다! 주말에 한 번 확인해보겠습니다 🙇

**Comment by yangchoi** [comment]
@2taesung 
말씀해주신 부분 확인해보았습니다. 
#366 이슈가 해결되면 본 이슈도 close 되겠군요. 
확인해주셔서 감사드립니다 (_ _)

**Comment by 2taesung** [comment]
> @2taesung 말씀해주신 부분 확인해보았습니다. #366 이슈가 해결되면 본 이슈도 close 되겠군요. 확인해주셔서 감사드립니다 (_ _)

네네! 맞습니다! 연관된 이슈라서 해결해주시면 연쇄적으로 다다닥 닫힙니다! 부탁드립니다!!!!

**Comment by 2taesung** [comment]
@yangchoi 효정님! 혹시 주말에 작업이 진행 됐을까요!!! 🕵️‍♂️

**Comment by 2taesung** [comment]
@yangchoi 효정님! 많이 바쁘신가요?! 혹시... 진행 사항을 알 수 있을까요?! 
아무래도 제 프로젝트들에서 githru를 실제로 사용해보고 싶은데 해당 버그 때문에 사용하지 못해 빨리 해결됐으면 하는 바램이 있습니다!!!!
response 부탁드립니다!!!!!!!!!

**Comment by yangchoi** [comment]
> @yangchoi 효정님! 많이 바쁘신가요?! 혹시... 진행 사항을 알 수 있을까요?! 아무래도 제 프로젝트들에서 githru를 실제로 사용해보고 싶은데 해당 버그 때문에 사용하지 못해 빨리 해결됐으면 하는 바램이 있습니다!!!! response 부탁드립니다!!!!!!!!!

아이고 죄송해요 ㅠㅠ 본 이슈로 인해 #366 가 닫히는 것이군요. 저는 반대로 생각해서 제가 작업할 필요가 없다고 생각했습니다.
금일 저녁까지 이슈 좀 보고, 해결이 어려우면 말씀을 드릴게요. 기다리게 해드려 정말 죄송해요  🙇
