### ISSUE TITLE
[vscode] npm run build:all 시 vinyl 정의에 대한 에러 발생 이슈

### ISSUE THREAD

**Issue by yangchoi** [githru/githru-vscode-ext#483]
![image](https://github.com/githru/githru-vscode-ext/assets/48708746/c154c7bf-f397-4339-8660-1a68349a614d)
vscode에서 `npm run build:all` 시 이미지와 같이 vinyl 패키지에 대한 에러가 발생할 수 있다. 
그런 경우 타입 패키지를 설치하여 해결할 수 있다. 
`npm install @types/vinyl --save-dev`

**Comment by ytaek** [comment]
재현하지 못하여 우선 close 합니다.
