### ISSUE TITLE
commit.message에 Merge "Merge pull request #xx from..." 포함되는 문제

### ISSUE THREAD

**Issue by 2taesung** [githru/githru-vscode-ext#492]
ClusterGraphElement>cluster>commitNodeList의 맨 처음 value의 commit.message 에 merge 내용이 포함되어 있습니다.

UI상 우측 summary와 분리되어 있음으로 Merge message의 경우 위의 데이터 계층에서 부모로 올려 ClusterGraphElement or cluster에 속성 값으로 위치시키는게 맞을 것 같습니다.

![image](https://github.com/githru/githru-vscode-ext/assets/66891085/cfccf8af-5200-4cc3-94c7-056f5e78974c)

**Comment by ytaek** [comment]
> UI상 우측 summary와 분리되어 있음으로 Merge message의 경우 위의 데이터 계층에서 부모로 올려 ClusterGraphElement or cluster에 속성 값으로 위치시키는게 맞을 것 같습니다.

이게 잘 이해가 안가는데, 내일 오프라인에서 얘기해보실까요? ㅎㅎ

**Comment by 2taesung** [comment]
> > UI상 우측 summary와 분리되어 있음으로 Merge message의 경우 위의 데이터 계층에서 부모로 올려 ClusterGraphElement or cluster에 속성 값으로 위치시키는게 맞을 것 같습니다.
> 
> 이게 잘 이해가 안가는데, 내일 오프라인에서 얘기해보실까요? ㅎㅎ

사진에 설명(?) 추가했습니다!
