### ISSUE TITLE
PR 바로가기 링크 에러 케이스

### ISSUE THREAD

**Issue by ytaek** [githru/githru-vscode-ext#496]
<img width="617" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/88ad4674-6aac-4ad1-8ad6-a93d539521b4">

PR 링크 주위에 괄호가 있을 경우
https://github.com/githru/githru-vscode-ext/issues/#469)
로 연결됩니다.

**Comment by seungineer** [comment]
## 진행상황
- Bug fix 하였으나 수정한 파일이 많아 검토 후 커밋 예정
### 참고
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/a1b29010-15c4-4773-a5cf-8d7c3e90eade">

- `href`에 URL이 올바르게 입력된 것을 알 수 있음
- `${owner}/${repo}/issues/${number}` 형식으로 URL이 지정되나 `issues`든 `pull request`이든 github에서 `number`에 맞게 redirection 함

**Comment by ytaek** [comment]
> ## 진행상황
> * Bug fix 하였으나 수정한 파일이 많아 검토 후 커밋 예정
> 
> ### 참고
> <img alt="image" width="1095" src="https://private-user-images.githubusercontent.com/97353541/352865842-a1b29010-15c4-4773-a5cf-8d7c3e90eade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTkyODksIm5iZiI6MTcyMjM1ODk4OSwicGF0aCI6Ii85NzM1MzU0MS8zNTI4NjU4NDItYTFiMjkwMTAtMTVjNC00NzczLWE1Y2YtOGQ3YzNlOTBlYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE3MDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NmY0YmQwOTgyMjI3OWZiMjJhYjU4YjUzMTZjNDcxNTAzNjI4ZGM0NGRkMzYzMjM5ZmFkNWJiMjM0MDYzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHRJANZnoWN1ZMvcey1_pDH7W3HDe--jukLrcB7EzWM">
> * `href`에 URL이 올바르게 입력된 것을 알 수 있음
> * `${owner}/${repo}/issues/${number}` 형식으로 URL이 지정되나 `issues`든 `pull request`이든 github에서 `number`에 맞게 redirection 함

@seungineer 님, 일단 PR 올려주셔서 확인이 되면 더 좋을 것 같습니다.
수정한 파일이 부득이하게 많아졌을 경우라면, 중요 부분에다가 line by line comment들을 좀 달아주시면 리뷰 하시는 분들이 편할 때도 있습니다.

구조 변경(or refactoring)으로 인해 수정사항이 많아진 경우라면, 그 부분도 설명에 적어놔주시면 빠른 리뷰가 가능합니다!!
