### ISSUE TITLE
commit detail에 중복된 commit 이 들어가는 버그

### ISSUE THREAD

**Issue by inthejim** [githru/githru-vscode-ext#507]
![image](https://github.com/githru/githru-vscode-ext/assets/107672313/b6fe5e19-c41b-4b59-a26a-e0b32ecf4532)
commit 이 중복되게 들어가면서, 
중복된 commit 개수만큼 뒤의 commit들이 보이지 않음.
#492 연관

**Comment by ytaek** [comment]
오우!! 제가 순서 거꾸로 하면서 잘못 짰나보네요!!! 감사합니다!
