### ISSUE TITLE
git 연동이 안 된 프로젝트에서 무한로딩이 발생하는 증상

### ISSUE THREAD

**Issue by DaYoung-woo** [githru/githru-vscode-ext#520]
https://github.com/user-attachments/assets/f67ed41e-7356-4d4e-8a47-327054cf340e

깃  연동이 안된 프로젝트에서 githru를 실행시키면 무한 로딩이 발생합니다.
깃 연동이 안되어있어 그래프를 제공하기 어렵다는 안내가 표시되면 더 좋은 사용자 경험을 제공할 수 있을 것 같습니다.

**Comment by ytaek** [comment]
간단하지만, 매우 중요한 이슈인 것 같습니다!!
