### ISSUE TITLE
브랜치나 커밋이 많은 경우 느린 로딩 개선

### ISSUE THREAD

**Issue by choisohyun** [githru/githru-vscode-ext#522]
브랜치나 커밋이 많은 경우 전체 커밋을 가져오고 있어 로딩이 느린 모습인 것 같습니다. 인피니티 스크롤 등 빠르게 페이지 로딩을 할 수 있도록 개선해도 좋을 것 같습니다.

**Comment by ytaek** [comment]
(궁금) 인피니티 스크롤은 어떤 내용일까요?? 
virtual list 이런거랑 다를까요?

**Comment by kimdaeyeobbb** [comment]
인피니티 스크롤도 괜찮고 페이지네이션을 통해 해당 페이지 정보만 그때그때 가져오면 초기렌더링 시간 단축에 도움이 될거같아요

**Comment by ytaek** [comment]
#617 #512 에서 다루고 있어서 해당 issue는 close합니다
