### ISSUE TITLE
[view] Vertical Cluster List에서 여러 아이템 클릭 시, 열린 아이템의 authors 이미지들이 List 최상단에 제한없이 추가되는 현상

### ISSUE THREAD

**Issue by rakseong** [githru/githru-vscode-ext#524]
### 내용

- 여러가지 아이템을 open하였을 때  authors의 이미지가 클릭 순서에 따라 제한없이 쌓이는 모습을 보이고 있습니다.

### 재현

![image](https://github.com/user-attachments/assets/b592c53b-e20f-44a4-b2fc-ea46a4d2a757)

**Comment by HIITMEMARIO** [comment]
제가 해보겠습니다...!
