### ISSUE TITLE
글자 색 자동 변환 / change text color based on brightness

### ISSUE THREAD

**Issue by pcwadarong** [githru/githru-vscode-ext#528]
## 목적
명시성 확보

## 제안내용
배경 색이 어두울 때는 잘 보이지만, 배경 색이 밝을 때도 흰 글자색으로 고정되어 명시성이 떨어지는 문제가 있습니다. 배경 색의 명도에 따라 글자를 흰 색과 검은 색 중 자동으로 선택하여 표현할 수 있으면 좋을 것 같습니다.

![image](https://github.com/user-attachments/assets/8cf13efa-043a-43cb-88ef-34a1e7159a85)
![image](https://github.com/user-attachments/assets/be3ed105-6386-4bae-9436-4c69360d8f2c)

## 참고링크
https://miunau.com/posts/dynamic-text-contrast-in-css/

**Comment by ytaek** [comment]
558에서 해결된 내용이라 close해도 될 것 같습니다~.

(혹은 다른 모듈들에도 적용해보는 것도 좋을 것 같네요!)
