### ISSUE TITLE
[view] 커밋 링크 추가

### ISSUE THREAD

**Issue by joonwonBaek** [githru/githru-vscode-ext#534]
![image](https://github.com/user-attachments/assets/056016ff-2902-4f3c-a800-e17c0e627f35)

커밋 해시 코드를 클릭하면 github의 해당 커밋 내역 링크 페이지를 제공하여 코드 변경 사항을 보다 쉽게 파악할 수 있도록 개선해도 좋을 것 같습니다.

**Comment by ytaek** [comment]
좋습니다! 
혹은 vscode 내에서 관련 panel을 띄워도 좋을 것 같네요!!

**Comment by GBAJS754** [comment]
요거 아직 아무도 안하셨다면 제가 해볼게요!!🙋‍♂️

**Comment by joonwonBaek** [comment]
> 요거 아직 아무도 안하셨다면 제가 해볼게요!!🙋‍♂️

넵! 지금 커밋을 클릭하면 커밋 해시 코드가 복사되는데 그 부분 살려서 하셔도 좋을 것 같습니다

**Comment by seungineer** [comment]
#668 PR로 해결되어 해당 issue를 close합니다.
