### ISSUE TITLE
컬러 피커의 필요성, 컬러 적용 범위와 컬러 시스템 제안

### ISSUE THREAD

**Issue by pcwadarong** [githru/githru-vscode-ext#537]
사용자가 Githru를 이용할 때 메인 컬러를 컬러 피커를 통해 직접 지정할 수 있는 기능에 대해 말씀드리고자 합니다.

사용자가 Githru를 캡처하여 GitHub README나 Notion 등에 사용하고자 할 때, 세세한 색상 조절 기능이 있으면 프로젝트 문서의 통일성을 높이는 데 도움이 될 것입니다.

하지만 Githru가 주로 분석용으로 사용된다면, 사용자의 자율성보다는 가독성과 명시성을 우선하는 것이 더 중요하다고 생각합니다. 예를 들어, 사용자가 너무 라이트한 색상을 선택하면 글자의 가독성이 떨어질 수 있고, 너무 쨍한 색상은 시각적으로 자극적일 수 있습니다.

이 문제를 해결하기 위해, Githru의 메인 색상과 컬러 시스템을 정하여 이미지를 공고히 하거나, 미리 만들어둔 몇 개의 컬러 차트에서 사용자가 선택할 수 있도록 하는 것을 제안합니다. 예를 들어, VSCode는 각 단어의 종류에 따라 색상을 다르게 하여 구분하며, 이를 사용자가 마음에 드는 테마로 바꿀 수 있는 익스텐션을 제공합니다. 이처럼 미리 여러 색상을 정해두고 사용자에게 고르게 하는 방식을 고려해보면 좋을 것 같습니다.

또한, 사용자가 직접 색상을 선택하게 하면서 단일 색상 이상이 필요하여 적절한 색상 조합을 찾을 때 [ChatGPT를 이용하는 방법](https://medium.com/@bunny753358/chat-gpt-%ED%99%9C%EC%9A%A9%ED%95%98%EC%97%AC-%EC%BB%AC%EB%9F%AC-%ED%8C%94%EB%A0%88%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-75850283a1e6) 이 괜찮은 것 같아 찾아 보았습니다.

이전 첫 이슈로 색상에 대한 이야기와 vscode 테마 연동 등의 이야기가 나온 것처럼 보이는데 최종적으로 컬러피커가 도입된 이유가 궁금합니다!

**Comment by mdgarden** [comment]
개인적으로는 githru자체에서 몇가지 테마를 설정하여 기본 세트를 제공하는 방법이 좋을 것 같습니다.(미리 만들어둔 몇 개의 컬러 차트에서 사용자가 선택하는 방식)

사용자가 설정하고 있는 테마에서 직접 컬러를 자동으로 가져오는 것도 좋지만, 어제 멘토님이 말씀하신 내용을 포함해서 실제 구현에 많은 어려움이 있을 것 같습니다. 갠적으로 vscode 테마에 관심이 많아서 직접 만들어보려고 했었는데 생각보다 설정해야할 색상들이 굉장히 많고 테마의 포인트 색을 주는 곳도 다양했습니다.(예: 어떤 테마는 글자색에 테마 색을, 어떤 테마는 윈도 자체에 테마색을 배정) 

간단하게 vscode 테마를 만들 수 있는 사이트가 있으니 여기 한번 둘러보시는 것도 좋을 것 같습니다.
https://themes.vscode.one/

**Comment by ytaek** [comment]
아래처럼 여러가지 방법이 있을 것 같습니다.

- "이쁜" 하나의 테마로 변경 (사실 지금껀 별루죠? ㅋ)
- "이쁜" N개의 테마 제공 (자체적)
- vscode 테마와 자동 연계 (테마에 따라 githru도 알아서(?) 변화)

view팀 내부적으로 얘기를 해보고 방향을 결정해서 진행하면 좋을 것 같아요.
개인적으로 우선 순위 상위에 두고 싶은 주제 중 하나입니다 😸
