### ISSUE TITLE
[view / bug] 기간 선택 기능 개선, 새로고침 시 무한 로딩

### ISSUE THREAD

**Issue by BeA-Pro** [githru/githru-vscode-ext#539]
[view]
githru-vscode-ext는 기간 선택을 할 때 불편함이 있다고 생각합니다.

<img width="768" alt="스크린샷 2024-07-19 오후 12 44 01" src="https://github.com/user-attachments/assets/a58e9368-cda3-4013-a2fe-3692d8494927">

<img width="775" alt="스크린샷 2024-07-19 오후 12 43 50" src="https://github.com/user-attachments/assets/2f04de6b-741b-4bc8-a975-2b18b81f682a">

위 사진은 24-05-04 ~ 24-05-08 기간을 선택하기 위해 드래그를 하였으나 실제로는 24-05-04 ~ 24-05-07 기간만을 조회하고 있음을 보여줍니다.
커서를 그래프에 올렸을 경우 툴팁을 사용해 어떤 기간을 선택했는지 명시하였으면 좋을 것 같습니다. 또한, 드래그 방식보다는 클릭으로 시작점과 끝점을 선택하는 방식이 더 나은 방법이라고 생각됩니다.

[bug]

우측 상단에 새로고침 버튼을 누르면 무한 로딩이 되는 버그가 있습니다.

**Comment by lxxmnmn** [comment]
새로고침 시 무한 로딩 버그에 대해서는 #549 에서 다루면 좋을 것 같습니다!
