### ISSUE TITLE
[view] Total Commit 그래프에 마우스 호버시 깜빡임 현상 발생

### ISSUE THREAD

**Issue by mdgarden** [githru/githru-vscode-ext#540]
## 상세 내용
다음과 같이 특정 커밋을 선택하여 Total Commit의 그래프에 마우스 호버시, 지속적인 깜빡임이 발생합니다.

## 발생 환경
- Mac M3 Air

https://github.com/user-attachments/assets/6669b852-12bc-4a80-bce3-05b3c0046a7d

**Comment by seungineer** [comment]
해당 issue는 #550 , #559 를 통해 해결되어 Close 합니다.
