### ISSUE TITLE
리드미 contributors 인원 일치하지 않는 문제

### ISSUE THREAD

**Issue by yuiseo** [githru/githru-vscode-ext#547]
## 문제 상황
리드미의 contributors 인원이 일치 하지 않습니다.
![image](https://github.com/user-attachments/assets/9009ebec-0c86-4398-af27-95ba05d14397)
![image](https://github.com/user-attachments/assets/80f7f603-d98f-4cc4-bb72-0bb7410a1597)

## 해결 방법
23명으로 하드코딩 된 인원 배지 코드를 교체합니다.
다음 링크 api를 통해 레포지토리의 contributors를 보여줍니다.
https://shields.io/badges/git-hub-contributors

**Comment by ytaek** [comment]
앗. 뱃지 숫자가 하드코딩이었군요;;; 
이건 빠르게 수정할 수도 있겠습니다.
(뱃지를 아예 빼버려도 괜찮을 듯)

**Comment by yuiseo** [comment]
@ytaek 리드미 하단에 이미 컨트리뷰터가 존재하기 때문에 중복되는 정보이므로 배지를 제거해 보도록 하겠습니다!

**Comment by yuiseo** [comment]
closes
