### ISSUE TITLE
view page 상단 그래프 전체 기간에서 특정 기간으로 Brushing 후 원복 시 UX 개선

### ISSUE THREAD

**Issue by seungineer** [githru/githru-vscode-ext#551]
## 상세 내용
다음과 같이 조회하고자 하는 기간을 Brushing 후 다시 전체 기간 조회로 돌아가고자 할 때 그래프를 한 번 클릭해야 합니다.
클릭 시 전체 기간으로 돌아가는 UX가 직관적이지 않아 개선이 필요하다고 생각합니다.

## 참고
![브러싱](https://github.com/user-attachments/assets/bd71a696-9efc-467b-aacd-a19b300a2739)

**Comment by ytaek** [comment]
d3에서 brushing하는 예제들에서 많이 사용되는 ux인데, 두 번 리포트 될 정도로 불편한 이슈인가보군요!!! report 감사합니다!
해당 temporal filter기능을 하는 차트 부분은 제가 급하게 진행했었는데,
원래 reset 버튼을 좌측 위에 달까 했었는데, ... 못 생기게 나와서 일단 생략했습니다 🥲🥲🥲🥲🥲 

직관적인 방향으로 재설계 되면 좋겠습니다!
