### ISSUE TITLE
커밋 메시지가 긴 경우에 Author 프로필 이미지 비율이 깨짐

### ISSUE THREAD

**Issue by yoouyeon** [githru/githru-vscode-ext#552]
## 문제 상황

아코디언 목록 안쪽의 커밋 메시지 길이가 길어지면 author의 프로필 이미지가 작아져 거의 직선으로 보입니다. (hover하지 않은 경우에도 최소 너비를 지정해야 할 것 같습니다.)
또한 원형의 1:1 비율이 깨지면서 이미지 뒤쪽 흰색 배경이 그대로 보입니다.

## 스크린샷

길이가 긴 커밋 메시지 목록에서 author 프로필 이미지가 너무 작은 화면

<img width="1198" alt="Screen_Shot 2024-07-23 01 42 06" src="https://github.com/user-attachments/assets/1e185bab-94f2-4d5b-8cde-06bef61d80ad">

이미지 뒤쪽 흰색 배경이 보이는 화면
<img width="1197" alt="Screen_Shot 2024-07-23 01 48 26" src="https://github.com/user-attachments/assets/a629b6fa-5c67-4556-a720-0310a77fa16f">

**Comment by ytaek** [comment]
아!! 이게 커밋 메시지 길이 때문에 생기는 이슈였군요!!

**Comment by seungineer** [comment]
@lxxmnmn 님,

해당 이슈 계속 발생하여 reopen 해주셨나요?!
제 환경(확장 개발 호스트 및 dev 모드 실행 기준)에선 해결된 걸로 보여 close 했었거든요 😅

확인 한 번 해주시면 감사하겠습니다~!

**Comment by lxxmnmn** [comment]
@seungineer 

엇 그렇네요...!
UI 리뉴얼 팀 태스크 할당하는 과정에서 해당 이슈를 다룬 pr이 없는 것만 확인하고 reopen 했었습니다 😅😅
제 환경에서도 발생하지 않고 있어서 다시 close 하겠습니다!
