### ISSUE TITLE
일자별 커밋그래프 일부 선택 이후 전체 그래프를 보기 위한 경로가 직관적이지 않음

### ISSUE THREAD

**Issue by pithesun** [githru/githru-vscode-ext#555]
이슈내용 : 일자별 커밋그래프 일부 선택 이후 전체 그래프를 다시 보기 위해서 더블클릭 혹은 새로고침을 통해서만 가능하여, 처음 githru를 사용할 때 혼란을 줄 수 있음.

재현경로 : githru-view > 드래그 하여 일부 그래프 선택

기대사항: 일자별 커밋그래프 일부 선택 이후 전체 그래프를 다시 보기 위한 안내 혹은 직관적인 UI 제공

<img width="864" alt="image" src="https://github.com/user-attachments/assets/b0d20ad5-2732-4382-8238-8365de7faf02">

**Comment by rakseong** [comment]
#551 이슈와 유사한 내용인거 같습니다 : )

**Comment by ytaek** [comment]
d3에서 brushing하는 예제들에서 많이 사용되는 ux인데,
두 번 리포트 될 정도로 불편한 이슈인가보군요!!! report 감사합니다!

#551 에서 진행하는 걸로 하고, 해당 이슈는 close 하겠습니다.
