### ISSUE TITLE
githru-vscode-ext 전체 레포를 vscode에서 열었을 경우, tsconfig 파일의 경로가 잘못되어 에러가 발생함

### ISSUE THREAD

**Issue by mdgarden** [githru/githru-vscode-ext#557]
## 에러 내용
githru-vscode-ext 전체 모노레포를 vscode에서 오픈하면 각 패키지 내부에서 린트 에러가 발생합니다.

## 상세 내용
각 패키지의 ts파일 첫째줄에서 공통적으로 다음과 같은 에러가 발생합니다.
`Parsing error: Cannot read file '/users/madang/documents/opensource/githru-vscode-ext/tsconfig.json'.eslint`
각 패키지 별도로 vscode를 열었을 경우에는 에러가 발생하지 않습니다.

**Comment by choisohyun** [comment]
머지된 이슈로 close합니다!
