### ISSUE TITLE
credentials octokit 관련 중복 코드 개선

### ISSUE THREAD

**Issue by bbanderson** [githru/githru-vscode-ext#561]
### 문제 상황
`packages/vscode/src/credentials.ts`의 getOctokit과 getAuth 메서드 각각에 중복된 코드가 있습니다.

<img width="919" alt="스크린샷 2024-07-26 오후 9 27 19" src="https://github.com/user-attachments/assets/fd2ef879-2c09-4018-b763-b79782e7cbd2">

### 해결 방법
공통 로직을 추상화 하면 될 것 같습니다.

**Comment by choisohyun** [comment]
머지된 이슈여서 close합니다!
