### ISSUE TITLE
[view] 커밋 메세지가 긴 노드를 클릭 시 우측 그래프 표시 레이아웃이 무너짐

### ISSUE THREAD

**Issue by mdgarden** [githru/githru-vscode-ext#563]
## 버그 내용

커밋 메세지가 긴 노드를 클릭하면 레이아웃이 무너집니다.
#552 와 비슷한 내용이나, 발생 영역이 달라 별도 이슈로 작성하였습니다.

## 상세 내용
- 커밋메세지가 길어지는 경우, 길어지는만큼 우측의 그래프 표시 영역이 줄어듭니다.
- 줄어든 그래프 표시 영역만큼, 우측 하단의 수정 파일 표시 그래프의 비율이 줄어듭니다.

https://github.com/user-attachments/assets/33c61054-cde8-443a-b534-3e3d80d3ffc6

**Comment by ytaek** [comment]
꼼꼼한 이슈 발견 감사합니다!! 👍
