### ISSUE TITLE
그래프 상에 현재 선택된 pr 정보 명확히 노출

### ISSUE THREAD

**Issue by hhbb0081** [githru/githru-vscode-ext#564]
![스크린샷 2024-07-28 173204](https://github.com/user-attachments/assets/31ffd892-8fcf-4cb9-9e37-b8a4af04fb99)

여러 개 선택 시 현재 선택한 pr에 대한 정보가 그래프밖에 존재하지 않아 헷갈릴 것 같습니다.
그래프 영역에 현재 선택한 pr의 정보를 제목 정도만 간단히 노출시키는 것이 좋을 것 같습니다.

**Comment by ytaek** [comment]
selection 관련해서 생각해볼게 많을 것 같은데, 좋은 이슈 잡아주셨네요.
이 건은 UI renewal 하고 같이 연관지어서 얘기해보면 좋을 것 같습니다!

**Comment by seungineer** [comment]
#664 , #676 PR에서 해결되어 close합니다.
