### ISSUE TITLE
[view] 사용자 정보 클릭시 해당 계정 페이지로 이동

### ISSUE THREAD

**Issue by kimdaeyeobbb** [githru/githru-vscode-ext#571]
<img width="818" alt="image" src="https://github.com/user-attachments/assets/dd9c137d-4687-43b8-9e05-2242095ac02b">
 
- 커밋 메시지 오픈하고 나서 보이는 사용자 정보 클릭시 해당 계정 페이지로 이동하게 만드는 기능이 있으면 유저 파악에 용이할 것 같아 제안합니다.

**Comment by choisohyun** [comment]
머지된 것으로 보여 닫겠습니다!
