### ISSUE TITLE
[view] 용도에 맞게 포인터 설정

### ISSUE THREAD

**Issue by jkea1** [githru/githru-vscode-ext#580]
각각의 요소마다 해당 요소에 해당하는 hover시의 포인터들이 있는데 뒤죽박죽으로 섞여 있는 것 같습니다. 
클릭기능이 있는 요소, 텍스트 등 해당 요소에 맞는 pointer를 설정합니다.

**Comment by seungineer** [comment]
그래프에 커서 hover 시 피드백이 뒤죽박죽이네요.
어떤 그래프를 어떻게 수정하면 좋을지 논의가 필요할 것 같습니다.

구체적인 논의, 피드백이 필요할 것 같아 Discussion 태그 달아두겠습니다!

**Comment by jkea1** [comment]
해결된 것 같아 이슈를 닫겠습니다! 👍
