### ISSUE TITLE
[view] 커밋이 하나도 없는 경우 화면 수정 논의

### ISSUE THREAD

**Issue by xxxjinn** [githru/githru-vscode-ext#584]
### 커밋 기록이 하나도 없는 경우 

- 현재는 text만 띄워주고 있습니다.
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/b8e0941a-eb5b-4197-b4c1-d127ca609671">

<br/>
<br/>

- 간단하게라도 큰 아이콘(예를 들면 githru의..?) + 텍스트가 함께 보이도록 하는 건 어떻게 생각하시는지 다른분들의 의견이 궁금합니다! (큰 아이콘+텍스트의 느낌 참고용으로 사진 첨부합니다.)
![image](https://github.com/user-attachments/assets/4de2b8c5-9cd8-4752-8d9f-baca9dfab92e)

**Comment by seungineer** [comment]
현재 text만 띄어 커밋이 없다고 알려주는 부분이 아쉬운 것 같아요 ! 🙌

상단 CLOC, COMMIT # 차트 하단에 큰 이미지와 함께 `NO COMMIT EXISTS` 가 중앙 정렬되어 표시되면 좋을 것 같네요 👍👍👍 
상단 차트 없이 이미지 + 텍스트만 보여도 좋을 것 같구요!

어떤 이미지가 적합할지 다른 분들의 의견 여쭙습니다 🤔 ㅎ ㅎ

**Comment by xxxjinn** [comment]
> 현재 text만 띄어 커밋이 없다고 알려주는 부분이 아쉬운 것 같아요 ! 🙌
> 
> 상단 CLOC, COMMIT # 차트 하단에 큰 이미지와 함께 `NO COMMIT EXISTS` 가 중앙 정렬되어 표시되면 좋을 것 같네요 👍👍👍 상단 차트 없이 이미지 + 텍스트만 보여도 좋을 것 같구요!
> 
> 어떤 이미지가 적합할지 다른 분들의 의견 여쭙습니다 🤔 ㅎ ㅎ

의견 정말 감사합니다!! 상단의 차트는 어차피 커밋이 없다면,, 빈 차트가 나오게 될 것 같아서 기능적으로는 문제가 없을 것 같은데 화면에서 없어지면 너무 허전해지지는 않을까 하는 생각이 들었습니다...!! 이것도 다른 분들 의견이 궁금하네욥

**Comment by Sang-minKIM** [comment]
githru 아이콘 예쁜데 이런 곳에 써도 좋을 것 같아요 가운데에 커다랗게 githru 아이콘과 함께 text로 커밋이 없다고 알려주면 어떨까요?

**Comment by pcwadarong** [comment]
오 좋습니다! 이렇게 하면 어떨까요?
![Group 27920](https://github.com/user-attachments/assets/6ce877ce-4477-4911-82df-8b7b7a128103)
![Group 27921dsf](https://github.com/user-attachments/assets/8cec7174-2590-4d1a-b0e8-c2c14c8ee0eb)

**Comment by lxxmnmn** [comment]
@pcwadarong 우와 시안 감사합니다!!! 저는 두번째가 조금 더 예뻐보여요 😲👍👍

**Comment by seungineer** [comment]
@pcwadarong 저도 두 번째 시안이 아이콘에 색이 없어서 Not Found 느낌이 더 많이나고 예쁜 거 같아요 ! 👍👍👍👍

**Comment by xxxjinn** [comment]
> 오 좋습니다! 이렇게 하면 어떨까요? ![Group 27920](https://private-user-images.githubusercontent.com/86795558/354994683-6ce877ce-4477-4911-82df-8b7b7a128103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTEwMjksIm5iZiI6MTcyMjg1MDcyOSwicGF0aCI6Ii84Njc5NTU1OC8zNTQ5OTQ2ODMtNmNlODc3Y2UtNDQ3Ny00OTExLTgyZGYtOGI3YjdhMTI4MTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5Mzg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZjE3ODMzYWYwM2U2MDlhNTNkNmEzMzNjNGM3Zjc4NDA1NWFiNGM0ODYxNzBjMDAwYjc0NmJkZDRkMjhjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BoFt6txHHNgHmO6DmYMmQ1ZW5Pw1I-7SmAO4eQPQLO0) ![Group 27921dsf](https://private-user-images.githubusercontent.com/86795558/354994691-8cec7174-2590-4d1a-b0e8-c2c14c8ee0eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTEwMjksIm5iZiI6MTcyMjg1MDcyOSwicGF0aCI6Ii84Njc5NTU1OC8zNTQ5OTQ2OTEtOGNlYzcxNzQtMjU5MC00ZDFhLWIwZTgtYzJjMTRjOGVlMGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5Mzg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzM0MmVlNTMwNTY2ZDYwNzE4OGY5MjlmOTEwNmQyMWY1YTIxZmE5NDRlZTE1MzdlZGFmYjFiOTU1ZTA4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xhbpok-SlB0gzxckLu1V5AM03tb3LyBMGy91e-FNlR4)

저도 두번째가 좋은 것 같아요!
