### ISSUE TITLE
[view] 커밋 문자열의 issue number가 텍스트와 붙어 있는 경우 issue number로 인식하지 않는 버그

### ISSUE THREAD

**Issue by seungineer** [githru/githru-vscode-ext#590]
### 문제 상황
<img width="494" alt="image" src="https://github.com/user-attachments/assets/9fa87b55-fdb5-4b16-8daf-540058332721">

위 이미지와 같이 commit 메시지 내 issue number가 앞 단어에 붙어 있는 경우 issue number로 인식하지 않는 버그가 있습니다.

**Comment by seungineer** [comment]
어떤 단어에 붙은 `#{number}`의 경우 PR이나 Issue 넘버가 아닐 수 있어서 지금처럼 되어 있는 것이라면 수정할 필요가 없을 것 같습니다.

의견 여쭙습니다! 🤔🙋‍♂️

**Comment by yoouyeon** [comment]
깃허브에서 `#`를 입력하면 이슈나 PR을 참조할 수 있게 목록이 뜨는데요!  텍스트 바로 뒤에 `#`를 입력하는 경우에는 목록이 뜨지 않고 띄어쓰기 이후에 #를 입력해야만 목록이 뜨더라구요.

<img width="724" alt="Screen_Shot 2024-08-04 15 47 07" src="https://github.com/user-attachments/assets/c3bbf51e-4d4d-41a1-8287-10b539331878">
<img width="724" alt="Screen_Shot 2024-08-04 15 47 12" src="https://github.com/user-attachments/assets/531232da-2701-4e59-a500-838b07788bcc">

이런 것을 보면 개인적으로는 말씀하신
> 어떤 단어에 붙은 #{number}의 경우 PR이나 Issue 넘버가 아닐 수 있어서 지금처럼 되어 있는 것

이 맞을 수도 있겠다는 생각이 듭니다 🤔

**Comment by seungineer** [comment]
> > 어떤 단어에 붙은 #{number}의 경우 PR이나 Issue 넘버가 아닐 수 있어서 지금처럼 되어 있는 것
> 
> 이 맞을 수도 있겠다는 생각이 듭니다 🤔

오 😲 그러네요! **Github에 말씀주신 규칙이 있으니 지금처럼 parsing되는 게 맞을 것** 같네요~
의견 감사합니다 👍👍👍👍

이에 본 issue는 Close as not planned 하겠습니다 🔥
