### ISSUE TITLE
이슈 템플릿 적용 논의

### ISSUE THREAD

**Issue by yoouyeon** [githru/githru-vscode-ext#598]
## 요약

이슈 유형에 맞는 이슈 템플릿을 만들어서 좀 더 일관된 형식으로 이슈를 만들 수 있으면 좋을 것 같습니다.

## 내용

아직까지는 약속된 이슈 템플릿이 없어 자유롭게 이슈를 올리고 있는데요.
이슈 생성자와 이슈 작업자가 다른 경우가 종종 있기 때문에 가능하면 이슈를 잘 라벨링하고 자세하고 한눈에 알아보기 좋게 적는 것이 중요한 것 같다는 생각이 들었습니다.
다들 나름대로의 방법으로 알아보기 좋게 올려주시고 있지만 실제 작업자가 필요로 하는 정보는 또 다를 수 있기 때문에
기능 제안 / 버그 제보 / 논의 사항 같은 유형의 이슈들에 들어가면 좋을 항목들을 논의하고, 템플릿화 하는 것이 어떨지 논의해보고 싶습니다!

## 참고

다른 오픈소스 프로젝트들에 설정되어있는 이슈 템플릿들입니다.

- https://github.com/huggingface/transformers/issues/new/choose
- https://github.com/argoproj/argo-cd/issues/new/choose
- https://github.com/yorkie-team/yorkie/issues/new/choose

**Comment by choisohyun** [comment]
유형 별로 나누고 기본 템플릿 넣어주는 것 너무 좋습니다! 👍 그런데 이슈 템플릿 설정페이지가 안보이는데 권한을 받아야 하는 걸까요 🤔

**Comment by yoouyeon** [comment]
엇 미처 설정페이지를 확인해보진 못했는데 정말 설정 페이지가 안보이네요...?? 근데 이슈 템플릿은 설정 페이지 말고도 파일로도 직접 올릴 수 있는 것으로 알고 있어서 파일로 직접 올린다면 설정할 수 있지 않을까 싶기도 합니다.. 🤔

**Comment by choisohyun** [comment]
아 그러네요 폴더 만들어서 올리면 똑같군요!

**Comment by joonwonBaek** [comment]
이슈 유형에 맞는 이슈 템플릿 만드는거 너무 좋아요!!
기존 템플릿이 구체적이지 않아서 이슈를 한눈에 알아보기 힘들었어요😅

**Comment by ytaek** [comment]
오 이슈 템플릿 좋습니다!!!
