### ISSUE TITLE
[vscode] webview-loader 코드 분리

### ISSUE THREAD

**Issue by DaYoung-woo** [githru/githru-vscode-ext#599]
webview loader쪽도 
engine을 실행하는 부분, vscode와의 interface를 선언하는 부분, webview를 만들어서 react view app을 띄우는 부분 등으로 
관심사 분리를 해놓는게 필요할 것 같습니다.

@DaYoung-woo 님, 해당 내용 새로 이슈로 등록하시고, 추후에 진행해보셔도 좋을 것 같습니다 : )

_Originally posted by @ytaek in https://github.com/githru/githru-vscode-ext/pull/577#discussion_r1700568467_

**Comment by BeA-Pro** [comment]
다영님 혹시 이 이슈 제가 해결해도 괜찮을까요?

**Comment by DaYoung-woo** [comment]
@BeA-Pro 엇 혹시 해결하셨나용...? 저희 지금 수정하려고 디코에 모여있습니다!

**Comment by DaYoung-woo** [comment]
#643 엔진팀 내부에서 협의한 뒤 진행하는 것이 좋을 것 같아 롤백하였습니다
