### ISSUE TITLE
[view] : error npm run build:bundle

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#60]
in .github/workflow/ci.yml

- run: npm run build:all --if-present

this is throw an error

---

npm run build:all 
=> [*:package.json] => "build:all": "npm run build --workspaces",
=> [view] "build:bundle": "webpack --config webpack.config.js",
=> error
=> Can't merge

---

We have to fix the error.

How to solve this error?

**Comment by hanseul-lee** [comment]
build 오류 해결해 해당 이슈 close 하겠습니다.
