### ISSUE TITLE
[view] dev 모드 실행 시 에러 발생

### ISSUE THREAD

**Issue by seungineer** [githru/githru-vscode-ext#603]
### 문제 상황
#569 PR merge 이후 부터 dev 모드 실행 시 아래 이미지와 같은 에러가 발생하고 있습니다.

- 에러 이미지

<img width="750" alt="image" src="https://github.com/user-attachments/assets/e42b18f0-a6cf-4c38-8a67-a9c50e6b374c">

- 에러 발생 양상

![포스트메시지에러](https://github.com/user-attachments/assets/042f45c3-abc9-4eee-99a5-34dcbee0feab)
위 이미지처럼 에러가 순차적으로 생성되며 쌓이는 것을 봤을 때 이슈 넘버가 포함된 커밋을 처리할 때마다 에러가 발생하고 있는 것 같습니다.

### 참고
- #588 이슈 해결 시 dev 모드 실행 환경도 고려해야겠습니다.

**Comment by ytaek** [comment]
@seungineer #604 로 해결된 것 맞을까요?
맞다면 close 부탁드립니다~

**Comment by seungineer** [comment]
> @seungineer #604 로 해결된 것 맞을까요? 맞다면 close 부탁드립니다~

네 맞습니다!
#604 로 해결되어 Close하겠습니다.
