### ISSUE TITLE
[view] 우측 차트 잘림 현상

### ISSUE THREAD

**Issue by HIITMEMARIO** [githru/githru-vscode-ext#606]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/d056a1e6-6f3c-4f31-863b-976e378097ba">
<img width="348" alt="image" src="https://github.com/user-attachments/assets/31310003-18bf-42fd-a204-42e98d071b0a">

width값이 %로 변경 되면서 우측 차트가 잘리는 문제가 생긴거 같습니다!!

**Comment by joonwonBaek** [comment]
아... 제가 변경된 부분을 `pull` 하지 않고 테스트해서 이런 문제가 발생한거 같네요 ㅠㅠ

**Comment by ytaek** [comment]
@HIITMEMARIO 예리한 테스트 항상 감사합니다!!


> 아... 제가 변경된 부분을 `pull` 하지 않고 테스트해서 이런 문제가 발생한거 같네요 ㅠㅠ
@joonwonBaek push 하시기 전에, 혹은 개발중에도 항상 upstream pull 하시면서 개발하시는게 좋긴 합니다 😄

**Comment by HIITMEMARIO** [comment]
> 아... 제가 변경된 부분을 `pull` 하지 않고 테스트해서 이런 문제가 발생한거 같네요 ㅠㅠ

혹시 이슈 수정 중이실까요?!
