### ISSUE TITLE
node version upgrade

### ISSUE THREAD

**Issue by pcwadarong** [githru/githru-vscode-ext#610]
#609 
여기서 제가 처음 세팅할 때 `npm i`를 하니 node 버전이 업그레이드 되어서, 혹시 특정 버전을 사용하는 걸까싶어서 다시 원상 복귀 (수동으로) 해놓앗는데 그 과정에서 오류가 생긴 것 같습니다.

**npm i를 하면 생기는 변화**

![image](https://github.com/user-attachments/assets/dcf1a109-e93c-4df1-861c-8ead07e51c29)

이에 따라 영택님 말씀대로 node.버전을 올리려고 합니다.

**Comment by ytaek** [comment]
참고로 node 버전올리실 때, .github에 있는 CI 내용도 같이 업데이트 해주셔야 합니다 👿👿

**Comment by pcwadarong** [comment]
@ytaek 전혀 모를 뻔 했는데 감사합니다 ㅎㅎ 둘다 업데이트하였습니다!

**Comment by pcwadarong** [comment]
PR 성공!
