### ISSUE TITLE
[engine] 엔진 성능 최적화 현 상황 보고 및 개선방안 논의

### ISSUE THREAD

**Issue by BeA-Pro** [githru/githru-vscode-ext#621]
## 1. 현 상황
- 모든 git 데이터를 한번에 불러오고 있음
- engine 테스트 시, getGitLog 함수에서 작업 시간이 많이 소요되고 있음
(ex. 40,000개 정도의 커밋 처리시 6분 정도 소요)

## 2. 문제 의식
- 모든 git 이력을 한 번에 불러올 필요성에 의문이 듦
→ 익스텐션을 사용하는 유저가 제공받고 싶은 효용에 초점을 맞춘다면,
한번에 모든 데이터를 보여줄 필요는 없다고 생각이 됨
(해당 익스텐션을 사용하는 유저가 모든 히스토리를 한번에 알고 싶기 보단,
최근 데이터부터 시작하여 추적하는 것이 더 일반적인 사용법이라고 생각 됨)
- 최근 데이터 기준으로 일정량의 데이터를 보여준 후, 유저가 요청했을 때
추가적인 데이터를 보여주는 것이 보다 더 맞지 않을까 생각 됨

## 3. 개선 방안
- 근본적인 해결 방안
→ git 데이터를 처리하는 작업 시간 자체를 효율화 하는 것 (getGitLog 함수 처리 효율화)
- 우선적으로 접근할 수 있는 부분
→ 2번의 문제 의식을 고려하여, 데이터를 일정량씩 나눠서 제공하는 방안 마련
- 우선적으로 데이터를 나눠서 제공하는 방안을 마련하고, 
이후에 데이터를 처리하는 함수 성능을 효율화 하는 것이 보다 더 접근하기 쉬운 방법으로 생각 됨

## 4. 이슈 진행 시 문제가 예상되는 부분
- 데이터를 적게 제공할 경우, 유의미한 CSM을 생성할 수 있는지 여부
→ 현재는 루트 데이터부터 모든 git 데이터를 불러와서 CSM을 생성하고 있음
→ 바뀐 방법 (최신 데이터부터 일정량 제공 후, 요청 시 추가 제공) 을 적용할 경우, 더 적은 양의 데이터로 CSM을 구성하게 됨
→ CSM을 통해 유저가 제공받는 정보가 적어지게 되는데, 이것이 사용성을 저해하지 않을지 고민 됨

## 5. 확인이 필요한 부분
- 최대로 수용 가능한 git 데이터 체크
→ 현재 로직을 기반으로 했을 때, 몇개의 git 데이터를 처리했을 시 사용성에 저해가 발생하지 않을지 체크
(ex. 유저가 10초 정도를 기다리는 정도는 괜찮다고 보여지므로, 10초 동안 처리할 수 있는 git 데이터가 몇개인지 체크)
- 최대 수용 가능한 git 데이터 기반으로 CSM 을 생성할 시, 유의미한 데이터인지 체크
→ 1번을 통해 확인한 최대 git 데이터 기반으로 CSM을 생성했을 때,
해당 CSM을 통해 유저에게 유의미한 데이터를 제공할 수 있는지 체크

**Comment by ytaek** [comment]
2. 좋습니다!
3. 좋네요!
4. CSM을 Root node부터 돌리는게 아니라 HEAD부터 돌려도 유의미한  CSM 생성 가능합니다. 단, 
    1. (브랜치가 복잡할 경우) 두 방법의 결과가 다르게 나올 수 있을 것 같습니다… 만 overview를 본다는 관점에서 그게 같을 필요는 없을 것 같아요
    2. 100개 혹은 1000개씩 끊어서 한다고 했을 경우, 정보가 부족하기 때문에 처리가 애매 혹은 불가능해지는 노드들이 생길 껀데, 해당 부분에 대한 처리를 고민해야 할껍니다.
    3. 말씀하신 대로 위 4-2 이슈 때문에라도 유저가 제공받는 정보가 적어질 경우가 있습니다. 이건 표현의 방법등으로 해결하던지 할 수도 있겠지요
5. 사용성에 대해 신경쓰는게 너무 좋습니다. FE 분들이 모인게 맞긴 맞군요!! (BE는 저렇게까지는… ㅋㅋ)
