### ISSUE TITLE
[engine/AI] 요약/릴리즈 노트 기능 구현 관련 현황 정리 및 방향성 논의

### ISSUE THREAD

**Issue by mdgarden** [githru/githru-vscode-ext#624]
### 현재 상황 정리
- AI 팀에서 사용할 Chat GPT API KEY 공유가 필요합니다. (무료버전 사용 시 API 호출이 되지 않음)
  - API KEY 입력하게 하는 방식으로 우회
  - ~~셀레니움같이 메크로처럼 긁어오기~~
  - 생성형 AI 서드파티 (하루 40개 제한 있음)
  - copilot 활용?
- 구현할 기능들에 대해서 더 많이 구체적으로 사양을 정해야할 필요가 있습니다. [멘토님이 전에 쓰셨던 릴리즈 노트 관련](https://github.com/githru/githru-vscode-ext/issues/513)해서 멘토님이 생각하셨던 기능들의 이미지를 공유받고 싶습니다. (최소한의 방향성 정하는데 도움받고 싶습니다)
    - 예시들)
    - API 자체에 토큰 수 (=글자 수) 제한이 있어서 githru의 사양이 AI의 api의 사양을 따라가야하는 상황, 또 AI마다 토큰 제한이 다를 수 있습니다(확인 필요)
    - 선택구간에 대해서: 커밋수, 날짜, 브랜치 무엇을 기준으로 어떻게 선택을 하게 해야할지 정해야합니다
- AI가 요약했을 때, 어떤 내용을 어떻게 보여줄지에 대해서 마찬가지로 최소한의 방향성을 정하고 싶습니다
    - 어떤 사람이
    - 어떤 작업을 했는지
    - 어떤 파일이 수정되었는가
    - 어떤 사람/파일 수정 정보가 필요한지?
- 엔진 패키지의 개발에 많은 어려움이 있습니다.
-> 빠른 시일안에 멘토님과의 대화의 시간을 가지고 싶습니다(디엠으로 별도 연락)

### 관련 이슈들
- [engine/AI] 노드의 커밋 AI 요약을 위한 기초적인 기능 도입 #578
- [engine/AI] AI 요약 기능 고도화 #579
- [engine/AI] AI 요약 기능 - 커밋 가져오기 기준 및 View 구성 논의 #592
- [engine/AI] AI 요약 기능 - 다양한 AI 서비스 구현 #593
- [engine/AI] 릴리즈 노트 작성 #594

**Comment by ytaek** [comment]
https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/creating-a-pull-request-summary-with-github-copilot
https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample
https://code.visualstudio.com/api/extension-guides/chat

**Comment by choisohyun** [comment]
- 서드파티
  -  https://docs.aimlapi.com/api-reference/examples
  - Limited access to over 100 AI Models over API
  - Limited token usage
  - Limited AI Playground model selection
  - 무료 버전으로 먼저 사용해 보기 ? 하지만 어느 정도 리밋이 있을지는 정확히 적혀있지 않음
- vscode chat
  - https://github.com/microsoft/vscode-extension-samples/blob/main/chat-sample/README.md
  - vscode > activate에 커밋을 받아 prompt 실행시키는 구조로 추가하면 가능할 듯 함

**Comment by mdgarden** [comment]
- VSCode의 Chat Extension과 Language Model 비교
  - Chat Extension : 채팅 확장을 만들기 위한 인터페이스를 제공
  - Language Model : AI 기능과 자연어 처리를 통합할 수 있게 해주는 특정 API
  -  Language Model API를 활용해 인공지능이 도와주는 채팅형 확장 프로그램을 만들 수 있음
  - AI를 반드시 사용하지 않더라도 Chat Extension만으로 확장 프로그램을 만들 수 있음 (예시: 오늘의 날씨 알려줘 라고 입력하면 날씨 알려줌)

이 이슈를 진행하면서 Language Model API는 필히 익혀야할 내용 같고 , chat이라는 형태로 구현을 할지에 대해서는 좀 더 논의가 필요할 것 같습니다.

**Comment by mdgarden** [comment]
0812 회의 내용
결론 : 아무도 안써도 우리는 이 기능을 만들겠다 :punch: :muscle:(ㅋㅋㅋ)

- 무료로 이용 가능한 AI API는 현재 Gemini AI 뿐
- 개발은  Gemini 를 활용하여 개발
- Gemini AI는 VSCode의 Language Model API에서 지원하지 않기 때문에 별도로 API를 주고 받는 로직을 작성해야함.
- Chat Extension을 활용하여 챗봇에 가까운 형태로 사용자가 이용할 수 있게함(유저는 정해진 커맨드만 사용할 수 있음)
- Chat Extension과 Gemini로 어느 정도 구현이 되면, 다른 AI 모델들도 사용할 수 있도록 기능 추가 구현
- 실제로는 학생용이나 엔터프라이즈용으로 AI API를 사용할 수 있는 유저가 소수 있을 것이라고 기대중

**Comment by ytaek** [comment]
응원하겠습니다!!! 어떻게 나올지 가장 궁금해지는 기능 중 하나입니다 👍
