### ISSUE TITLE
[view] commit 내용에 PR 내용이 포함되어 있음

### ISSUE THREAD

**Issue by choisohyun** [githru/githru-vscode-ext#625]
- 특정 시점 이후부터 커밋 내용에 PR 내용까지 포함되어 보이고 있습니다. 원래는 `Merge pull ~` 커밋으로 보였습니다. 의도된 기능인지 확인이 필요합니다.
- 의도된 기능이면 Close 부탁드립니다!

(현재) PR 내용 노출 
<img width="966" alt="Screenshot 2024-08-08 at 9 28 49 PM" src="https://github.com/user-attachments/assets/44cef924-828c-41d8-b9f7-72d515961504">
<img width="1097" alt="Screenshot 2024-08-08 at 9 29 05 PM" src="https://github.com/user-attachments/assets/e9f54785-3f4f-42e9-b3c5-0ca025e0dca7">

(이전) Merge 커밋으로 노출 
![image](https://github.com/user-attachments/assets/0c49aa1d-4bad-4622-a47f-41df6abe937d)

**Comment by ytaek** [comment]
으음... 이부분 기억이 가물가물한데 (죄송... 😿)

더듬어보니 PR로 CSM을 한번 더 수행합니다.
PR 자체가 하나의 `묶음`이기 때문에, 이걸 CSM과 유사한 형태라고 생각하도록 했던 것 같(^^;;)네요.

여기서 단순히 commit message를 모아놓는 것을 넘어서, 
뭔가 `요약`을 하기위해
PR Detail 내용 (지금 포함되었다고 말씀하신)을 그 요약으로 생각하고, 표현하도록 한 것 같습니다.

그런데 이게 Commit 내용 안에 들어가야 되는건지는 조금 애매하네요 ㅜ.ㅜ

요 내용 중요 이슈로 좀 고정해놓고 살펴보도록 해야겠습니다.
@choisohyun 님 꼼꼼한 확인 감사합니다!!

**Comment by seungineer** [comment]
PR 제목인 `content.message`가 생성되는 과정에서 repo명이 올바르지 않게 들어가면, PR 제목과 함께 PR 내용이 표시되는 버그가 발생합니다.

위와 같은 이유로 현재는 `const repo = initialRepo[0]`로 Repo명의 가장 앞자리 문자만 할당하도록 되어 있습니다.

아마도 해당 버그는 제가 일전에 repo에 initialRepo를 그대로 할당하여 발생시켰던 버그인 것 같습니다. 😅
현재는 아래와 같이 해결되어 버그가 발생하고 있지 않아 해당 issue는 close하도록 하겠습니다.

*참고 코드입니다
```javascript
// vscode/src/extension.ts

const gitLog = await getGitLog(gitPath, currentWorkspacePath);
        const { owner, repo: initialRepo } = getRepo(gitConfig);
        const repo = initialRepo[0];
        const engine = new AnalysisEngine({
          isDebugMode: true,
          gitLog,
          owner,
          repo,
          auth: githubToken,
          baseBranchName,
        });
 ```
