### ISSUE TITLE
[view] 상태관리도구 도입 관련 논의

### ISSUE THREAD

**Issue by Sang-minKIM** [githru/githru-vscode-ext#626]
8월 8일 View 성능 최적화팀 논의 내용과 함께 상태관리 선택 관련해서 의견 여쭤봅니다!

일단 저희의 결론은 Zustand 쪽으로 기울고 있는데 많이 사용해보신 분 계시면 githru에 적합한지, 실제 사용후기(?) 많이 남겨주시면 감사하겠습니다 😁

그리고 다른 라이브러리가 githru 더 적합한 것 같다 하시면 의견 한마디 부탁드려요!!

# Recoil

[공식문서링크](https://recoiljs.org/ko/docs/introduction/getting-started/)

- **핵심 개념**:
    - 원자(Atom) 기반의 상태 관리, 이를 통해 상태를 읽고 쓸 수 있음
    - selector를 사용하여 상태를 파생
- **장점**:
    - 상태 변경 시 관련 컴포넌트만 리렌더링
    - useState와 비슷한 사용법
- **단점**:
    - key 생성의 수고로움
    - 객체 구조 처리의 어려움
        - atom 단위 상태를 사용 → atom에 객체 구조를 담는 것은 비효율적임(객체의 일부분만 변경이 되어도 새로운 아톰(객체)을 만들기 때문)
            - 해결책으로는 객체 구조를 여러 atom으로 쪼개어서 관리해야 함(기존 코드의 객체 변수에서 많은 수정이 불가피함)
- 예제 코드
    
    ```tsx
    import { atom, useRecoilState } from 'recoil'
    
    // 원자 정의
    const counterAtom = atom({
      key: 'counterAtom',
      default: 0,
    })
    
    function Counter() {
      const [count, setCount] = useRecoilState(counterAtom)
    
      return (
        <div>
          <p>Count: {count}</p>
          <button onClick={() => setCount(count + 1)}>Increment</button>
        </div>
      )
    }
    ```
    

# Jotai

[공식문서링크](https://jotai.org/)

- **핵심 개념**:
    - Recoil과 같이 원자(Atom) 기반으로 상태 관리
- **장점**:
    - 쉬운 사용법
    - context의 문제점인 리렌더링 해결, 메모이제이션이나 최적화 필요 없음
    - key를 관리하지 않아도 되어서 recoil보다 낫다고 판단됨
    - 비동기 지원해서 suspense 사용가능(확실하지 않음)
- **단점**:
    - atom 기반의 경우 사용하는 컴포넌트마다의 상태 변경 추적이 어려움
- 예제코드
    
    ```tsx
    import { Provider, atom, useAtom } from 'jotai'
    
    const textAtom = atom('hello')
    const textLenAtom = atom((get) => get(textAtom).length)
    const uppercaseAtom = atom((get) => get(textAtom).toUpperCase())
    
    const Input = () => {
      const [text, setText] = useAtom(textAtom)
      return <input value={text} onChange={(e) => setText(e.target.value)} />
    }
    
    const CharCount = () => {
      const [len] = useAtom(textLenAtom)
      return <div>Length: {len}</div>
    }
    
    const Uppercase = () => {
      const [uppercase] = useAtom(uppercaseAtom)
      return <div>Uppercase: {uppercase}</div>
    }
    
    const App = () => (
      <Provider>
        <Input />
        <CharCount />
        <Uppercase />
      </Provider>
    )
    
    export default App
    ```
    

# Zustand

[공식문서링크](https://github.com/pmndrs/zustand)

- **핵심 개념**:
    - store 모듈을 통해 상태를 관리
    - store에 상태변화 메서드를 만들어서 함께 관리(액션기반)
- **장점**:
    - 모듈별 store에서 상태 변화를 바로 확인 할 수 있음
    - redux devtools로 디버깅 가능
    - provider로 컴포넌트를 감싸주지 않아도 됨
    - 라이브러리 용량이 **325 kB로** 매우 적음
    - Context API에서의 전환이 용이
        - 훅 기반 접근 방식
            - useGlobalData 호출을 유지하면서 이 내부를 Zustand로 수정해가며 마이그레이션 가능
- **단점**:
    - 액션 기반 상태관리에 익숙해져야함

```tsx
import { create } from 'zustand'

const useBearStore = create((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}))

function BearCounter() {
  const bears = useBearStore((state) => state.bears)
  return <h1>{bears} around here ...</h1>
}

function Controls() {
  const increasePopulation = useBearStore((state) => state.increasePopulation)
  return <button onClick={increasePopulation}>one up</button>
}
```

# **Redux**

[공식문서링크](https://ko.redux.js.org/introduction/core-concepts)

- 핵심개념
    - 액션기반의 상태관리
- 선택적 구독 구현이 번거로움
    - 기본적으로 전체 store 상태에 대한 구독을 함(이로 인해 useSelector를 사용하더라도 여전히 ‘전체 상태 트리의 변화를 감지’)
        - 선택적 구독 구현을 위해서는 reselect와 같은 추가 라이브러리에 의존해야 함
- 러닝커브가 높고 보일러플레이트가 많음

# **MobX**

[공식문서링크](https://ko.mobx.js.org/reactions.html)

- 핵심개념
- 장점
    - 선택적 구독의 자동화
    - 렌더링 최적화 기능 내장
- 단점
    - 반응형 프로그래밍에 대한 이해 필요(https://itchallenger.tistory.com/705)

**Comment by xxxjinn** [comment]
저는 recoil과 zustand의 사용 경험이 있습니다!

둘 다 구글링하면 쉽게 정보를 얻을 수 있는 편이라 러닝커브는 적은 것 같다고 생각했습니다. 

저도 잘 아는 것은 아니지만, 본문에 적어주신 recoil의 단점 중 key 생성이 수고롭다는 점과 관련해서는 개인적으로 zustand는 액션 함수까지 만들어주어야 해서 zustand가 훨씬 번거로웠던 것 같습니다...ㅎㅎ 그래도 우리에게는 gpt도 있습니다.

redux같은 경우 강의로 접한 적이 있는데, 앞선 두 라이브러리보다 사용법이 복잡했던 것 같아 비교적 러닝커브가 크다고 생각했습니다. 물론 시간이 여유로우시다면 redux도 나쁘지 않다고 생각합니다!

언급해주신 상태관리 라이브러리들의 사용 순위를 볼 수 있는 사이트입니다.
https://npmtrends.com/jotai-vs-mobx-vs-react-redux-vs-recoil-vs-zustand

### 의견
recoil같은 경우 제가 알기로는 라이브러리 자체의 업데이트 속도가 느리다고 알고 있습니다. (참고: https://medium.com/@clockclcok/recoil-%EC%9D%B4%EC%A0%9C%EB%8A%94-%EB%96%A0%EB%82%98-%EB%B3%B4%EB%82%BC-%EC%8B%9C%EA%B0%84%EC%9D%B4%EB%8B%A4-ff2c8674cdd5)

그래서 저는 러닝커브가 높지 않아 효율적이며 그나마 사용 순위도 2위로 높은 zustand 사용을 추천드립니다ㅎㅎ

**Comment by pcwadarong** [comment]
저는 recoil, zustand, context api 사용해보았는데요!
사실 redux는 러닝커브가 높아서 오픈 소스에서 사용하기에는 좀 어려울 것 같구요.
recoil도 편하긴 했지만 최근에 지원이 잘 안되는 추세라서...ㅎㅎ (버려짐..)
최근 트렌드는 zustand 나 jotai라고 보시면 좋을 것 같습니다!! 둘 다 러닝 커브는 괜찮은 편이에요.
두 개는 선호도가 비등비등한 걸로 알고 있어서 장단점 비교해서 이중에서 고르시면 좋지 않을까 싶습니다 ㅎㅎㅎ

**Comment by bbanderson** [comment]
zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요!
각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~
또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!

**Comment by xxxjinn** [comment]
> zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요! 각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~ 또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!

(궁금합니다!) githru는 결국에는 vscode 상에서 실행되는데 로컬/세션 스토리지에 저장한 상태값이 그대로 적용(?)이 되나욥??..

**Comment by bbanderson** [comment]
> > zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요! 각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~ 또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!
> 
> (궁금합니다!) githru는 결국에는 vscode 상에서 실행되는데 로컬/세션 스토리지에 저장한 상태값이 그대로 적용(?)이 되나욥??..

@xxxjinn 아래 예시가 말씀하신 의도와 맞는지 모르겠지만, 우선 콘솔에는 잘 찍혔습니다!!
다르다면 말씀주세요😄
<img width="921" alt="스크린샷 2024-08-10 오전 9 05 23" src="https://github.com/user-attachments/assets/8b1fa8e9-c97b-4389-a326-825e09381cc8">
<img width="748" alt="스크린샷 2024-08-10 오전 9 03 59" src="https://github.com/user-attachments/assets/0e647878-63da-45d4-8d77-c31912d2315a">
<img width="737" alt="스크린샷 2024-08-10 오전 9 04 15" src="https://github.com/user-attachments/assets/38b33f41-b00b-4960-a166-f88ba7e854d2">

**Comment by Sang-minKIM** [comment]
> 저는 recoil과 zustand의 사용 경험이 있습니다!
> 
> 둘 다 구글링하면 쉽게 정보를 얻을 수 있는 편이라 러닝커브는 적은 것 같다고 생각했습니다.
> 
> 저도 잘 아는 것은 아니지만, 본문에 적어주신 recoil의 단점 중 key 생성이 수고롭다는 점과 관련해서는 개인적으로 zustand는 액션 함수까지 만들어주어야 해서 recoil보다는 zustand가 번거로웠던 것 같습니다...ㅎㅎ
> 
말씀해주신 것 듣고 보니 그럴수도 있겠네요. 액션함수 만드는 것에 비하면 key 생성은 코드로 보면 아무것도 아니니까요 ㅎㅎ..

> redux같은 경우 강의로 접한 적이 있는데, 앞선 두 라이브러리보다 사용법이 복잡했던 것 같아 비교적 러닝커브가 크다고 생각했습니다. 물론 시간이 여유로우시다면 redux도 나쁘지 않다고 생각합니다!
> 
> 언급해주신 상태관리 라이브러리들의 사용 순위를 볼 수 있는 사이트입니다. https://npmtrends.com/jotai-vs-mobx-vs-react-redux-vs-recoil-vs-zustand
> 
> ### 의견
> recoil같은 경우 제가 알기로는 라이브러리 자체의 업데이트 속도가 느리다고 알고 있습니다. (참고: https://medium.com/@clockclcok/recoil-%EC%9D%B4%EC%A0%9C%EB%8A%94-%EB%96%A0%EB%82%98-%EB%B3%B4%EB%82%BC-%EC%8B%9C%EA%B0%84%EC%9D%B4%EB%8B%A4-ff2c8674cdd5)
> 
> 그래서 저는 러닝커브가 높지 않아 효율적이며 그나마 사용 순위도 2위로 높은 zustand 사용을 추천드립니다ㅎㅎ

의견 감사합니다!   
recoil은 아직도 정식 1버전이 안된것을 보면.. 선택지에서 없애도 될 것 같네요

**Comment by Sang-minKIM** [comment]
> zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요! 각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~ 또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!

zustand/persist도 있군요!  
감사합니다👍🏻

**Comment by Sang-minKIM** [comment]
> > > zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요! 각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~ 또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!
> > 
> > 
> > (궁금합니다!) githru는 결국에는 vscode 상에서 실행되는데 로컬/세션 스토리지에 저장한 상태값이 그대로 적용(?)이 되나욥??..
> 
> @xxxjinn 아래 예시가 말씀하신 의도와 맞는지 모르겠지만, 우선 콘솔에는 잘 찍혔습니다!! 다르다면 말씀주세요😄 

아마 웹브라우저가 아닌 vscode 상에서 실행되는데 웹 스토리지를 활용할 수 있는지를 여쭤본 것 같습니다!

**Comment by Sang-minKIM** [comment]
> 저는 recoil, zustand, context api 사용해보았는데요! 사실 redux는 러닝커브가 높아서 오픈 소스에서 사용하기에는 좀 어려울 것 같구요. recoil도 편하긴 했지만 최근에 지원이 잘 안되는 추세라서...ㅎㅎ (버려짐..) 최근 트렌드는 zustand 나 jotai라고 보시면 좋을 것 같습니다!! 둘 다 러닝 커브는 괜찮은 편이에요. 두 개는 선호도가 비등비등한 걸로 알고 있어서 장단점 비교해서 이중에서 고르시면 좋지 않을까 싶습니다 ㅎㅎㅎ

역시 zustand와 jotai가 트렌드군요...  
감사합니다!!

**Comment by ytaek** [comment]
> > > > zustand 중심으로 써봤는데, 그 명성에 맞게 간단하고 가벼워서 저희 프로젝트에 빠르게 테스트 및 적용 가능할 것 같아요! 각 상태의 구독이 필요한 컴포넌트들의 결합도를 낮춘다면(ex. CLOC 정보가 필요한 곳에는 CLOC store만 불러오기 등), 아시다시피 ContextAPI와 달리 리렌더링의 범위를 최소화할 수 있어서 성능 최적화 결과가 잘 드러날 것으로 기대되네요~ 또한 `zustand/persist`를 통해 로컬/세션 스토리지를 활용하는 기능도 쉽게 만들 수 있을 것 같구요!
> > > 
> > > 
> > > (궁금합니다!) githru는 결국에는 vscode 상에서 실행되는데 로컬/세션 스토리지에 저장한 상태값이 그대로 적용(?)이 되나욥??..
> > 
> > 
> > @xxxjinn 아래 예시가 말씀하신 의도와 맞는지 모르겠지만, 우선 콘솔에는 잘 찍혔습니다!! 다르다면 말씀주세요😄
> 
> 아마 웹브라우저가 아닌 vscode 상에서 실행되는데 웹 스토리지를 활용할 수 있는지를 여쭤본 것 같습니다!

webview라서 모두 사용가능합니다!!
(vscode도 자체적으로  node - webview를 사용하고 있어요!)

**Comment by Sang-minKIM** [comment]
여러 의견 받아보니 역시 zustand가 좋다는 생각이 드네요!

의견 주신 많은 분들께 감사드립니다.
githru에 zustand 도입 해보겠습니다!
