### ISSUE TITLE
[view] LineChart Brushing 후 생성되는 Reset 버튼 UI 개선

### ISSUE THREAD

**Issue by pithesun** [githru/githru-vscode-ext#631]
*  LineChart Brushing 후 생성되는 Reset 버튼 디자인 변경이 필요해보입니다.

![image](https://github.com/user-attachments/assets/395e3485-ecac-4ed0-821e-4c3eb99db63c)

**Comment by xxxjinn** [comment]
ㅎㅎ pr타고 왔습니다.....!! 다름이 아니라 제가 mui 적용하는 팀에 속해 있어서, 괜찮으시다면 제가 mui 버튼을 가져와서 수정하려고 하는데 어떻게 생각하시나요?!

**Comment by pithesun** [comment]
오 넵 좋습니다!

**Comment by xxxjinn** [comment]
> 오 넵 좋습니다!

넵 그럼 assignee 저로 바꿔서 작업 후 pr 올리겠습니다! 감사합니다 :>
