### ISSUE TITLE
[view] 확정 Theme 공유

### ISSUE THREAD

**Issue by xxxjinn** [githru/githru-vscode-ext#637]
안녕하세요, View 디자인 시스템 팀입니다!
Theme 색상은 첨부해드린 사진대로 fix할 것 같습니다 :>

체크 해 둔 두 가지 Theme에 맞는 기가 막힌 테마 이름이 있다면 추천 받아서 적용하겠습니다!
아이디어가 있으시다면 남겨주시고, 괜찮은 아이디어가 있다면 좋아요도 눌러주세요 🙂🙂🙂🙂🙂🥰 

많은 참여 부탁드립니다 <3<3
 
![image](https://github.com/user-attachments/assets/25e79a77-240d-41a6-82a7-d104979f9754)

**Comment by xxxjinn** [comment]
참고로 저는 1번 Aqua 2번 Cotton으로..ㅎㅎ

**Comment by pcwadarong** [comment]
조아여~ 저는 2번 Sakura도 좋은 것 같아요. 코튼 캔디도 좋네용

**Comment by seungineer** [comment]
1번 Ocean / 2번 Lilac
어떠신가요 ㅎㅎ

> 코튼 캔디도 좋네용

저도 Cotton Candy도 어떤 색의 느낌일지 와닿아서 좋은거 같아요!

**Comment by ytaek** [comment]
창의적인 이름이 많네요!!! 🍨🍨🍨 
뭔가 있어보입니다!!
