### ISSUE TITLE
[view] branches select box label 수정

### ISSUE THREAD

**Issue by xxxjinn** [githru/githru-vscode-ext#652]
- 화면 상단의 branches select bos는 현재 mui의 select box를 사용 중에 있습니다.
-  box 상단에 label이 붙어 수정이 필요할 것 같다는 의견이 있어 수정하도록 하겠습니다!

<img width="950" alt="image" src="https://github.com/user-attachments/assets/777dbbf5-ab58-4927-8a6c-70921cc7acd3">

**Comment by pcwadarong** [comment]
#645 에서 제가 작성했던 리뷰들은 따로 이슈 파는 게 좋을까요?

**Comment by xxxjinn** [comment]
> #645 에서 제가 작성했던 리뷰들은 따로 이슈 파는 게 좋을까요?

#645 에 채원님 LGTM만 있눈데 어떤 리뷰를 말씀하신건 지 알 수 있을까요?
