### ISSUE TITLE
[view] 커밋 목록의 프리뷰 순서 변경 제안

### ISSUE THREAD

**Issue by lxxmnmn** [githru/githru-vscode-ext#658]
## 제안

`SummaryCommitList`의 길이가 5 이상인 경우에는 가장 오래된 커밋부터 프리뷰로 보여주고,
토글 버튼을 클릭하면 모든 커밋을 보여주고 있습니다.
리스트 하단에 있는 토글 버튼을 클릭했을 때, 리스트 상단에 내용이 추가되는 방식이 어색하게 느껴집니다.

사용자가 보편적으로 기대하는 UX에 맞게 최신 커밋부터 프리뷰로 보여주고 리스트 하단에 나머지 커밋이 추가되는 방식으로 변경하면 좋을 것 같습니다.

- 닫았을 때
![hide](https://github.com/user-attachments/assets/3ca0b70a-4213-41e0-b81a-8a17c7cf615f)

- 펼쳤을 때
![show](https://github.com/user-attachments/assets/b6f12975-3bf1-4fae-94f5-7cac30f63e3e)

## 추가 이슈

`SummaryCommitList` 토글 여부에 따라 서브 그래프의 순서가 역순으로 바뀝니다.

- 닫았을 때
![hide-sub](https://github.com/user-attachments/assets/36d4c49f-fee2-4839-80e6-e71f28f05a96)

- 펼쳤을 때
![show-sub](https://github.com/user-attachments/assets/78d61f6d-6513-434a-9a77-54eef041c427)

**Comment by lxxmnmn** [comment]
@ytaek 가장 오래된 커밋부터 프리뷰로 보여주는 이유가 있을까요???

**Comment by ytaek** [comment]
> @ytaek 가장 오래된 커밋부터 프리뷰로 보여주는 이유가 있을까요???

순서가 꼬인것 같네요 😂  
옆의 subgraph node들이랑 align 되도록 순서를 맞춰야할것 같습니다!

**Comment by ytaek** [comment]
예상되는 milestone 도 찍어주시면 좋을 것 같습니다 😸

**Comment by seungineer** [comment]
> 사용자가 보편적으로 기대하는 UX에 맞게 최신 커밋부터 프리뷰로 보여주고 리스트 하단에 나머지 커밋이 추가되는 방식으로 변경하면 좋을 것 같습니다.

@lxxmnmn
저도 최신 커밋이 프리뷰 상단부터 나오고, 'Read More ...'를 클릭하면 과거 커밋이 하단에 추가되는 방식이 낫다고 생각합니다!
최신 커밋 서브 그래프도 마찬가지로 상단에 보이는게 맞을 것 같구요 🙆‍♂️

#671 PR에서는 우선 테스트 코드에 맞게 오래된 커밋이 상단에 위치되도록 두겠습니다. 본 이슈에서 리스트(+ 서브 그래프) 정렬 순서를 맞추고 테스트 코드까지 수정하는게 좋을 것 같아요 🚀
