### ISSUE TITLE
[engine] getCommitRaws 함수 개선

### ISSUE THREAD

**Issue by yoouyeon** [githru/githru-vscode-ext#675]
## 개요

git log 데이터를 파싱하는 `getCommitRaws` 함수를 개선해보려고 합니다.

## 내용

- `getCommitRaws` 함수가 git log에서 제공하는 출력 포맷(fuller)을 기반으로 구현되어 있어서 필요한 형태로 가공하는 과정이 복잡합니다.
  → git log 출력 자체를 파싱하기 좋은 포맷으로 바꾸고, 파싱 과정을 덜 복잡하게 수정해보려 합니다.
- `getCommitRaws` 함수에서 데이터를 파싱하고, json 형태로 변환하는 2번의 반복을 1번으로 줄여보려 합니다.

---

개선하고자 했던 이유에 대한 설명이 부족했던 것 같아 추가로 남깁니다!

기존에 git log 포맷으로 사용하던 `fuller` 포맷은 사람이 이해하기에는 편한 포맷이지만 컴퓨터가 읽기에는 (간결한 코드로 파싱하기에는) 좀 복잡한 포맷이라고 생각했습니다.
`fuller` 포맷을 파싱하는 `getCommitRaws` 함수 코드를 봤을 때 해결하고 싶었던 부분이 조금 있었는데,

1. 로그를 new line 단위로 끊어서 `startWith`으로 각 라인의 첫 문장을 확인하여 파싱하는 방식이
   정확히 해당 코드가 어떤 내용을 파싱하고 있는지 (`fuller` 형식에 대한 이해가 부족하다면) 한눈에 이해하기 어려움
   예) `if (str.startsWith("CommitDate")` 분기에서 `CommitDate` 외에도 `commit message`와 `fileChange`를 처리함
2. `fuller` 포맷의 `“commit”`, `username <user email>`, ref 목록을 감싸는 괄호 등의 형식을 제거하는 코드가 오히려 `fuller` 형식을 모를 때에는 의도를 파악하기 어려움
3. line 별로 읽으면서 각 line을 카테고리별로 분리하는 for loop 한번
   각 카테고리의 원소들을 다시 json 타입으로 변환하는 for loop 한번, 총 2번의 for loop를 돌게 되는데, 
   이렇게 중복으로 동일한 데이터를 반복하는 것이 성능에 영향을 줄 것이라 생각

이러한 부분들을 해결해보고 싶어서 git log의 출력 형식을 변경하고, `getCommitRaws`의 파싱 과정을 변경해보려고 했습니다!

## Todo

- `getGitLog` 수정 (참고: https://git-scm.com/docs/git-log#_pretty_formats)
- `getCommitRaws` 수정

**Comment by ytaek** [comment]
refactoring은 언제나 환영합니다!!!

**Comment by choisohyun** [comment]
요거 종료된 이슈로 보여서 종료하겠습니다!
