### ISSUE TITLE
[view] Detail 구현

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#68]
# Detail

## Render 조건

Vertical Cluster List Feature의 Summary Component를 클릭하는 경우 Detail Component가 렌더링 됩니다.

## Props

{ data , id }

data : 전체 데이터 <br />
id : Click한 Summary ( Commit ) Id

## Component UI

![스크린샷 2022-09-03 오전 4 23 17](https://user-images.githubusercontent.com/70205497/188223219-fe4a5c26-76d3-4c4d-97a9-5eb72d2d7992.png)

## Component UI Data

~diffStatistics => Statistics Component 렌더링~ <br />
author => ~name => Summary Component 렌더링~ , email 렌더 가능 <br />
authorDate => 렌더 가능 <br />
commitDate => 렌더 가능 <br />
committer => name,emails 렌더 가능 <br />
~message => Summary Component 에서 렌더링~ <br />
해당 STEM 의 COMMIT 나열 가능 <br />

## 희망

- relation issue  => 메세지에서 찾아야 하는가 ?
- relation pr => url 가져올 수 있는가 ?
- commit의 body 내용 가져올 수 있는가?

## 결과

<img width="886" alt="스크린샷 2022-09-11 오후 1 35 57" src="https://user-images.githubusercontent.com/70205497/189512708-6a6638a2-3fd5-42a0-bbbb-32ba84330670.png">

**Comment by jin-Pro** [comment]
Vertical Cluster List에서 제공해주는 message의 역할이 무엇인지?
Vertical Cluster List에서 click하여 보여주는 commit은 어떤 commit인지?
그에 따라 Detail Component에서는 어떠한 message를 보여줄 수 있는지?

@jejecrunch

**Comment by jin-Pro** [comment]
Vertical Cluster List에서 Author와 Committer가 있는데 Author를 선정한 이유는?  @jejecrunch 
Detail Component에서는 Author와 Committer 둘 중 어느 데이터를 보여주어야 하는지?

**Comment by jin-Pro** [comment]
해당 Commit과 관련된 STEM ( cluster ) 의 Commit들을 나열할 수 있는데 이게 의미가 있을지?

**Comment by jin-Pro** [comment]
Detail Component에서 보여줄 Commit과 연관된 정보를 찾는데,
commit과 연관된 issue 는 message에서 나타나는지? 
또한 url로 나타낼수 있는지?

@githru/engine

**Comment by jin-Pro** [comment]
Detail Component에서 보여줄 Commit과 연관된 정보를 찾는데,
commit과 연관된 PR 정보는 구할 수 있는지?

@githru/engine

**Comment by wherehows** [comment]
> 해당 Commit과 관련된 STEM ( cluster ) 의 Commit들을 나열할 수 있는데 이게 의미가 있을지?

요기 말씀 들어보니까 맨 마지막 커밋 메세지만 보여준다고 적혀있는데, Commit 나열하는거 괜찮아 보이네용!
링크: https://github.com/githru/githru-vscode-ext/issues/40#issuecomment-1231705406

**Comment by jejecrunch** [comment]
> Vertical Cluster List에서 제공해주는 message의 역할이 무엇인지?
> 
> Vertical Cluster List에서 click하여 보여주는 commit은 어떤 commit인지?
> 
> 그에 따라 Detail Component에서는 어떠한 message를 보여줄 수 있는지?
> 
> 
> 
> @jejecrunch 

1. 제가 출력하기 쉽게 가공한 것입니다
2&3. 제 생각에 이 부분은 제가 생각한 프로세스와 달라서 더 이야기해봐야할 것 같습니다 #42

**Comment by jejecrunch** [comment]
> Vertical Cluster List에서 Author와 Committer가 있는데 Author를 선정한 이유는?  @jejecrunch 
> 
> Detail Component에서는 Author와 Committer 둘 중 어느 데이터를 보여주어야 하는지?

통계팀도 그렇고 엔진팀도 그렇고 Author 쓰시는 것 같아서 처음에는 Commiter로 쓰다가 이후에 변경 후 PR 했습니다!

**Comment by jin-Pro** [comment]
> Detail Component에서 보여줄 Commit과 연관된 정보를 찾는데, commit과 연관된 issue 는 message에서 나타나는지? 또한 url로 나타낼수 있는지?
> 
> @githru/engine

위 부분에 대해서 [link](https://discord.com/channels/973748686238658571/997693397399777350/1015432661675814912)에 답변받았습니다!

**Comment by wherehows** [comment]
> 해당 Commit과 관련된 ~STEM~ CSM ( cluster ) 의 Commit들을 나열할 수 있는데 이게 의미가 있을지?

제가 생각한건 아래 이미지처럼 클러스터를 클릭했을을 때 commit 들을 보여주는 것이었는데,
<img width="460" alt="image" src="https://user-images.githubusercontent.com/81841082/188254764-c5782797-be5c-46d0-86b8-ea398e40793c.png">

여기 아래 링크를 보니까 cluster의 마지막 commit 만 보여준다고하면,,, detail에서 보여줘도 좋을 듯하네요.
링크: https://github.com/githru/githru-vscode-ext/issues/40#issuecomment-1231705406
