### ISSUE TITLE
[engine] getCommitRaws 테스트코드 보완

### ISSUE THREAD

**Issue by yoouyeon** [githru/githru-vscode-ext#690]
## 개요
연산을 통해 생성하던 getCommitRaws 테스트코드의 값을 본연의 값으로 변경합니다.

## 내용

getCommitRaws의 테스트 입력값을 변수 값의 연산을 통해 생성하는 대신 본연의 값으로 변경합니다.

> 가독성도 그렇고, 보통 test할 때 확인하는 값들은 연산을 거친 값이 아니라,
> 본연의 값(?)을 사용하는게 더 좋을 수 있습니다. (반복되어서 사용되는 경우가 아니라면)
> 살짝 사례가 다르게 보일 수 있지만, 아래 reference 추가합니다.
> https://learn.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices#avoid-logic-in-tests
> _Originally posted in https://github.com/githru/githru-vscode-ext/pull/680#discussion_r1739715599_

**Comment by choisohyun** [comment]
머지된 이슈로 보여 닫겠습니다!
