### ISSUE TITLE
[view] 선택된 클러스터 정보 표시 리스트가 열려 있는 상태에서 외부 요소 조작

### ISSUE THREAD

**Issue by seungineer** [githru/githru-vscode-ext#700]
### 현상

![스크롤안되는에러](https://github.com/user-attachments/assets/61fa5155-0c50-4966-95ad-1857c3b7619f)

- 선택된 클러스터 정보 표시 리스트가 열려 있는 상태에서는 **스크롤이 리스트 내부에서만 가능**한 상태입니다.
- 선택된 클러스터 정보 표시 리스트가 열려 있더라도 vertical cluster list 와 같은 외부 요소를 조작할 수 있어야 할 것 같은데 불가능합니다.

**Comment by pcwadarong** [comment]
엇 이런 부분은 mui에서 드롭다운 등의 '모달', '포탈' 요소가 열려 있을 때 자동으로 스크롤을 없애고 다른 것이 클릭되지 않게 설정하는 걸로 알고 있습니다. 이럴 때 드롭다운 외부를 한 번 누르면 드롭다운이 닫히고 그 다음 클릭 가능한 걸로 알고 있는데 혹시 불편하다고 느끼실까요? 그렇다면 mui 설정을 만져야 해결됩니다!

**Comment by seungineer** [comment]
> 혹시 불편하다고 느끼실까요? 그렇다면 mui 설정을 만져야 해결됩니다!

저는 드롭다운이 열려 있을 때도 스크롤이 되어야 할 것 같아요! 🙌

다른 분들은 어떻게 생각하시나요 ?! 🤔🤔

**Comment by xxxjinn** [comment]
저도 의식하고 나니까 불편하다고 생각해서 드롭다운이 열려있을 때에도 외부 요소 동작이 가능해야할 것 같다고 생각하게 되었어요..!! (모달같은 경우는 대부분 전체 시스템에 대한 설정을 바꾼다든지.. 유저에게 최종적으로 확인하는 용도 등에 쓰이면서 모달의 외부 화면은 어둡게 되는 식으로 보통 처리하는 것 같은데 선택된 클러스터 리스트는 이런 경우가 아니라고 생각해서요!)

비슷하게 상단 branch select도 mui라서 dropdown이 열리면 외부 요소 동작이 불가능하네요😖

**Comment by lxxmnmn** [comment]
좋은 이슈 감사합니다!!!

해당 드롭다운의 주 목적은 선택된 클러스터를 모아서 보여주는 것이기 때문에 외부 요소 동작을 제한할 이유가 없어보이네요!
mui를 사용하지 않는 방향으로 개선해보겠습니다 💪💪
