### ISSUE TITLE
[view] 상단 branch명 관련

### ISSUE THREAD

**Issue by xxxjinn** [githru/githru-vscode-ext#707]
이런 경우는 많이 없을 것 같다고 생각하지만 혹시나 해서 다른 분들의 의견이 궁금해 이슈로 올려보았습니다!

---
브랜치 명의 길이가 길 경우에 아래 사진과 같은 상황이 되는데,

<br/>

<img width="488" alt="image" src="https://github.com/user-attachments/assets/53dcafeb-f3ca-446f-8c03-4acf6dc4c9ed">
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/327d2053-3c6b-492d-98e5-0684e21495a6">

<br/>
<br/>

#### 생각한 대안

1. 이런 경우는 없을 것이라고 가정하고 추가로 처리하지 않는다.
2. 브랜치 명이 몇 글자 이상이면 자르고 prefix로 (...)을 붙여 hover 시 tooltip을 통해 전체 브랜치명을 보이게 한다.
3. suffix로 (...)을 붙인다. 
4. 특정한 단어를 포함하고 있으면 미리 정해 두고 줄인다. (ex. origin => og) 

다른 생략하는 방법이 있거나 하면 의견 말씀해주시면 감사드리겠습니다 🙂🙂❤️

**Comment by seungineer** [comment]
> 2. 브랜치 명이 몇 글자 이상이면 자르고 prefix로 (...)을 붙여 hover 시 tooltip을 통해 전체 브랜치명을 보이게 한다.

저는 전체 브랜치명은 확인할 수 있어야 할 것 같아서 2안이 좋아 보여요!
4안은 좋아 보이나 줄일 수 있는 수준에 한계가 있을 것 같아요.. 😢

**Comment by lxxmnmn** [comment]
> 3\. suffix로 (...)을 붙인다.

저는 텍스트가 길 경우에 보편적으로 처리하는 방식인 3안이 좋아보입니다!
태그의 [title](https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/title) 속성 값으로 브랜치명을 지정하면 hover 시 전체 브랜치명을 확인할 수도 있을 것 같아요

**Comment by pcwadarong** [comment]
4안은 중요도에 비해 넘 복잡해질 것 같고, 2나 3이 좋아보입니다!

**Comment by xxxjinn** [comment]
3안으로 작업 해보겠습니다~!!
