### ISSUE TITLE
[view] 브랜치를 바꾸면 색상 테마가 초기화 됨

### ISSUE THREAD

**Issue by mdgarden** [githru/githru-vscode-ext#747]
## 내용
임의의 색상 테마를 설정한 뒤, 브랜치를 바꾸면 가장 초기의 테마로 돌아옵니다.

## 재현 방법
1. 임의의 리포지토리에서 githru을 실행합니다.
2. 좌측 상단의 아이콘을 눌러 테마를 변경합니다.
3. 브랜치를 변경합니다.
4. 가장 초기의 테마로 돌아와있습니다.

## 추가 내용
테마와 관계없이 로딩색은 일정한 색인게 아쉽습니다...!

**Comment by taboowiths** [comment]
제가 작업한 부분에서 나는 에러네요 ... ! 확인해보겠습니다 🥲🥲

더불어 로딩 컴포넌트의 색상을 테마와 동기화 해보려고 했는데, 로딩이 특정 라이브러리를 사용하는 터라 컴포넌트 자체에 색상 코드를 입력해주어야 하는 방식이어서, 그 과정을 효율적으로 처리해 줄 방식을 고민하고 있었습니다 ㅠㅠ 해당 문제와 같이 다루도록 하겠습니다 !!
