### ISSUE TITLE
[Question] CSM 과 Cluster

### ISSUE THREAD

**Issue by jin-Pro** [githru/githru-vscode-ext#77]
# Githru 질문

Cluster , STEM, CSM 에 대한 이해도 부족으로 인한 질문입니다.

## 제 생각

[ CSM-base commit 질문 ]

![](https://i.imgur.com/ydZ4RMD.png)

위 이미지 (d)에서 Main STEM의 5,6번째 commit은 merge commit으로 CSM-base commit이며
위 이미지 (d)에서 fix STEM의 첫번째 commit은 merge commit이 아니지만, dev STEM의 5번째 commit을 가장 먼저 포함하고있는 commit이라 fix STEM의 첫번째 commit이 CSM-base commit이 된다.

라고 이해했는데 맞을까요???

[ Cluster 질문 ]
위 이미지 (g)에서 
main STEM에서 각각 3개/3개/2개의 commit을 묶어서 3개의 Cluster를 만들었는데,

제 생각은 (g)에서 main STEM의 붙어있는 2개의 Cluster ( CSM-base commit이 없는 Cluster와 있는 cluster)가 하나의 Cluster로 형성될거라 생각했습니다.

Cluster 형성 기준이 무엇인지 이해가 가질 않아 질문드리게 되었습니다!

@ytaek

**Comment by ytaek** [comment]
엄청 디테일하고 좋은 질문입니다 👍 

1. base commit 맞습니다.  
dev STEM의 5번째 commit이 dev에 들어갈꺼냐 fix에 들어갈꺼냐는 traverse 알고리즘 마음대로 일 것 같구요.
(spec에 정해져 있지 않음)
  
저희는 main stem만 바라보니까 일단 dev/fix 어디에 들어가도 관계없을 것 같긴 합니다.
매우 디테일한 부분인데 발견하셨네요 :- )

2.
cluster vs csm의 기준이 헷갈리는데 동일한 질문을 @githru/engine 팀에서도 하셨어요.

지금 조금 용어가 섞여있는데, 논문에서는 cluster와 csm은 다른 거라고 보시면 됩니다.
(csm = dag 구조에 따른 묶음, cluster = context(metadata의)에 따른 묶음)

하지만, 개념적으로 볼 때 csm도 크게 볼 때는 일종의 cluster는 맞구요. 여러개를 뭉쳐주니까.
githru에서는 절차적으로는 먼저 node들을 csm 을 적용하고, 그 뒤 (contextual)cluster를 수행하게 됩니다.
(cluster를 한뒤 csm을 할 수는 없습니다)

---

참고로, 추후(0.2 이후?)에 진행할 clustering은 아마도 아래 방법으로 생각하고 있습니다.
- commit type (conventional commit을 이용한)
- version (tag에 있는 v0.1.0 등)
- pull request (요건 githru에 없었던 새로운 것)

**Comment by anpaul0615** [comment]
> dev STEM의 5번째 commit이 dev에 들어갈꺼냐 fix에 들어갈꺼냐는 traverse 알고리즘 마음대로 일 것 같구요.

이부분 질문있습니다!

fix stem의 첫번째 커밋은 dev stem 의 5번째 커밋에서 분기된 커밋이기땜 때문에 (=즉 머지커밋이 아니라서) csm-based-commit 이 아니라 그냥 commit 으로 판단하고 처리는걸로 생각했는데요. 그런데 그림d 에서는 dev 5 commit을 머지커밋으로 가져오는것처럼 동작하네요.

저는 csm-based-commit 가 되는 기준은 머지커밋(=parents[0] parents[1] 둘다 가지고있는 커밋) 이라고 생각했었는데요. 위 케이스를 보니깐 이게 전부가 아닐수도 있겠다는 생각이 드네요.

혹시 그림d fix stem 과 같은 케이스를 판단하는 기준을 알 수 있을까요?

**Comment by ytaek** [comment]
> fix stem의 첫번째 커밋은 dev stem 의 5번째 커밋에서 분기된 커밋이기땜 때문에 (=즉 머지커밋이 아니라서) csm-based-commit 이 아니라 그냥 commit 으로 판단하고 처리는걸로 생각했는데요. 그런데 그림d 에서는 dev 5 commit을 머지커밋으로 가져오는것처럼 동작하네요.
> 
> 저는 csm-based-commit 가 되는 기준은 머지커밋(=parents[0] parents[1] 둘다 가지고있는 커밋) 이라고 생각했었는데요. 위 케이스를 보니깐 이게 전부가 아닐수도 있겠다는 생각이 드네요.
> 
> 혹시 그림d fix stem 과 같은 케이스를 판단하는 기준을 알 수 있을까요?

이 문제는 d-5(d 다섯번째) commit이 어느 branch, stem에 속한 것이냐? 라는 질문과 궤를 같이 하는 것 같네요.
이건 stem이 이미 그림처럼 쪼개저버렸기 때문에 일어났던 케이스라고 할 수 있구요.
만약에 stem을 쪼갤 때 fix부터 먼저 시작했다면, dev stem은 가장 최근 commit 하나만 달랑 남아있겠지요.
(이 순서를 정하는게 traverse 알고리즘 마음대로.. 라고 말씀드린거구요)

참고로, branch는 tag처럼 그냥 commit하나를 가리키는 pointer이기 때문에,
실제 저 d-5 라는 commit이 dev branch(stem말고) 인지 fix branch에서 파생된 놈인지를 알 수가 없습니다
(굳이 git ref 쪽을 뒤지면 정보가 있을 수도 있지만, remote에 있거나, 기간이 오래되거나 하면 정보가 날아갑니다ㅜ.ㅜ)
실제로 d1~5는 dev이면서 fix branch인거죠. 구분할 수가 없습니다.
그걸 임의로 stem으로 쪼개 주면서, 즉 leaf노드를 따라 가면서 first parent만 골라내면서
leaf 노드를 어떤 것부터 시작할지에 따라서 다른 거죠.
아마 githru는 main stem을 한 번 돌리고, 그 다음 최근 leaf node부터 쭉 stemming을 했던 것 같아요 
(그림 처럼)

아무튼, 어차피 저희는 main/master stem 위주로만 볼꺼라, 
다른 stem(branch)에 대한 정보는 '일단' don't care 할 수 있겠습니다.

**Comment by anpaul0615** [comment]
> 실제 저 d-5 라는 commit이 dev branch(stem말고) 인지 fix branch에서 파생된 놈인지를 알 수가 없습니다

이 말씀에 한방에 이해가 되네요 ㅎㅎ

![image](https://user-images.githubusercontent.com/8488507/188317134-5416ac1e-c2c7-45d5-a479-0858bfb7f394.png)

![image](https://user-images.githubusercontent.com/8488507/188317170-d1e55b84-7e55-4b64-9154-712156fade75.png)

그림a 에서는 첫번째이미지처럼 구분했지만
사실 두번째이미지처럼 해석할수도 있다는 말씀이신거죠? (branch = pointer)

저걸 명확하게 구분할수있는 방법이 없는 이상은 

> 그걸 임의로 stem으로 쪼개 주면서, 즉 leaf노드를 따라 가면서 first parent만 골라내면서
leaf 노드를 어떤 것부터 시작할지에 따라서 다른 거죠.
아마 githru는 main stem을 한 번 돌리고, 그 다음 최근 leaf node부터 쭉 stemming을 했던 것 같아요

이 말씀처럼 traverse 순서에 따라서 stem 결과가 달라지겠군요.

친절한 설명 감사합니다 :)))

**Comment by anpaul0615** [comment]
그런데 그럼에도 불구하고 조금 의문이 가는 부분이

![image](https://user-images.githubusercontent.com/8488507/188317556-2acd4e1c-f7f6-4b0f-9fa1-9d032d603733.png)
![image](https://user-images.githubusercontent.com/8488507/188317558-b305df06-3f84-4ce8-82b9-b2ae1fcfbeec.png)

그림c 에서 그림d 로 넘어갈때 dev-5 가 fix-1 에 squash 되는 것입니다.

제가 이해한 바로는 
- dev-5 커밋이 dev브랜치일때,
  => fix-1 커밋은 머지커밋이 아니므로(parents[1] === undefined), dev-5 를 squash 하지않음
  
- dev-5 커밋이 fix브랜치일때, (=dev-5 가 사실은 fix-5 일때)
  => fix-6 커밋은 머지커밋이 아니므로, fix-5 를 squash 하지않음
  => 또한 dev-1 커밋도 머지커밋이 아니므로, fix-5 를 squash 하지 않음
  ![image](https://user-images.githubusercontent.com/8488507/188317170-d1e55b84-7e55-4b64-9154-712156fade75.png)

으로 처리되지 않을까 생각했었습니다.
아마 위 내용은 제가 CSM 처리방식을 `if parents[1] exist then squash` 로 보고있어서 저렇게 해석했을수도 있을 것 같습니다.

혹시 CSM 처리흐름에서 제가 잘못 이해한 부분이 있을까요ㅠㅠ

**Comment by ytaek** [comment]
어라? 이거 @anpaul0615 님 말씀이 맞는것 같은데요!!
fix의 1번째 (f-1) commit이 merge commit이어야 되네요 ㅋㅋㅋㅋㅋ

그림을 정확하게 다시 그리자면,
<img width="339" alt="image" src="https://user-images.githubusercontent.com/24404665/188318661-392558fb-ba55-46f8-b4ba-b0393b927e52.png">
요렇게 되면, d-5가 f-1에 갖다 붙겠군요. ㄷㄷ

정확한 해설 감사합니다 : ---)

**Comment by anpaul0615** [comment]
아닙니다아닙니다..ㅠㅠ 다 모르는거 알려주시고 도와주신대로 접근한건데 다행히 저자분 생각과 맞아서 안심입니다..ㅎㅎ
저도 다행히 열심히 만든 코드 안고쳐도되서 좋네요..ㅋㅋ 🙏🙏🙏
