### ISSUE TITLE
[view] 정적 에러 검출을 위한 husky 추가하기

### ISSUE THREAD

**Issue by pshdev1030** [githru/githru-vscode-ext#78]
모노레포에서 생각한대로 동작하지 않아 고민했었는데 @ansrlm 님이 보내주신 아티클 보면서 적용해보려고 합니다!

우선순위가 높은 작업은 아니여서 기능구현을 마무리하는대로 천천히 시도하려교 해요!

https://javifm.com/en/blog/monorepo-simple-starter-workflow/

**Comment by ytaek** [comment]
husky 적용은 우선 holding합니다.
