### ISSUE TITLE
[view] githru 전체적인 view 및 use case 정리

### ISSUE THREAD

**Issue by wherehows** [githru/githru-vscode-ext#79]
저번에 미팅을 하고나서 전반적으로 서로 구현하는 방향이 다 다르다고 느꼈습니다. 큰 틀이 없어서 그렇다고 느꼈는데요.
그래서 제가 먼저 githru가 전체적으로 어떻게 흘러가는지와 view에 대해서 구성해봤습니다. 기획자가 아니기도 하고 전문적인 툴도 다뤄본 경험이 적어서 keynote로 짜집기했습니다. 🫠

❤️‍🔥 본 내용은 전적으로 제 머릿속에서만 나온 내용이고, 구현하시는 분들 고생하시는데 이렇게 해라 저래라 할 의도가 아니며, 크로스 체크하기 위함임을 먼저 말씀드립니다. 고생해주셔서 감사합니다 ( _ _ )
❤️‍🔥 각 feature 위치 배치도 고려해서 배치했습니다. 디테일하게 피드백 부탁드립니다.
❤️‍🔥 이런 상황(use case 작성)을 위해서 쓸만한 툴은 없을까요? image와 번호 마킹, 텍스트로 전달하는게 너무 불편하네유. 어쩔수 없으려나요 ㅇㅅaㅇ...

## 처음 페이지에 진입하는 경우 보여지는 View
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/81841082/188308694-edd8d872-405a-4f9f-a956-77bdb549c4b4.png">

- 1️⃣ 전체 기간을 대상으로 한 stem과 그에 따른 summary가 기본적으로 보여짐
  - summary는 각 클러스터가 갖고 있는 commit 리스트 전부 보여줌
- 2️⃣ 클러스터가 클릭되지 않았을 때는 기본적으로 클러스터를 클릭해달라는 안내 문구가 보여짐

## use case
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/81841082/188309221-d126e726-5e76-40c9-a8e0-dc0137e5becf.png">

- 1️⃣혹은 2️⃣로 filter 함에 따라서 3️⃣이 업데이트 됩니다. 5️⃣와 6️⃣은 처음 페이지를 진입했을 때와 동일한 View를 보여줍니다.
- 3️⃣ 스크롤이 가능합니다.
- 4️⃣(cluster 리스트 중 하나)를 클릭하면 5️⃣와 6️⃣이 업데이트 됩니다.
- 7️⃣(Filter)를 클릭하면 5️⃣가 업데이트 됩니다.
- 6️⃣의 박스를 누르면, 줌인/줌아웃이 됩니다.
- 8️⃣에 커서를 올리면, 프로필 사진 확대와 풀네임에 대한 tooltip이 나타납니다.
- 9️⃣(summary 리스트 중 하나)을 클릭하면, 🔟이 나타납니다.

**Comment by hy57in** [comment]
use case 툴은 아니지만 간단하게 와이프레임을 그려본다면 figma를 사용해도 좋을것 같습니다!

**Comment by ytaek** [comment]
WOW 정리가 엄청 잘 되어 있네요 👍 

- 참고로 Global Temporal Filter (왼쪽에서 날짜/revision 고르는 form)은 이번 v0.1의 스펙이 아닙니다~.
- 클러스터가 클릭되지 않았을 때는 전체 통계를 보여주면 좋겠습니다. 처음 띄울 때 인상도 중요해서..
 - performance 이슈가 있다면, 최근 30일 이렇게도 될 듯?

@hy57in 님, figma ㄷㄷ 안써봤는데 써보면 재밌겠네용!

**Comment by wherehows** [comment]
> use case 툴은 아니지만 간단하게 와이프레임을 그려보기 위함이라면 figma를 사용해도 좋을것 같습니다!
> 예시)
> <img alt="image" width="841" src="https://user-images.githubusercontent.com/60775453/188309892-2446ce28-0d71-4879-bb03-e6b3aa5c65bd.png">

와... keynote로 조잡하게 한거보다 훨씬 더 낫네요. 이 문서에서 이야기 한 내용을 업데이트 할때 figma로 업데이트해야겠습니다. 정보 너무 감사드립니다. 최고에연 ! 👍

**Comment by jejecrunch** [comment]
키노트로 작업하셨군요 ㄷㄷ
전체적인 내용은 제가 이해한 것과 동일합니다 !
그리고 figma로 작업하면 더 동적인 와이어 프레임 제작도 가능합니다 !

**Comment by pshdev1030** [comment]
와 엄청 깔끔하네요.. 저도 똑같은 로직으로 이해했습니다!

**Comment by jin-Pro** [comment]
9번 summary list 중 하나를 클릭하면 10 이 나타나는것에서, summary list 중 하나가 commit 하나 인것이 맞을 까요 ?? 
@jejecrunch  @wherehows

**Comment by jin-Pro** [comment]
Statistics Component에서 diff 관련 내용 렌더링 없는건가요..? 그럼 detail에서 갖고 가도 되는 걸까요 ..? 
@hanseul-lee

**Comment by jejecrunch** [comment]
@jin-Pro 현재 첨부된 사진은 전체 커밋 리스트를 보여주기 때문에 내용과는 조금 거리가 있습니다.
제가 말씀드린대로 1개의 summary는 여러개의 커밋 리스트를 가지고 있는 클러스터 요약본이라고 생각해주시면 감사할 것 같습니다 !

**Comment by vgihan** [comment]
Statistics Component에서 Icicle Chart가 diff 관련 내용인 것 같은데 맞을까요 ...?
@jin-Pro

**Comment by jin-Pro** [comment]
> Statistics Component에서 Icicle Chart가 diff 관련 내용인 것 같은데 맞을까요 ...? @jin-Pro

<img width="465" alt="스크린샷 2022-09-05 오후 2 44 00" src="https://user-images.githubusercontent.com/70205497/188368762-1413b9ef-919d-410f-88b1-51231421c45c.png">

이 부분을 의미했던겁니다! ㅎㅎ

**Comment by hanseul-lee** [comment]
@jin-Pro 넵~ 가져가셔도 되어요

**Comment by ytaek** [comment]
> > Statistics Component에서 Icicle Chart가 diff 관련 내용인 것 같은데 맞을까요 ...? @jin-Pro
> 
> <img alt="스크린샷 2022-09-05 오후 2 44 00" width="465" src="https://user-images.githubusercontent.com/70205497/188368762-1413b9ef-919d-410f-88b1-51231421c45c.png">
> 
> 이 부분을 의미했던겁니다! ㅎㅎ

요런 부분은 약간 좁은 의미의 summary 같긴 한데, detail에서 써도 되고 첫번째 그림 2-통계에서 써도 괜찮겠네요.
추후에 cluster node를 multi-selection 할 수 있게 되면 (fix된 기능 아닙니당!! 저 혼자 망상ㅋ)
detail은 cluster selection 하나에 대한 정보만, 2-통계에서는 전체 selection에 대한 통계를 보여줄 수 있으니까요

**Comment by wherehows** [comment]
> @jin-Pro 현재 첨부된 사진은 전체 커밋 리스트를 보여주기 때문에 내용과는 조금 거리가 있습니다. 제가 말씀드린대로 1개의 summary는 여러개의 커밋 리스트를 가지고 있는 클러스터 요약본이라고 생각해주시면 감사할 것 같습니다 !
> 
> @wherehows 혹시 이와 관련하여 이미지에 대한 설명을 덧붙여주실 수 있으실까요?

확인했습니다. 전체 commit list를 보여주는게 아니라 말그대로 summary를 보여주신다고요~
근데 아마 이미지 수정할 것 없이 view 구현이 다 된것 같아서, 해당 view를 보여주는 것으로 pass하겠습니다 ㅎ_ㅎ.
